/**
 * UI-Texte für Domäne `customers` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const customers = {
    title: 'Kunden',
    subtitle: 'Kundenstamm verwalten',
    newCustomer: 'Neuer Kunde',
    searchPlaceholder: 'Suche nach Name oder Kundennr. …',
    empty: 'Noch keine Kunden vorhanden.',
    emptyAction: 'Ersten Kunden anlegen →',
    noResults: 'Keine Kunden gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Kunden anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Kunde löschen?',
    deleteConfirm:
      'Der Kunde wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      customerNumber: 'Kundennr.',
      companyName: 'Firmenname',
      city: 'Ort',
      industry: 'Branche',
      rating: 'Bewertung',
      status: 'Status',
    },
    status: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
    },
    tabs: {
      master: 'Stammdaten',
      emails: 'E-Mails',
      bankAccounts: 'Bankverbindungen',
      branches: 'Niederlassungen',
      contacts: 'Ansprechpartner',
      businessCards: 'Visitenkarten',
      submissions: 'Ausschreibungen',
      documents: 'Dokumente',
      printTab: 'Aktuelle Ansicht drucken',
      printAll: 'Gesamtübersicht drucken',
    },
    fields: {
      companyName: 'Firmenname',
      legalForm: 'Rechtsform',
      customerNumber: 'Kundennummer',
      status: 'Status',
      industry: 'Branche',
      rating: 'Bewertung',
      paymentTermDays: 'Zahlungsziel (Tage)',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      phone: 'Telefon',
      website: 'Website',
      vatId: 'USt-ID',
      taxNumber: 'Steuernummer',
      notes: 'Notizen',
      email: 'E-Mail',
      emailType: 'Typ',
      label: 'Bezeichnung',
      isPrimary: 'Primär',
      bankName: 'Bankname',
      iban: 'IBAN',
      bic: 'BIC',
      accountHolder: 'Kontoinhaber',
      branchName: 'Name',
      branchType: 'Typ',
      title: 'Anrede',
      titleNone: '—',
      titleHerr: 'Herr',
      titleFrau: 'Frau',
      titleFirma: 'Firma',
      firstName: 'Vorname',
      lastName: 'Nachname',
      role: 'Funktion',
      department: 'Abteilung',
      branch: 'Niederlassung',
      phoneMobile: 'Mobil',
      phoneLandline: 'Festnetz',
      birthday: 'Geburtstag',
      linkedInUrl: 'LinkedIn',
      preferredContactMethod: 'Bevorzugter Kontakt',
      isAccountingContact: 'Buchhaltung',
      isProjectContact: 'Projektleitung',
      isSignatory: 'Unterschriftsberechtigt',
    },
    sections: {
      base: 'Basisdaten',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      contactInfo: 'Kontakt',
      tax: 'Steuer',
    },
    actions: {
      openRoute: 'Route öffnen',
      addEmail: 'E-Mail hinzufügen',
      addBankAccount: 'Bankverbindung hinzufügen',
      addBranch: 'Niederlassung hinzufügen',
      addContact: 'Ansprechpartner hinzufügen',
      uploadBusinessCard: 'Visitenkarte hochladen',
      scanBusinessCard: 'Visitenkarte scannen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      print: 'Drucken',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      setPrimary: 'Als primär',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      details: 'Details',
      close: 'Schließen',
    },
    empties: {
      emails: 'Noch keine E-Mail-Adressen.',
      bankAccounts: 'Noch keine Bankverbindungen.',
      branches: 'Noch keine Niederlassungen.',
      contacts: 'Noch keine Ansprechpartner.',
      documents: 'Noch keine Dokumente.',
      addNow: 'Jetzt anlegen →',
    },
    contactsView: {
      layout: 'Darstellung',
      table: 'Tabelle',
      cols2: '2 Spalten',
      cols3: '3 Spalten',
      cols4: '4 Spalten',
    },
    headquarters: 'Hauptsitz',
    allBranches: 'Alle Standorte',
    coordinates: 'Koordinaten',
    branchContacts: 'Ansprechpartner',
    branchContactsEmpty: 'Keine Ansprechpartner für diese Niederlassung.',
    maxBankReached: 'Maximal 2 Bankverbindungen erreicht.',
    documentTypes: {
      BUSINESS_CARD: 'Visitenkarte',
      CONTRACT: 'Vertrag',
      LOGO: 'Logo',
      CERTIFICATE: 'Zertifikat',
      NOTE_DOCUMENT: 'Notiz-Dokument',
      OTHER: 'Sonstiges',
    },
    emailTypes: {
      GENERAL: 'Allgemein',
      BILLING: 'Rechnung',
      SERVICE: 'Service',
      SUPPORT: 'Support',
      PROJECT: 'Projekt',
      OTHER: 'Sonstiges',
    },
    branchTypes: {
      HEADQUARTERS: 'Hauptsitz',
      OFFICE: 'Büro',
      WAREHOUSE: 'Lager',
      SITE: 'Standort',
      OTHER: 'Sonstiges',
    },
    contactMethods: {
      EMAIL: 'E-Mail',
      PHONE: 'Festnetz',
      MOBILE: 'Mobil',
    },
    contactSearch: {
      button: 'Kontakte suchen',
      placeholder: 'Website-URL eingeben...',
      loading: 'Suche Kontakte...',
      found: (n: number): string =>
        `${n} Kontaktperson${n !== 1 ? 'en' : ''} gefunden`,
      noResults: 'Keine Kontaktpersonen gefunden',
      selectAll: 'Alle auswählen',
      selectNone: 'Keine auswählen',
      import: 'Ausgewählte übernehmen',
      importing: 'Kontakte werden angelegt...',
      success: (n: number): string =>
        `${n} Kontakt${n !== 1 ? 'e' : ''} erfolgreich angelegt`,
      syncToGoogle: 'Zu Google Kontakte synchronisieren',
    },
    research: {
      button: 'Auto-Recherche',
      loading: 'Recherchiere …',
      dialogTitle: 'Auto-Recherche Ergebnis',
      companySection: 'Firmendaten',
      contactsSection: 'Ansprechpartner',
      socialSection: 'Social Media',
      sources: 'Quellen',
      confidence: 'Konfidenz',
      field: 'Feld',
      value: 'Gefundener Wert',
      apply: 'Ausgewählte übernehmen',
      applyContact: 'Übernehmen',
      syncGoogle: 'Mit Google Kontakte synchronisieren',
      syncGoogleHint: 'Kontakt wird in Google Kontakte angelegt/aktualisiert',
      noData: 'Keine Daten gefunden.',
      serviceError: 'Research-Service nicht verfügbar',
      applied: (fields: number, contacts: number): string =>
        `${fields} Felder und ${contacts} Kontakte übernommen`,
    },
    submissions: {
      tab: 'Ausschreibungen',
      title: 'Ausschreibungen',
      newSubmission: 'Neue Ausschreibung',
      searchButton: 'Ausschreibungen suchen',
      empty: 'Noch keine Ausschreibungen.',
      addNow: 'Jetzt anlegen →',
      columns: {
        title: 'Titel',
        status: 'Status',
        priority: 'Priorität',
        deadline: 'Abgabefrist',
        value: 'Wert',
        reference: 'Referenz',
      },
      status: {
        OPEN: 'Offen',
        IN_PROGRESS: 'In Bearbeitung',
        SUBMITTED: 'Eingereicht',
        WON: 'Gewonnen',
        LOST: 'Verloren',
        CANCELLED: 'Abgesagt',
      } as Record<string, string>,
      priority: {
        LOW: 'Niedrig',
        MEDIUM: 'Mittel',
        HIGH: 'Hoch',
        URGENT: 'Dringend',
      } as Record<string, string>,
      fields: {
        title: 'Titel',
        description: 'Beschreibung',
        reference: 'Referenz/Vergabenummer',
        source: 'Quelle/URL',
        status: 'Status',
        priority: 'Priorität',
        deadline: 'Abgabefrist',
        startDate: 'Projektbeginn',
        endDate: 'Projektende',
        value: 'Geschätzter Wert (€)',
        contactName: 'Ansprechpartner',
        contactEmail: 'E-Mail',
        contactPhone: 'Telefon',
        requirements: 'Anforderungen',
        notes: 'Notizen',
      },
      sections: {
        base: 'Basisdaten',
        dates: 'Termine',
        contact: 'Ansprechpartner',
        details: 'Details',
      },
      search: {
        dialogTitle: 'Ausschreibungen suchen',
        urlPlaceholder: 'URL der Ausschreibungsseite eingeben …',
        searching: 'Suche Ausschreibungen …',
        found: (n: number): string =>
          `${n} Ausschreibung${n !== 1 ? 'en' : ''} gefunden`,
        noResults: 'Keine Ausschreibungen gefunden.',
        selectAll: 'Alle auswählen',
        selectNone: 'Keine auswählen',
        import: 'Ausgewählte importieren',
        importing: 'Wird importiert …',
        imported: (n: number): string =>
          `${n} Ausschreibung${n !== 1 ? 'en' : ''} importiert`,
        confidence: 'Konfidenz',
      },
      toast: {
        created: 'Ausschreibung angelegt.',
        updated: 'Ausschreibung gespeichert.',
        deleted: 'Ausschreibung gelöscht.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    toast: {
      created: 'Kunde angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Kunde gelöscht.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      scanSuccess: 'Visitenkarte erfolgreich gescannt.',
      scanError: 'Visitenkarte konnte nicht gescannt werden.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  } as const;
