/**
 * UI-Texte für Domäne `documents` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const documents = {
    title: 'Dokumente',
    subtitle: 'Alle Dokumente durchsuchen und verwalten',
    nav: 'Dokumente',
    // Globale Suche
    searchPlaceholder: 'Nach Dateiname, Titel oder Tags suchen …',
    allTypes: 'Alle Typen',
    allEntities: 'Alle Bereiche',
    onlyExpiring: 'Nur ablaufende',
    results: 'Treffer',
    noResults: 'Keine Dokumente gefunden.',
    pagination: {
      showing: 'Treffer',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    linkedTo: 'Verknüpft mit',
    uploadedAt: 'Hochgeladen',
    uploadedBy: 'von',
    // Tab / Entitäts-Ansicht
    allFolder: 'Alle',
    empty: 'Noch keine Dokumente.',
    search: 'Suchen …',
    gridView: 'Kacheln',
    listView: 'Liste',
    newFolder: 'Ordner',
    newFolderTitle: 'Neuer Ordner',
    newFolderName: 'Ordnername',
    renameFolder: 'Ordner umbenennen',
    deleteFolder: 'Ordner löschen',
    deleteFolderConfirm:
      'Ordner wirklich löschen? (nur möglich, wenn er leer ist)',
    // Aktionen
    upload: 'Hochladen',
    takePhoto: 'Foto aufnehmen',
    download: 'Herunterladen',
    open: 'Öffnen',
    preview: 'Vorschau',
    replace: 'Ersetzen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    versions: 'Versionen',
    versionHistory: 'Versions-Historie',
    deleteTitle: 'Dokument löschen?',
    deleteConfirm: 'Das Dokument wird unwiderruflich aus dem Speicher entfernt.',
    cancel: 'Abbrechen',
    save: 'Speichern',
    // Badges
    versionBadge: 'V',
    expiresOn: 'Läuft ab am',
    expired: 'Abgelaufen',
    expiringSoon: 'Läuft bald ab',
    // Upload-Dialog
    uploadTitle: 'Dokumente hochladen',
    dropZone: 'Dateien hierher ziehen oder klicken zum Auswählen',
    dropZoneActive: 'Dateien hier ablegen …',
    selectFiles: 'Dateien wählen',
    fileType: 'Typ',
    fileTitle: 'Titel',
    fileTags: 'Tags (komma-getrennt)',
    fileExpiry: 'Ablaufdatum',
    folder: 'Ordner',
    noFolder: 'Kein Ordner',
    removeFile: 'Entfernen',
    startUpload: 'Hochladen',
    uploading: 'Wird hochgeladen …',
    uploadDone: 'Upload abgeschlossen.',
    // Bild-Editor
    editorTitle: 'Bild bearbeiten',
    rotateLeft: 'Links drehen',
    rotateRight: 'Rechts drehen',
    crop: 'Zuschneiden',
    cropApply: 'Zuschnitt anwenden',
    cropCancel: 'Zuschnitt abbrechen',
    brightness: 'Helligkeit',
    contrast: 'Kontrast',
    reset: 'Zurücksetzen',
    apply: 'Übernehmen',
    // Lightbox
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    prev: 'Zurück',
    next: 'Weiter',
    close: 'Schließen',
    // Toasts
    toast: {
      uploaded: 'Dokument(e) hochgeladen.',
      replaced: 'Neue Version gespeichert.',
      deleted: 'Dokument gelöscht.',
      folderCreated: 'Ordner erstellt.',
      folderDeleted: 'Ordner gelöscht.',
      folderRenamed: 'Ordner umbenannt.',
      error: 'Aktion fehlgeschlagen.',
    },
    entityTypes: {
      CUSTOMER: 'Kunde',
      BRANCH: 'Standort',
      CONTACT: 'Kontakt',
      PROJECT: 'Projekt',
      WORKER: 'Monteur',
      VEHICLE: 'Fahrzeug',
    } as Record<string, string>,
    documentTypes: {
      PHOTO: 'Foto',
      DELIVERY_NOTE: 'Lieferschein',
      INVOICE: 'Rechnung',
      PROJECT_DOC: 'Projektdokument',
      BUSINESS_CARD: 'Visitenkarte',
      CONTRACT: 'Vertrag',
      LOGO: 'Logo',
      CERTIFICATE: 'Zertifikat',
      NOTE_DOCUMENT: 'Notiz-Dokument',
      DRAWING: 'Zeichnung',
      WORK_CONTRACT: 'Werkvertrag',
      SPECIFICATION: 'Leistungsverzeichnis',
      SITE_PHOTO: 'Baustellenfoto',
      HANDOVER_PROTOCOL: 'Abnahmeprotokoll',
      PASSPORT: 'Reisepass',
      ID_CARD: 'Personalausweis',
      WORK_PERMIT: 'Arbeitserlaubnis',
      RESIDENCE_PERMIT: 'Aufenthaltsgenehmigung',
      CERTIFICATION: 'Zertifizierung',
      HEALTH_CERTIFICATE: 'Gesundheitszeugnis',
      WORKER_PHOTO: 'Profilbild',
      REGISTRATION_DOC: 'Fahrzeugschein',
      INSURANCE_DOC: 'Versicherungsnachweis',
      INSPECTION_DOC: 'TÜV/HU-Bericht',
      OTHER: 'Sonstiges',
    } as Record<string, string>,
  } as const;
