/** UI-Texte: `equipment`. */
export const equipment = {
    title: 'Geräte & Werkzeuge',
    titleSingle: 'Gerät',
    subtitle: 'Werkzeuge und Geräte verwalten',
    new: 'Neues Gerät',
    searchPlaceholder: 'Suche nach Name, Seriennr. oder Inventarnr. …',
    empty: 'Noch keine Geräte vorhanden.',
    emptyAction: 'Erstes Gerät anlegen →',
    noResults: 'Keine Geräte gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Gerät anlegen',
    createSubtitle: 'Stammdaten erfassen – Zuweisungen folgen im Detail.',
    deleteTitle: 'Gerät löschen?',
    deleteConfirm: 'Das Gerät wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    fields: {
      name: 'Bezeichnung',
      description: 'Beschreibung',
      category: 'Kategorie',
      manufacturer: 'Hersteller',
      model: 'Modell',
      serialNumber: 'Seriennummer',
      inventoryNumber: 'Inventarnummer',
      purchaseDate: 'Kaufdatum',
      purchasePrice: 'Kaufpreis',
      status: 'Status',
      condition: 'Zustand',
      image: 'Foto',
      notes: 'Notizen',
    },
    status: {
      AVAILABLE: 'Verfügbar',
      ASSIGNED: 'Ausgegeben',
      IN_REPAIR: 'In Reparatur',
      RETIRED: 'Ausgemustert',
    } as Record<string, string>,
    condition: {
      NEW: 'Neu',
      GOOD: 'Gut',
      FAIR: 'Befriedigend',
      POOR: 'Schlecht',
      DEFECTIVE: 'Defekt',
    } as Record<string, string>,
    tabs: { master: 'Stammdaten', assignments: 'Zuweisungen' },
    sections: {
      base: 'Basisdaten',
      purchase: 'Einkauf',
      state: 'Status & Zustand',
      notes: 'Notizen',
    },
    assign: {
      button: 'Ausgeben',
      title: 'Gerät ausgeben',
      worker: 'Monteur',
      expectedReturn: 'Erwartete Rückgabe',
      notes: 'Notizen',
      submit: 'Ausgeben',
    },
    return: {
      button: 'Rückgabe',
      title: 'Gerät zurücknehmen',
      condition: 'Zustand bei Rückgabe',
      notes: 'Bemerkungen',
      submit: 'Rückgabe bestätigen',
    },
    history: {
      title: 'Zuweisungs-Historie',
      worker: 'Monteur',
      assignedAt: 'Ausgegeben am',
      returnedAt: 'Zurück am',
      expected: 'Erwartet',
      condition: 'Zustand',
      notes: 'Notizen',
      current: 'Aktuell ausgegeben',
    },
    columns: {
      name: 'Bezeichnung',
      category: 'Kategorie',
      status: 'Status',
      condition: 'Zustand',
      assignedTo: 'Zugewiesen an',
    },
    filters: {
      all: 'Alle',
      status: 'Status',
      category: 'Kategorie',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      uploadImage: 'Foto hochladen',
      changeImage: 'Foto ändern',
    },
    toast: {
      created: 'Gerät erfolgreich angelegt.',
      updated: 'Gerät aktualisiert.',
      deleted: 'Gerät gelöscht.',
      assigned: 'Gerät ausgegeben.',
      returned: 'Rückgabe registriert.',
      imageUploaded: 'Foto hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
    workerSection: 'Zugewiesene Geräte',
    workerSectionEmpty: 'Keine Geräte zugewiesen.',
  } as const;
