/**
 * UI-Texte für Domäne `invoices` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const invoices = {
  title: 'Rechnungen',
  subtitle: 'Ausgangsrechnungen, Stornorechnungen und Korrekturen verwalten',
  newInvoice: 'Neue Rechnung',
  generate: 'Aus Stundenzetteln',
  searchPlaceholder: 'Suche nach Rechnungsnr. …',
  empty: 'Noch keine Rechnungen vorhanden.',
  noResults: 'Keine Rechnungen gefunden.',
  backToList: 'Zurück zur Übersicht',
  draftNumber: 'Entwurf',
  pagination: {
    showing: 'Einträge',
    page: 'Seite',
    of: 'von',
    prev: 'Zurück',
    next: 'Weiter',
  },
  tabsType: {
    outgoing: 'Ausgangsrechnungen',
    storno: 'Stornorechnungen',
    correction: 'Korrekturen',
  },
  columns: {
    invoiceNumber: 'Rechnungs-Nr.',
    party: 'Kunde',
    project: 'Projekt',
    period: 'Zeitraum',
    net: 'Netto',
    gross: 'Brutto',
    status: 'Status',
    dueDate: 'Fällig am',
  },
  filters: {
    all: 'Alle',
    status: 'Status',
    project: 'Projekt',
    periodFrom: 'Von',
    periodTo: 'Bis',
  },
  status: {
    DRAFT: 'Entwurf',
    SENT: 'Finalisiert',
    PARTIALLY_PAID: 'Teilbezahlt',
    PAID: 'Bezahlt',
    PARTIALLY_CORRECTED: 'Teilkorrigiert',
    CANCELLED: 'Storniert',
  },
  type: {
    OUTGOING: 'Ausgangsrechnung',
    INCOMING: 'Eingangsrechnung',
    STORNO: 'Stornorechnung',
    CORRECTION: 'Rechnungskorrektur',
  },
  correctionReason: {
    INVOICE_ERROR: 'Rechnungsfehler',
    CONSIDERATION_REDUCTION: 'Entgeltminderung',
  },
  lineType: {
    WEEKLY_PACKAGE: 'Wochenpaket',
    OVERTIME: 'Überstunden',
    UNIT_BASED: 'Einheit',
    PARTIAL_PAYMENT: 'Abschlag',
    CUSTOM: 'Frei',
  },
  overdue: 'Überfällig',
  partial: 'Teilrechnung',
  partialLabel: (n: number, pct: number | null): string =>
    pct != null ? `${n}. Abschlag (${pct}%)` : `${n}. Abschlag`,
  tabs: {
    lines: 'Positionen',
    payments: 'Zahlungen',
    details: 'Details',
  },
  lines: {
    title: 'Positionen',
    position: 'Pos',
    type: 'Typ',
    description: 'Beschreibung',
    quantity: 'Menge',
    unit: 'Einheit',
    unitPrice: 'Einzelpreis',
    discount: 'Rabatt',
    total: 'Gesamt',
    add: 'Position hinzufügen',
    edit: 'Bearbeiten',
    moveUp: 'Nach oben',
    moveDown: 'Nach unten',
    empty: 'Noch keine Positionen erfasst.',
    readonlyHint: 'Positionen können nur im Entwurf bearbeitet werden.',
    subtotal: 'Netto',
    tax: 'MwSt',
    grandTotal: 'Brutto',
    product: 'Produkt',
    selectProduct: 'Produkt wählen (optional)',
    discountPercent: 'Rabatt %',
    discountAmount: 'Rabatt €',
    fromCustomerPrice: 'Kundenpreis',
  },
  lineDialog: {
    addTitle: 'Position hinzufügen',
    editTitle: 'Position bearbeiten',
    type: 'Typ',
    description: 'Beschreibung',
    quantity: 'Menge',
    unit: 'Einheit',
    unitPrice: 'Einzelpreis (€)',
    product: 'Produkt',
    selectProduct: 'Kein Produkt',
    discountPercent: 'Rabatt (%)',
    discountAmount: 'Rabatt (€)',
    preview: 'Gesamt',
    save: 'Speichern',
    saving: 'Wird gespeichert …',
    cancel: 'Abbrechen',
  },
  payments: {
    title: 'Zahlungen',
    date: 'Datum',
    amount: 'Betrag',
    method: 'Methode',
    reference: 'Referenz',
    skonto: 'Skonto',
    add: 'Zahlung erfassen',
    empty: 'Noch keine Zahlungseingänge.',
    progress: (paid: string, total: string): string =>
      `${paid} von ${total} bezahlt`,
    open: 'Offen',
    cancelledHint:
      'Für stornierte Rechnungen können keine Zahlungen erfasst werden.',
  },
  paymentDialog: {
    title: 'Zahlung erfassen',
    amount: 'Betrag (€)',
    date: 'Zahlungsdatum',
    method: 'Methode',
    reference: 'Referenz (optional)',
    skontoApplied: 'Skonto gezogen',
    skontoAmount: 'Skontobetrag (€)',
    save: 'Speichern',
    saving: 'Wird gespeichert …',
    cancel: 'Abbrechen',
  },
  methods: {
    TRANSFER: 'Überweisung',
    CASH: 'Bar',
    PAYPAL: 'PayPal',
    OTHER: 'Sonstige',
  },
  taxKind: {
    label: 'Steuerart',
    STANDARD: 'Regelsteuersatz',
    REDUCED: 'Ermäßigt',
    REVERSE_CHARGE: 'Reverse Charge (§13b)',
    TAX_EXEMPT: 'Steuerbefreit',
  },
  skontoPage: {
    title: 'Skonto-Auswertung',
    subtitle: 'Zahlungen mit gezogenem Skonto',
    empty: 'Keine Skonto-Zahlungen erfasst.',
    invoice: 'Rechnung',
    customer: 'Kunde',
    date: 'Datum',
    amount: 'Zahlung',
    skontoAmount: 'Skonto',
    sumSkonto: 'Summe Skonto',
    periodFrom: 'Von',
    periodTo: 'Bis',
    back: 'Zurück zu Rechnungen',
  },
  emailDialog: {
    title: 'Per E-Mail senden',
    recipient: 'Empfänger (Billing)',
    noRecipient: 'Keine Billing-E-Mail hinterlegt.',
    attachments: 'Anhänge aus Kundendokumenten',
    timesheets: 'Verknüpfte Stundenzettel-PDFs',
    noAttachments: 'Keine Kundendokumente vorhanden.',
    noTimesheets: 'Keine Stundenzettel an Positionen verknüpft.',
    eInvoice: 'E-Rechnung',
    attachZugferd: 'ZUGFeRD-PDF anhängen',
    attachXRechnung: 'XRechnung-XML anhängen',
    send: 'Senden',
    sending: 'Wird gesendet …',
    cancel: 'Abbrechen',
  },
  details: {
    title: 'Rechnungsdetails',
    invoiceNumber: 'Rechnungsnummer',
    type: 'Typ',
    status: 'Status',
    issueDate: 'Ausstelldatum',
    dueDate: 'Fälligkeitsdatum',
    paidDate: 'Bezahlt am',
    project: 'Projekt',
    customer: 'Kunde',
    subcontractor: 'Subunternehmen',
    period: 'Zeitraum',
    paymentTerm: 'Zahlungsziel (Tage)',
    performanceCountry: 'Leistungsort',
    taxKind: 'Steuerart',
    creditedInvoice: 'Bezug (Rechnung)',
    relatedDocs: 'ST / KO',
    correctionReason: 'Korrekturgrund',
    taxPeriod: 'Steuerperiode',
    finalizedAt: 'Finalisiert am',
    finalizedBy: 'Finalisiert von',
    partialTitle: 'Teilrechnung',
    partialNumber: 'Abschlagsnummer',
    partialPercentage: 'Prozentsatz (%)',
    notesTitle: 'Notizen',
    notes: 'Notizen (auf Rechnung)',
    internalNotes: 'Interne Notizen',
    createdBy: 'Erstellt von',
    none: '–',
  },
  actions: {
    finalize: 'Finalisieren',
    pdf: 'PDF Vorschau',
    xrechnung: 'XRechnung XML',
    zugferd: 'ZUGFeRD PDF',
    sendEmail: 'Per E-Mail senden',
    cancel: 'Entwurf stornieren',
    storno: 'Stornorechnung erstellen',
    correction: 'Rechnungskorrektur',
    duplicate: 'Rechnung duplizieren',
    delete: 'Entwurf löschen',
    save: 'Speichern',
    saving: 'Wird gespeichert …',
    saveInternalNotes: 'Internen Kommentar speichern',
    skontoReport: 'Skonto-Auswertung',
  },
  finalizeDialog: {
    title: 'Rechnung finalisieren?',
    description: (preview: string): string =>
      `Die Rechnung erhält die Nummer ${preview} und ist danach unveränderbar (außer Zahlung und interner Kommentar).`,
    confirm: 'Finalisieren',
    cancel: 'Abbrechen',
  },
  stornoDialog: {
    title: 'Stornorechnung erstellen?',
    description:
      'Es wird eine Stornorechnung (ST-…) mit Bezug auf diese Rechnung erzeugt. Das Original bleibt mit Beträgen und PDF nachvollziehbar erhalten und wird als storniert markiert.',
    reason: 'Korrekturgrund',
    confirm: 'Stornorechnung erstellen',
    cancel: 'Abbrechen',
  },
  correctionDialog: {
    title: 'Rechnungskorrektur anlegen?',
    description:
      'Es wird ein Korrektur-Entwurf (KO) angelegt. Positionen können angepasst und danach finalisiert werden.',
    reason: 'Korrekturgrund',
    confirm: 'Korrektur-Entwurf anlegen',
    cancel: 'Abbrechen',
  },
  cancelDialog: {
    title: 'Entwurf stornieren?',
    description:
      'Der Entwurf wird als storniert markiert. Dies kann nicht rückgängig gemacht werden.',
    confirm: 'Stornieren',
    cancel: 'Abbrechen',
  },
  deleteDialog: {
    title: 'Entwurf löschen?',
    description: 'Der Rechnungsentwurf wird unwiderruflich gelöscht.',
    confirm: 'Löschen',
    cancel: 'Abbrechen',
  },
  generateDialog: {
    title: 'Rechnung aus Stundenzetteln',
    description:
      'Erzeugt einen Rechnungsentwurf aus genehmigten Stundenzetteln des gewählten Zeitraums.',
    project: 'Projekt',
    periodFrom: 'Zeitraum von',
    periodTo: 'Zeitraum bis',
    selectProject: 'Projekt wählen',
    confirm: 'Generieren',
    generating: 'Wird generiert …',
  },
  create: {
    title: 'Neue Ausgangsrechnung',
    subtitle: 'Rechnung manuell anlegen – Positionen folgen im Entwurf.',
    project: 'Projekt (optional)',
    customer: 'Kunde',
    selectProject: 'Projekt wählen',
    selectCustomer: 'Kunde wählen',
    none: 'Kein',
    performanceCountry: 'Leistungsort',
    selectCountry: 'Land wählen',
    taxRate: 'MwSt-Satz (%)',
    taxKind: 'Steuerart',
    periodFrom: 'Zeitraum von (optional)',
    periodTo: 'Zeitraum bis (optional)',
    isPartial: 'Teilrechnung',
    partialNumber: 'Abschlagsnummer',
    partialPercentage: 'Prozentsatz (%)',
    notes: 'Notizen (auf Rechnung)',
    internalNotes: 'Interne Notizen',
    submit: 'Rechnung anlegen',
    submitting: 'Wird angelegt …',
    cancel: 'Abbrechen',
  },
  toast: {
    created: 'Rechnung angelegt.',
    generated: 'Rechnungsentwurf erstellt.',
    updated: 'Gespeichert.',
    deleted: 'Rechnung gelöscht.',
    finalized: 'Rechnung finalisiert.',
    cancelled: 'Entwurf storniert.',
    storno: 'Stornorechnung erstellt.',
    correction: 'Korrektur-Entwurf angelegt.',
    duplicated: 'Rechnung dupliziert.',
    lineSaved: 'Position gespeichert.',
    lineDeleted: 'Position entfernt.',
    reordered: 'Reihenfolge geändert.',
    paymentSaved: 'Zahlung erfasst.',
    paymentDeleted: 'Zahlung gelöscht.',
    emailSent: 'E-Mail gesendet.',
    pdf: 'PDF wird heruntergeladen.',
    xrechnung: 'XRechnung wird heruntergeladen.',
    zugferd: 'ZUGFeRD wird heruntergeladen.',
    error: 'Aktion fehlgeschlagen.',
  },
  permissionDenied: 'Keine Berechtigung für Rechnungen.',
} as const;
