/**
 * UI-Texte für Domäne `invoices` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const invoices = {
    title: 'Rechnungen',
    subtitle: 'Aus- und Eingangsrechnungen verwalten',
    newInvoice: 'Neue Rechnung',
    generate: 'Aus Stundenzetteln',
    searchPlaceholder: 'Suche nach Rechnungsnr. …',
    empty: 'Noch keine Rechnungen vorhanden.',
    noResults: 'Keine Rechnungen gefunden.',
    backToList: 'Zurück zur Übersicht',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    tabsType: {
      outgoing: 'Ausgangsrechnungen',
      incoming: 'Eingangsrechnungen',
    },
    columns: {
      invoiceNumber: 'Rechnungs-Nr.',
      party: 'Kunde / Sub',
      project: 'Projekt',
      period: 'Zeitraum',
      net: 'Netto',
      gross: 'Brutto',
      status: 'Status',
      dueDate: 'Fällig am',
    },
    filters: {
      all: 'Alle',
      status: 'Status',
      project: 'Projekt',
      periodFrom: 'Von',
      periodTo: 'Bis',
    },
    status: {
      DRAFT: 'Entwurf',
      SENT: 'Versendet',
      PARTIALLY_PAID: 'Teilbezahlt',
      PAID: 'Bezahlt',
      CANCELLED: 'Storniert',
    },
    type: {
      OUTGOING: 'Ausgangsrechnung',
      INCOMING: 'Eingangsrechnung',
    },
    lineType: {
      WEEKLY_PACKAGE: 'Wochenpaket',
      OVERTIME: 'Überstunden',
      UNIT_BASED: 'Einheit',
      PARTIAL_PAYMENT: 'Abschlag',
      CUSTOM: 'Frei',
    },
    overdue: 'Überfällig',
    partial: 'Teilrechnung',
    partialLabel: (n: number, pct: number | null): string =>
      pct != null ? `${n}. Abschlag (${pct}%)` : `${n}. Abschlag`,
    tabs: {
      lines: 'Positionen',
      payments: 'Zahlungen',
      details: 'Details',
    },
    lines: {
      title: 'Positionen',
      position: 'Pos',
      type: 'Typ',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einheit',
      unitPrice: 'Einzelpreis',
      total: 'Gesamt',
      add: 'Position hinzufügen',
      edit: 'Bearbeiten',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      empty: 'Noch keine Positionen erfasst.',
      readonlyHint:
        'Positionen können nur im Entwurf bearbeitet werden.',
      subtotal: 'Netto',
      tax: 'MwSt',
      grandTotal: 'Brutto',
    },
    lineDialog: {
      addTitle: 'Position hinzufügen',
      editTitle: 'Position bearbeiten',
      type: 'Typ',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einheit',
      unitPrice: 'Einzelpreis (€)',
      preview: 'Gesamt',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    payments: {
      title: 'Zahlungen',
      date: 'Datum',
      amount: 'Betrag',
      method: 'Methode',
      reference: 'Referenz',
      add: 'Zahlung erfassen',
      empty: 'Noch keine Zahlungseingänge.',
      progress: (paid: string, total: string): string =>
        `${paid} von ${total} bezahlt`,
      open: 'Offen',
      cancelledHint:
        'Für stornierte Rechnungen können keine Zahlungen erfasst werden.',
    },
    paymentDialog: {
      title: 'Zahlung erfassen',
      amount: 'Betrag (€)',
      date: 'Zahlungsdatum',
      method: 'Methode',
      reference: 'Referenz (optional)',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    methods: {
      TRANSFER: 'Überweisung',
      CASH: 'Bar',
      PAYPAL: 'PayPal',
      OTHER: 'Sonstige',
    },
    details: {
      title: 'Rechnungsdetails',
      invoiceNumber: 'Rechnungsnummer',
      type: 'Typ',
      status: 'Status',
      issueDate: 'Ausstelldatum',
      dueDate: 'Fälligkeitsdatum',
      paidDate: 'Bezahlt am',
      project: 'Projekt',
      customer: 'Kunde',
      subcontractor: 'Subunternehmen',
      period: 'Zeitraum',
      paymentTerm: 'Zahlungsziel (Tage)',
      partialTitle: 'Teilrechnung',
      partialNumber: 'Abschlagsnummer',
      partialPercentage: 'Prozentsatz (%)',
      notesTitle: 'Notizen',
      notes: 'Notizen (auf Rechnung)',
      internalNotes: 'Interne Notizen',
      createdBy: 'Erstellt von',
      none: '–',
    },
    actions: {
      send: 'Als versendet markieren',
      pdf: 'PDF Vorschau',
      cancel: 'Rechnung stornieren',
      duplicate: 'Rechnung duplizieren',
      delete: 'Entwurf löschen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
    },
    cancelDialog: {
      title: 'Rechnung stornieren?',
      description:
        'Die Rechnung wird auf „Storniert" gesetzt und die Beträge auf 0 reduziert. Dies kann nicht rückgängig gemacht werden.',
      confirm: 'Stornieren',
      cancel: 'Abbrechen',
    },
    deleteDialog: {
      title: 'Entwurf löschen?',
      description: 'Der Rechnungsentwurf wird unwiderruflich gelöscht.',
      confirm: 'Löschen',
      cancel: 'Abbrechen',
    },
    generateDialog: {
      title: 'Rechnung aus Stundenzetteln',
      description:
        'Erzeugt einen Rechnungsentwurf aus genehmigten Stundenzetteln des gewählten Zeitraums.',
      type: 'Typ',
      project: 'Projekt',
      subcontractor: 'Subunternehmen',
      periodFrom: 'Zeitraum von',
      periodTo: 'Zeitraum bis',
      selectProject: 'Projekt wählen',
      selectSubcontractor: 'Subunternehmen wählen',
      confirm: 'Generieren',
      generating: 'Wird generiert …',
    },
    create: {
      title: 'Neue Rechnung',
      subtitle: 'Rechnung manuell anlegen – Positionen folgen im Entwurf.',
      type: 'Typ',
      project: 'Projekt (optional)',
      customer: 'Kunde',
      subcontractor: 'Subunternehmen',
      selectProject: 'Projekt wählen',
      selectCustomer: 'Kunde wählen',
      selectSubcontractor: 'Subunternehmen wählen',
      none: 'Kein',
      taxRate: 'MwSt-Satz (%)',
      periodFrom: 'Zeitraum von (optional)',
      periodTo: 'Zeitraum bis (optional)',
      isPartial: 'Teilrechnung',
      partialNumber: 'Abschlagsnummer',
      partialPercentage: 'Prozentsatz (%)',
      notes: 'Notizen (auf Rechnung)',
      internalNotes: 'Interne Notizen',
      submit: 'Rechnung anlegen',
      submitting: 'Wird angelegt …',
      cancel: 'Abbrechen',
    },
    toast: {
      created: 'Rechnung angelegt.',
      generated: 'Rechnungsentwurf erstellt.',
      updated: 'Gespeichert.',
      deleted: 'Rechnung gelöscht.',
      sent: 'Rechnung als versendet markiert.',
      cancelled: 'Rechnung storniert.',
      duplicated: 'Rechnung dupliziert.',
      lineSaved: 'Position gespeichert.',
      lineDeleted: 'Position entfernt.',
      reordered: 'Reihenfolge geändert.',
      paymentSaved: 'Zahlung erfasst.',
      paymentDeleted: 'Zahlung gelöscht.',
      pdf: 'PDF wird heruntergeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  } as const;
