/**
 * UI-Texte für Domäne `invoices` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const invoices = {
    title: 'Rechnungen',
    subtitle: 'Ausgangsrechnungen und Gutschriften verwalten',
    newInvoice: 'Neue Rechnung',
    generate: 'Aus Stundenzetteln',
    searchPlaceholder: 'Suche nach Rechnungsnr. …',
    empty: 'Noch keine Rechnungen vorhanden.',
    noResults: 'Keine Rechnungen gefunden.',
    backToList: 'Zurück zur Übersicht',
    draftNumber: 'Entwurf',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    tabsType: {
      outgoing: 'Ausgangsrechnungen',
      creditNotes: 'Gutschriften',
    },
    columns: {
      invoiceNumber: 'Rechnungs-Nr.',
      party: 'Kunde',
      project: 'Projekt',
      period: 'Zeitraum',
      net: 'Netto',
      gross: 'Brutto',
      status: 'Status',
      dueDate: 'Fällig am',
    },
    filters: {
      all: 'Alle',
      status: 'Status',
      project: 'Projekt',
      periodFrom: 'Von',
      periodTo: 'Bis',
    },
    status: {
      DRAFT: 'Entwurf',
      SENT: 'Finalisiert',
      PARTIALLY_PAID: 'Teilbezahlt',
      PAID: 'Bezahlt',
      CANCELLED: 'Storniert',
    },
    type: {
      OUTGOING: 'Ausgangsrechnung',
      INCOMING: 'Eingangsrechnung',
      CREDIT_NOTE: 'Gutschrift',
    },
    lineType: {
      WEEKLY_PACKAGE: 'Wochenpaket',
      OVERTIME: 'Überstunden',
      UNIT_BASED: 'Einheit',
      PARTIAL_PAYMENT: 'Abschlag',
      CUSTOM: 'Frei',
    },
    overdue: 'Überfällig',
    partial: 'Teilrechnung',
    partialLabel: (n: number, pct: number | null): string =>
      pct != null ? `${n}. Abschlag (${pct}%)` : `${n}. Abschlag`,
    tabs: {
      lines: 'Positionen',
      payments: 'Zahlungen',
      details: 'Details',
    },
    lines: {
      title: 'Positionen',
      position: 'Pos',
      type: 'Typ',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einheit',
      unitPrice: 'Einzelpreis',
      total: 'Gesamt',
      add: 'Position hinzufügen',
      edit: 'Bearbeiten',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      empty: 'Noch keine Positionen erfasst.',
      readonlyHint:
        'Positionen können nur im Entwurf bearbeitet werden.',
      subtotal: 'Netto',
      tax: 'MwSt',
      grandTotal: 'Brutto',
    },
    lineDialog: {
      addTitle: 'Position hinzufügen',
      editTitle: 'Position bearbeiten',
      type: 'Typ',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einheit',
      unitPrice: 'Einzelpreis (€)',
      preview: 'Gesamt',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    payments: {
      title: 'Zahlungen',
      date: 'Datum',
      amount: 'Betrag',
      method: 'Methode',
      reference: 'Referenz',
      add: 'Zahlung erfassen',
      empty: 'Noch keine Zahlungseingänge.',
      progress: (paid: string, total: string): string =>
        `${paid} von ${total} bezahlt`,
      open: 'Offen',
      cancelledHint:
        'Für stornierte Rechnungen können keine Zahlungen erfasst werden.',
    },
    paymentDialog: {
      title: 'Zahlung erfassen',
      amount: 'Betrag (€)',
      date: 'Zahlungsdatum',
      method: 'Methode',
      reference: 'Referenz (optional)',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    methods: {
      TRANSFER: 'Überweisung',
      CASH: 'Bar',
      PAYPAL: 'PayPal',
      OTHER: 'Sonstige',
    },
    details: {
      title: 'Rechnungsdetails',
      invoiceNumber: 'Rechnungsnummer',
      type: 'Typ',
      status: 'Status',
      issueDate: 'Ausstelldatum',
      dueDate: 'Fälligkeitsdatum',
      paidDate: 'Bezahlt am',
      project: 'Projekt',
      customer: 'Kunde',
      subcontractor: 'Subunternehmen',
      period: 'Zeitraum',
      paymentTerm: 'Zahlungsziel (Tage)',
      performanceCountry: 'Leistungsort',
      creditedInvoice: 'Bezug (Rechnung)',
      creditNotes: 'Gutschriften',
      finalizedAt: 'Finalisiert am',
      finalizedBy: 'Finalisiert von',
      partialTitle: 'Teilrechnung',
      partialNumber: 'Abschlagsnummer',
      partialPercentage: 'Prozentsatz (%)',
      notesTitle: 'Notizen',
      notes: 'Notizen (auf Rechnung)',
      internalNotes: 'Interne Notizen',
      createdBy: 'Erstellt von',
      none: '–',
    },
    actions: {
      finalize: 'Finalisieren',
      pdf: 'PDF Vorschau',
      cancel: 'Entwurf stornieren',
      creditNote: 'Stornieren / Gutschrift',
      duplicate: 'Rechnung duplizieren',
      delete: 'Entwurf löschen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      saveInternalNotes: 'Internen Kommentar speichern',
    },
    finalizeDialog: {
      title: 'Rechnung finalisieren?',
      description: (preview: string): string =>
        `Die Rechnung erhält die Nummer ${preview} und ist danach unveränderbar (außer Zahlung und interner Kommentar).`,
      confirm: 'Finalisieren',
      cancel: 'Abbrechen',
    },
    creditNoteDialog: {
      title: 'Stornieren und Gutschrift erstellen?',
      description:
        'Es wird eine Gutschrift (GS-…) mit Bezug auf diese Rechnung erzeugt. Das Original bleibt mit Beträgen und PDF nachvollziehbar erhalten und wird als storniert markiert.',
      confirm: 'Gutschrift erstellen',
      cancel: 'Abbrechen',
    },
    cancelDialog: {
      title: 'Entwurf stornieren?',
      description:
        'Der Entwurf wird als storniert markiert. Dies kann nicht rückgängig gemacht werden.',
      confirm: 'Stornieren',
      cancel: 'Abbrechen',
    },
    deleteDialog: {
      title: 'Entwurf löschen?',
      description: 'Der Rechnungsentwurf wird unwiderruflich gelöscht.',
      confirm: 'Löschen',
      cancel: 'Abbrechen',
    },
    generateDialog: {
      title: 'Rechnung aus Stundenzetteln',
      description:
        'Erzeugt einen Rechnungsentwurf aus genehmigten Stundenzetteln des gewählten Zeitraums.',
      project: 'Projekt',
      periodFrom: 'Zeitraum von',
      periodTo: 'Zeitraum bis',
      selectProject: 'Projekt wählen',
      confirm: 'Generieren',
      generating: 'Wird generiert …',
    },
    create: {
      title: 'Neue Ausgangsrechnung',
      subtitle: 'Rechnung manuell anlegen – Positionen folgen im Entwurf.',
      project: 'Projekt (optional)',
      customer: 'Kunde',
      selectProject: 'Projekt wählen',
      selectCustomer: 'Kunde wählen',
      none: 'Kein',
      performanceCountry: 'Leistungsort',
      selectCountry: 'Land wählen',
      taxRate: 'MwSt-Satz (%)',
      periodFrom: 'Zeitraum von (optional)',
      periodTo: 'Zeitraum bis (optional)',
      isPartial: 'Teilrechnung',
      partialNumber: 'Abschlagsnummer',
      partialPercentage: 'Prozentsatz (%)',
      notes: 'Notizen (auf Rechnung)',
      internalNotes: 'Interne Notizen',
      submit: 'Rechnung anlegen',
      submitting: 'Wird angelegt …',
      cancel: 'Abbrechen',
    },
    toast: {
      created: 'Rechnung angelegt.',
      generated: 'Rechnungsentwurf erstellt.',
      updated: 'Gespeichert.',
      deleted: 'Rechnung gelöscht.',
      finalized: 'Rechnung finalisiert.',
      cancelled: 'Entwurf storniert.',
      creditNote: 'Gutschrift erstellt.',
      duplicated: 'Rechnung dupliziert.',
      lineSaved: 'Position gespeichert.',
      lineDeleted: 'Position entfernt.',
      reordered: 'Reihenfolge geändert.',
      paymentSaved: 'Zahlung erfasst.',
      paymentDeleted: 'Zahlung gelöscht.',
      pdf: 'PDF wird heruntergeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  } as const;
