/**
 * UI-Texte für Domäne `kiosk` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const kiosk = {
    title: 'Kiosk-Terminal',
    install: {
      title: 'Als App speichern',
      subtitle:
        'Speichern Sie den Kiosk auf dem Home-Bildschirm – dann starten Sie ihn wie eine App (ohne Browser-Leiste).',
      androidHint:
        'Tippen Sie auf „App installieren“, oder nutzen Sie das Menü Ihres Browsers („App installieren“ / „Zum Startbildschirm“).',
      installButton: 'App installieren',
      iosStep1: 'In Safari das Teilen-Symbol antippen (Quadrat mit Pfeil nach oben).',
      iosStep2: '„Zum Home-Bildschirm“ wählen.',
      iosStep3: 'Mit „Hinzufügen“ bestätigen.',
      later: 'Später',
      never: 'Nicht mehr anzeigen',
    },
    setup: {
      title: 'Kiosk einrichten',
      subtitle: 'Konfiguration für dieses Gerät',
      project: 'Projekt zuweisen',
      projectPlaceholder: 'Projekt auswählen …',
      autoLogout: 'Auto-Logout (Sekunden)',
      cameraEnabled: 'Kamera erlauben',
      fullscreen: 'Vollbild erzwingen',
      adminPin: 'Admin-PIN (4–6 Ziffern)',
      adminPinHint: 'Zum Verlassen des Kiosk-Modus',
      save: 'Kiosk starten',
      saving: 'Wird gespeichert …',
      noProjects: 'Keine aktiven Projekte gefunden.',
      loginRequired: 'Bitte als Admin anmelden, um den Kiosk einzurichten.',
    },
    terminal: {
      welcome: 'Willkommen',
      pinTitle: 'PIN eingeben',
      pinHint: 'Monteur-PIN',
      pinError: 'Ungültige PIN. Bitte erneut versuchen.',
      pinChecking: 'Wird geprüft …',
      clear: 'Löschen',
      confirm: 'OK',
      notClockedIn: 'Nicht eingestempelt',
      clockedInSince: 'Eingestempelt seit',
      startWork: 'ARBEIT STARTEN',
      stopWork: 'ARBEIT BEENDEN',
      takePhoto: 'Foto aufnehmen',
      photoUploading: 'Wird hochgeladen …',
      gpsActive: 'GPS aktiv',
      gpsInactive: 'GPS nicht verfügbar',
      gpsAcquiring: 'GPS wird ermittelt …',
      autoLogout: (seconds: number): string =>
        `Automatisch zurück in ${seconds} Sek.`,
      back: 'Zurück',
      setupButton: 'Setup',
      adminPinPrompt: 'Admin-PIN eingeben',
      confirmClockIn: (name: string, time: string): string =>
        `${name} – Eingestempelt um ${time}`,
      confirmClockOut: (name: string, time: string, duration: string): string =>
        `${name} – Ausgestempelt um ${time} (${duration})`,
      goodDay: 'Guten Arbeitstag!',
      goodBye: 'Bis morgen!',
      upcomingProjects: 'Zukünftige Projekte',
      liveOverview: 'Heute eingestempelt',
      notOnSite: 'Noch nicht da',
      since: 'seit',
      processing: 'Wird verarbeitet …',
      error: 'Aktion fehlgeschlagen. Bitte erneut versuchen.',
      savedPending: 'Gespeichert – wird synchronisiert',
    },
    nav: 'Kiosk-Modus',
    pl: {
      modeLabel: 'Kunden-PL',
      pinTitle: 'Kunden-PL PIN eingeben',
      pinHint: 'Kunden-PL PIN',
      pinError: 'Ungültige PIN oder kein Kunden-PL. Bitte erneut versuchen.',
      listTitle: 'Eingereichte Stundenzettel',
      listEmpty: 'Keine eingereichten Stundenzettel für dieses Projekt.',
      worker: 'Monteur',
      week: 'KW',
      netHours: 'Netto',
      status: 'Status',
      detail: 'Detail',
      back: 'Zurück',
      backToList: 'Zur Liste',
      signAndApprove: 'Unterschreiben & abzeichnen',
      signing: 'Wird abgezeichnet …',
      signerName: 'Name des Unterzeichners',
      signatureHint: 'Bitte mit Finger oder Stift unterschreiben.',
      signatureEmpty: 'Bitte zuerst unterschreiben.',
      clearSignature: 'Löschen',
      successTitle: 'Erfolgreich abgezeichnet',
      successMessage: 'Der Stundenzettel wurde unterschrieben und freigegeben.',
      errorGeneric: 'Aktion fehlgeschlagen. Bitte erneut versuchen.',
      totals: 'Wochensumme',
      autoLogout: (seconds: number): string =>
        `Automatisch zurück in ${seconds} Sek.`,
      alreadySigned: 'Bereits abgezeichnet',
      tabs: {
        items: 'Arbeitsitems',
        timesheets: 'Stundenzettel',
      },
      items: {
        searchAction: 'Suchen',
        loadError:
          'Arbeitsitems konnten nicht geladen werden. Keine Projektzuordnung oder Netzwerkfehler.',
        detailError: 'Item konnte nicht geladen werden.',
        closeDetail: 'Zurück zum Board',
      },
    },
  } as const;
