/**
 * UI-Texte für Domäne `projects` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const projects = {
    title: 'Projekte',
    subtitle: 'Projekte planen und steuern',
    newProject: 'Neues Projekt',
    searchPlaceholder: 'Suche nach Projektnr., Titel oder Kunde …',
    empty: 'Noch keine Projekte vorhanden.',
    emptyAction: 'Erstes Projekt anlegen →',
    noResults: 'Keine Projekte gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Projekt anlegen',
    createSubtitle: 'Stammdaten erfassen – Standorte und Zuordnungen folgen im Detail.',
    deleteTitle: 'Projekt löschen?',
    deleteConfirm:
      'Das Projekt wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      projectNumber: 'Projektnr.',
      title: 'Titel',
      customer: 'Kunde',
      serviceType: 'Leistungsart',
      priority: 'Priorität',
      status: 'Status',
      plannedStart: 'Start (geplant)',
    },
    tabs: {
      stammdaten: 'Stammdaten',
      standorte: 'Standorte',
      monteure: 'Monteure',
      equipment: 'Equipment',
      arbeitsitems: 'Arbeitsitems',
      dokumente: 'Dokumente',
      projectPlans: 'Projektpläne',
      sitePhotos: 'Baustellenfotos',
      emailVerteiler: 'E-Mail-Verteiler',
      notizenVerlauf: 'Notizen & Verlauf',
      printTab: 'Aktuelle Ansicht drucken',
      printAll: 'Gesamtübersicht drucken',
    },
    plans: {
      title: 'Projektpläne',
      hint: 'Nur die aktuelle Version ist für Monteure am Kiosk sichtbar. Alte Versionen bleiben zur Kontrolle hier.',
      empty: 'Noch keine Pläne hinterlegt.',
      upload: 'Plan hochladen',
      newVersion: 'Neue Version',
      open: 'Öffnen',
      history: 'Historie',
      historyTitle: 'Versionshistorie',
      badgeCurrent: 'Aktuell',
      badgeRev: 'Rev. {n}',
      reload: 'Aktualisieren',
      toastUploaded: 'Plan hochgeladen.',
      toastReplaced: 'Neue Plan-Version gespeichert.',
    },
    status: {
      DRAFT: 'Entwurf',
      PLANNED: 'Geplant',
      ACTIVE: 'Aktiv',
      PAUSED: 'Pausiert',
      COMPLETED: 'Abgeschlossen',
      CANCELED: 'Abgebrochen',
    },
    priority: {
      LOW: 'Niedrig',
      MEDIUM: 'Mittel',
      HIGH: 'Hoch',
      URGENT: 'Dringend',
    },
    serviceType: {
      VIDEO: 'Videotechnik',
      ELECTRICAL: 'Elektrotechnik',
      SERVICE: 'Service',
      OTHER: 'Sonstiges',
    },
    billingMode: {
      HOURLY_PACKAGE: 'Stunden-Paket',
      UNIT_BASED: 'Nach Einheiten',
      MIXED: 'Gemischt',
    },
    fields: {
      projectNumber: 'Projektnummer',
      title: 'Titel',
      description: 'Beschreibung',
      customer: 'Kunde',
      branch: 'Niederlassung',
      contact: 'Ansprechpartner',
      serviceType: 'Leistungsart',
      priority: 'Priorität',
      status: 'Status',
      projectManager: 'Projektleiter',
      plannedStart: 'Geplanter Start',
      plannedEnd: 'Geplantes Ende',
      actualStart: 'Tatsächlicher Start',
      actualEnd: 'Tatsächliches Ende',
      billingMode: 'Abrechnungsart',
      weeklyPackageHours: 'Paket-Stunden / Woche',
      weeklyPackagePrice: 'Paket-Preis / Woche (€)',
      overtimeRate: 'Überstundensatz (€/h)',
      pauseRule: 'Pausenregel',
      notes: 'Notizen',
      siteName: 'Standort-Name',
      siteAddress: 'Standort-Adresse',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      accessInfo: 'Zugangsinfos',
      workingHours: 'Arbeitszeiten',
      accommodation: 'Unterkunft',
      accommodationAddress: 'Unterkunft-Adresse',
      accommodationNotes: 'Unterkunft-Hinweise',
      equipmentName: 'Bezeichnung',
      equipmentDescription: 'Beschreibung',
      quantity: 'Menge',
      serialNumber: 'Seriennummer',
      issuedAt: 'Ausgegeben am',
      issuedTo: 'Ausgegeben an',
      returnedAt: 'Zurückgegeben am',
      condition: 'Zustand bei Ausgabe',
      returnCondition: 'Zustand bei Rückgabe',
      roleName: 'Funktion',
      worker: 'Monteur',
      startDate: 'Von',
      endDate: 'Bis',
      isLead: 'Teamleitung',
      recipientEmail: 'E-Mail',
      recipientName: 'Name',
      recipientType: 'Typ',
      noteBody: 'Notiz',
      sortOrder: 'Reihenfolge',
    },
    sections: {
      base: 'Basisdaten',
      classification: 'Einordnung',
      planning: 'Planung & Termine',
      billing: 'Abrechnung',
      site: 'Hauptstandort',
      accommodation: 'Unterkunft',
    },
    actions: {
      newProject: 'Neues Projekt',
      addSite: 'Standort hinzufügen',
      addEquipment: 'Equipment hinzufügen',
      addRecipient: 'Empfänger hinzufügen',
      addNote: 'Notiz hinzufügen',
      addAssignment: 'Monteur zuordnen',
      returnEquipment: 'Zurücknehmen',
      changeStatus: 'Status ändern',
      openRoute: 'Route öffnen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      print: 'Drucken',
      printList: 'Liste drucken',
      printing: 'Wird vorbereitet …',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      details: 'Details',
      close: 'Schließen',
    },
    printListTitle: 'Projektliste',
    printListSubtitleCurrent: 'Aktuelle Projekte (geplant, aktiv, pausiert)',
    printListSubtitleFiltered: 'Gefilterte Projektliste',
    empties: {
      sites: 'Noch keine Standorte erfasst.',
      equipment: 'Noch kein Equipment zugeordnet.',
      assignments: 'Noch keine Monteure zugeordnet.',
      recipients: 'Noch keine E-Mail-Empfänger.',
      notes: 'Noch keine Notizen.',
      documents: 'Noch keine Dokumente.',
      statusHistory: 'Noch keine Statusänderungen.',
      addNow: 'Jetzt anlegen →',
      noFreeWorkers: 'Keine Monteure vorhanden.',
    },
    hints: {
      workerAvailability:
        'Freie Monteure zuerst. Belegte Einträge sind gesperrt, bis die andere Zuweisung endet.',
    },
    statusHistory: 'Status-Verlauf',
    activeAssignments: 'Aktive Zuordnungen',
    issuedEquipment: 'Ausgegeben (offen)',
    returnedEquipment: 'Zurückgegeben',
    coordinates: 'Koordinaten',
    calendar: {
      title: 'Projektkalender',
      today: 'Heute',
      month: 'Monat',
      week: 'Woche',
      day: 'Tag',
      noEvents: 'Keine Termine in diesem Zeitraum.',
      plannedStart: 'Geplanter Start',
      plannedEnd: 'Geplantes Ende',
      actualStart: 'Tatsächlicher Start',
      actualEnd: 'Tatsächliches Ende',
      duration: 'Laufzeit',
    },
    changeStatus: {
      title: 'Status ändern',
      newStatus: 'Neuer Status',
      comment: 'Kommentar (optional)',
      confirm: 'Status setzen',
    },
    /** Arbeitsitems (item-basierte Projekte, SPEZ-arbeitsitems.md). */
    workItems: {
      badge: 'Items',
      itemBased: {
        label: 'Item-basiertes Projekt',
        hint: 'Arbeit wird in einzelne Items (Positionen) mit Material, Fotos und Kontrolle aufgeteilt.',
        disabledHint:
          'Aktivieren, um Blöcke, Import, Item-Board und Kunden-PL zu nutzen.',
        enabling: 'Wird umgestellt …',
      },
      sections: {
        blocks: 'Blöcke & PDFs',
        import: 'Import',
        items: 'Items',
        templates: 'Templates',
        customerPls: 'Kunden-PL',
      },
      blocks: {
        title: 'Blöcke & Block-PDFs',
        subtitle:
          'Ein Block gruppiert Items – im Regelfall ein PDF je Block. Unbekannte Blöcke legt der Import automatisch an.',
        blockKey: 'Block-Kennung',
        blockKeyHint: 'Muss der Spalte "block" der Importdatei entsprechen.',
        name: 'Bezeichnung',
        itemCount: 'Items',
        pdf: 'Block-PDF',
        pdfMissing: 'Kein PDF',
        pdfPresent: 'PDF hinterlegt',
        add: 'Block anlegen',
        edit: 'Block bearbeiten',
        uploadPdf: 'PDF hochladen',
        replacePdf: 'PDF ersetzen',
        openPdf: 'PDF öffnen',
        unlinkPdf: 'PDF-Verknüpfung lösen',
        deleteTitle: 'Block löschen?',
        deleteConfirm:
          'Der Block wird entfernt. Zugeordnete Items bleiben erhalten und verlieren nur den Block-Bezug.',
        empty: 'Noch keine Blöcke angelegt.',
      },
      import: {
        title: 'Excel-/CSV-Import (Fallback)',
        subtitle:
          'Blätter "Items" und "Material" aus .xlsx/.xlsm oder passende CSV-Dateien. Bestehende Items werden je Kennung aktualisiert, Material eines enthaltenen Items ersetzt.',
        fallbackHint:
          'Primärer Importweg ist der PDF-Import oben. Excel/CSV nur für Sonderfälle und Massenkorrektur.',
        templateHint:
          'Vorlage: arbeitsitems-import-beispiel.xlsx (im Repo, auch unter docs/import-vorlagen/).',
        chooseFiles: 'Dateien wählen',
        selectedFiles: 'Ausgewählt',
        noFiles: 'Noch keine Datei gewählt.',
        preview: 'Vorschau prüfen',
        previewing: 'Wird geprüft …',
        run: 'Import ausführen',
        running: 'Wird importiert …',
        clear: 'Auswahl leeren',
        resultPreview: 'Vorschau (nichts gespeichert)',
        resultDone: 'Import abgeschlossen',
        itemsCreated: 'Items neu',
        itemsUpdated: 'Items aktualisiert',
        blocksCreated: 'Blöcke neu',
        materialLines: 'Materialzeilen',
        materialsReplaced: 'Items mit ersetztem Material',
        orphanRows: 'Materialzeilen ohne Item',
        sources: 'Dateien',
        warnings: 'Warnungen',
        noWarnings: 'Keine Warnungen.',
      },
      pdfImport: {
        title: 'PDF-Import (Primär)',
        subtitle:
          'Mehrseiten-PDF hochladen → 1 Seite = 1 Arbeitsauftrag. Kennungen und Titel vor dem Import anpassen.',
        hint: 'Regel: 1 PDF-Seite = 1 Auftrag. Bauteile bleiben im PDF – Kennungen vor Commit anpassen.',
        chooseFile: 'PDF wählen',
        noFile: 'Noch kein PDF gewählt.',
        blockKey: 'Block-Kennung',
        blockKeyPlaceholder: 'z. B. Block-1',
        blockName: 'Block-Name (optional)',
        blockNamePlaceholder: 'z. B. Block 1 EG',
        prefix: 'Kennung-Präfix',
        prefixPlaceholder: 'Seite-',
        startPage: 'Ab Seite',
        endPage: 'Bis Seite',
        preview: 'Vorschau laden',
        previewing: 'Wird geladen …',
        commit: 'Import ausführen',
        committing: 'Wird importiert …',
        clear: 'Zurücksetzen',
        resultPreview: 'Vorschau (noch nicht gespeichert)',
        resultDone: 'PDF-Import abgeschlossen',
        pageCount: 'Seiten im PDF',
        colPage: 'Seite',
        colKey: 'Kennung',
        colTitle: 'Titel',
        colWorkScope: 'Arbeitsinhalt (DE)',
        colWarnings: 'Hinweise',
        itemsCreated: 'Items neu',
        itemsUpdated: 'Items aktualisiert',
        warnings: 'Warnungen',
        noWarnings: 'Keine Warnungen.',
        toastPreviewDone: 'PDF-Vorschau geladen.',
        toastCommitDone: 'PDF-Import abgeschlossen – Items angelegt.',
        template: 'Kartentyp-Template',
        templateNone: 'Kein Template (Minimal-Modus)',
        templateHint:
          'Optional: Template wählen, dann nach der Vorschau „OCR vorausfüllen“ – nicht bei „Vorschau laden“.',
        flowHint:
          'Ablauf: 1) Vorschau laden (schnell) → 2) optional OCR → 3) Import ausführen.',
        ocrFill: 'OCR vorausfüllen',
        ocrButtonHint:
          'Liest jede PDF-Seite per OCR mit dem gewählten Template (in Chunks). Bei vielen Seiten Fortschritt sichtbar.',
        ocrLoading: 'OCR läuft …',
        ocrProgress: (done: number, total: number): string =>
          `OCR: Seite ${done} von ${total}`,
        ocrProgressFailed: (n: number): string =>
          n === 1 ? '1 Seite mit OCR-Fehler' : `${n} Seiten mit OCR-Fehler`,
        fileTooLarge: (mb: string): string =>
          `PDF zu groß (${mb} MB). Maximal 50 MB für den Block-Import.`,
        itemsReady: 'Aufträge in der Liste',
        toastOcrDone: 'OCR-Extraktion abgeschlossen – bitte Kennungen prüfen.',
        toastOcrPartial:
          'OCR teilweise abgeschlossen – Seiten mit Fehlern behalten Platzhalter.',
        toastAborted:
          'Vorgang abgebrochen (Zeitüberschreitung oder Abbruch). Bitte erneut versuchen oder kleinere Chunks.',
        colFloor: 'Geschoss',
        colRoom: 'Raum',
        colOcrWarnings: 'OCR-Hinweise',
      },
      templates: {
        title: 'Kartentyp-Templates',
        subtitle: 'Feldzuordnungen für automatische OCR-Extraktion beim PDF-Import',
        newTemplate: 'Neues Template',
        name: 'Name',
        namePlaceholder: 'z. B. TAS Arbeitskarte',
        customer: 'Kunde (optional)',
        customerNone: 'Keinem Kunden zugeordnet',
        fields: 'Feldzuordnungen',
        addField: 'Feld hinzufügen',
        target: 'Zielfeld',
        labelHints: 'Label-Hinweise',
        labelHintsPlaceholder: 'z. B. Positions-ID, Kennung',
        regex: 'Regex (optional)',
        regexPlaceholder: 'z. B. \\d{2}-[A-Z]-\\d{2}',
        captureLines: 'Zeilen',
        zone: 'Zone',
        zoneSet: 'Zone gesetzt',
        zoneClearField: 'Zone löschen',
        notes: 'Notizen',
        notesPlaceholder: 'Hinweise zum Template',
        save: 'Speichern',
        saving: 'Wird gespeichert …',
        cancel: 'Abbrechen',
        edit: 'Bearbeiten',
        delete: 'Löschen',
        deleteConfirm: 'Template wirklich löschen?',
        empty: 'Noch keine Templates vorhanden.',
        calibrate: 'Kalibrieren',
        calibrateTitle: 'Template kalibrieren',
        calibrateSubtitle:
          'Beispielseite hochladen → OCR → Feldvorschläge + Zonen auf der Seite markieren',
        calibrateChooseFile: 'Beispielseite wählen',
        calibrateRun: 'OCR starten',
        calibrateRunning: 'OCR läuft …',
        calibrateOcrText: 'Erkannter Text',
        calibrateSuggestions: 'Vorgeschlagene Feldzuordnungen',
        calibrateApply: 'Vorschläge & Zonen übernehmen',
        calibrateNoSuggestions: 'Keine automatischen Vorschläge erkannt.',
        zoneEditorTitle: 'Zonen auf der Beispielseite',
        zoneDrawHint:
          'Feld wählen, dann Rechteck auf der Seite ziehen. Zonen werden beim Import bevorzugt.',
        zoneActiveField: 'Zone zeichnen für',
        zoneRemove: 'Zone entfernen',
        zonesList: 'Gesetzte Zonen',
        toastCreated: 'Template angelegt.',
        toastUpdated: 'Template gespeichert.',
        toastDeleted: 'Template gelöscht.',
      },
      list: {
        title: 'Items',
        search: 'Suche nach Kennung, Titel oder Raum …',
        filterStatus: 'Status',
        filterBlock: 'Block',
        all: 'Alle',
        noBlock: 'Ohne Block',
        itemKey: 'Kennung',
        itemTitle: 'Titel',
        location: 'Ort',
        block: 'Block',
        status: 'Status',
        assigned: 'Monteur',
        materials: 'Material',
        reload: 'Aktualisieren',
        empty: 'Keine Items gefunden.',
        emptyUnfiltered:
          'Noch keine Items – Datei im Bereich "Import" hochladen.',
        countLabel: 'Items',
        truncated:
          'Es werden die ersten {take} von {total} Items angezeigt – bitte filtern.',
      },
      detail: {
        title: 'Item-Detail',
        metadata: 'Metadaten',
        floor: 'Geschoss',
        area: 'Bereich',
        room: 'Raum',
        type: 'Typ',
        rc: 'RC',
        detailField: 'Detail',
        planPage: 'Planseite',
        sheet: 'Blatt',
        pdfFile: 'PDF-Datei',
        pdfPage: 'PDF-Seite',
        workScopeDe: 'Arbeitsumfang (DE)',
        workScopeSk: 'Arbeitsumfang (SK)',
        materials: 'Material',
        qty: 'Menge',
        materialDe: 'Material (DE)',
        materialSk: 'Material (SK)',
        noMaterials: 'Kein Material erfasst.',
        blockPdf: 'Block-PDF',
        openBlockPdf: 'Block-PDF öffnen',
        noBlockPdf: 'Für den Block ist kein PDF hinterlegt.',
        assignments: 'Aktive Zuordnungen',
        noAssignments: 'Keine aktive Zuordnung.',
        since: 'seit',
        reports: 'Rückmeldungen',
        noReports: 'Noch keine Rückmeldungen.',
        photos: 'Fotos',
        reviews: 'Kontrollen',
        noReviews: 'Noch keine Kontrolle.',
        time: 'Item-Zeit',
        totalTime: 'Gesamt',
        perWorker: 'Je Monteur',
        openSessions: 'laufend',
        noTime: 'Noch keine Zeiten erfasst.',
        readOnlyHint:
          'Fertigmeldungen und Kontrollen laufen über Monteur-App und Kunden-PL – hier nur zur Ansicht.',
      },
      customerPls: {
        title: 'Kunden-Projektleiter',
        subtitle:
          'Benutzer mit der Rolle CUSTOMER_PL dürfen Items dieses Projekts kontrollieren und fertigsetzen.',
        user: 'Benutzer',
        email: 'E-Mail',
        state: 'Status',
        active: 'Aktiv',
        inactive: 'Inaktiv',
        add: 'Kunden-PL zuordnen',
        choose: 'Benutzer wählen',
        empty: 'Noch kein Kunden-PL zugeordnet.',
        noCandidates:
          'Keine Benutzer mit der Rolle CUSTOMER_PL vorhanden – zuerst in der Benutzerverwaltung anlegen.',
        removeTitle: 'Zuordnung aufheben?',
        removeConfirm:
          'Der Kunden-PL verliert den Zugriff auf dieses Projekt. Die Historie bleibt erhalten.',
        setPin: 'PIN setzen',
        pinDialogTitle: 'Kiosk-PIN für Kunden-PL setzen',
        pinDialogHint:
          'PIN für die Anmeldung am Kiosk-Terminal (Länge laut Einstellungen → Allgemein).',
        pinLabel: 'PIN ({n} Ziffern)',
        pinPlaceholder: '000000',
        pinValidation: 'PIN muss genau {n} Ziffern sein.',
        pinSet: 'PIN gesetzt',
        pinSetError: 'PIN konnte nicht gesetzt werden.',
        setNotificationEmail: 'Zustell-E-Mail setzen',
        emailDialogTitle: 'Zustell-E-Mail für Stundenzettel',
        emailDialogHint:
          'An diese Adresse wird das PDF nach dem Abzeichnen gesendet. Leer = Login-E-Mail des Kunden-PL.',
        emailLabel: 'Zustell-E-Mail',
        emailPlaceholder: 'pl@kunde.de',
        emailValidation: 'Bitte eine gültige E-Mail-Adresse eingeben.',
        emailSet: 'Zustell-E-Mail gespeichert.',
        emailCleared: 'Zustell-E-Mail zurückgesetzt (Fallback Login-E-Mail).',
        emailFallbackHint: 'Fallback: Login-E-Mail',
      },
      toast: {
        itemBasedOn: 'Projekt auf Item-Modus umgestellt.',
        itemBasedOff: 'Item-Modus deaktiviert.',
        blockCreated: 'Block angelegt.',
        blockUpdated: 'Block gespeichert.',
        blockDeleted: 'Block gelöscht.',
        pdfLinked: 'Block-PDF hinterlegt.',
        pdfUnlinked: 'PDF-Verknüpfung gelöst.',
        previewDone: 'Vorschau erstellt – es wurde nichts gespeichert.',
        importDone: 'Import abgeschlossen.',
        pdfPreviewDone: 'PDF-Vorschau geladen.',
        pdfImportDone: 'PDF-Import abgeschlossen – Items angelegt.',
        customerPlAdded: 'Kunden-PL zugeordnet.',
        customerPlRemoved: 'Zuordnung aufgehoben.',
      },
    },
    toast: {
      created: 'Projekt angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Projekt gelöscht.',
      statusChanged: 'Status geändert.',
      siteAdded: 'Standort hinzugefügt.',
      siteDeleted: 'Standort entfernt.',
      equipmentAdded: 'Equipment hinzugefügt.',
      equipmentReturned: 'Equipment zurückgenommen.',
      assignmentAdded: 'Monteur zugeordnet.',
      assignmentEnded: 'Zuordnung beendet.',
      recipientAdded: 'Empfänger hinzugefügt.',
      noteAdded: 'Notiz gespeichert.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  } as const;
