/**
 * UI-Texte für Domäne `settings` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const settings = {
    title: 'Einstellungen',
    placeholder: 'Einstellungen folgen in einem späteren Auftrag.',
    email: {
      title: 'E-Mail-Konfiguration',
      subtitle: 'SMTP-Einstellungen für den E-Mail-Versand',
      host: 'SMTP-Host',
      port: 'SMTP-Port',
      user: 'SMTP-Benutzer',
      pass: 'SMTP-Passwort',
      fromName: 'Absender-Name',
      fromEmail: 'Absender-E-Mail',
      secure: 'TLS/SSL verwenden',
      testEmail: 'Test-E-Mail senden',
      testEmailTo: 'Empfänger für Test',
      testEmailPlaceholder: 'test@example.com',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      sending: 'Wird gesendet …',
      toast: {
        saved: 'SMTP-Konfiguration gespeichert.',
        testSuccess: 'Test-E-Mail erfolgreich gesendet.',
        testFailed: 'Test-E-Mail fehlgeschlagen.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    storage: {
      title: 'Speicher & Cloud',
      subtitle: 'Google Drive Synchronisation konfigurieren',
      enabled: 'Google Drive aktivieren',
      folderId: 'Google Drive Ordner-ID',
      folderIdPlaceholder: 'z.B. 1aBcDeFgHiJkLmNoPqRsTuVwXyZ',
      serviceAccountJson: 'Service Account JSON Key',
      serviceAccountPlaceholder: 'JSON-Inhalt hier einfügen …',
      testConnection: 'Verbindung testen',
      testing: 'Wird getestet …',
      info: 'Dokumente werden parallel in MinIO (lokal) und Google Drive gespeichert.',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      toast: {
        saved: 'Speicher-Konfiguration gespeichert.',
        testSuccess: 'Verbindung erfolgreich.',
        testFailed: 'Verbindungstest fehlgeschlagen.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    nav: {
      email: 'E-Mail-Konfiguration',
      storage: 'Speicher & Cloud',
      breakRules: 'Pausenregeln',
      system: 'Server-Status',
      backup: 'Backup & Restore',
    },
    backup: {
      title: 'Backup & Restore',
      subtitle: 'Datenbank-Backups planen, manuell erstellen und Module wiederherstellen',
      scheduleTitle: 'Zeitplan',
      enabled: 'Automatisches Backup aktivieren',
      hour: 'Stunde (0–23)',
      minute: 'Minute (0–59)',
      retentionDays: 'Aufbewahrung (Tage)',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      lastUpdated: 'Zuletzt geändert',
      startBackup: 'Jetzt sichern',
      running: 'Backup läuft …',
      jobsTitle: 'Vorhandene Backups',
      restoresTitle: 'Restore-Protokoll',
      noJobs: 'Noch keine Backups vorhanden.',
      restore: 'Wiederherstellen',
      restoring: 'Wird wiederhergestellt …',
      restoreTitle: 'Backup wiederherstellen',
      restoreConfirm:
        'Gewählte Module werden aus dem Backup in die aktuelle Datenbank zurückgeschrieben (Upsert). Bitte Module sorgfältig wählen.',
      deleteTitle: 'Backup löschen?',
      deleteConfirm: 'Backup-Dateien und Job-Eintrag werden unwiderruflich gelöscht.',
      triggerCron: 'Zeitplan',
      triggerManual: 'Manuell',
      columns: {
        created: 'Erstellt',
        status: 'Status',
        trigger: 'Auslöser',
        size: 'Größe',
        actions: 'Aktionen',
        modules: 'Module',
      },
      toast: {
        saved: 'Backup-Konfiguration gespeichert.',
        backupOk: 'Backup erfolgreich erstellt.',
        backupFailed: 'Backup fehlgeschlagen.',
        restoreOk: 'Wiederherstellung erfolgreich.',
        restorePartial: 'Wiederherstellung teilweise erfolgreich.',
        restoreFailed: 'Wiederherstellung fehlgeschlagen.',
        deleted: 'Backup gelöscht.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    system: {
      title: 'Server-Status',
      subtitle: 'Systemüberwachung und Ressourcenauslastung',
      refresh: 'Aktualisieren',
      lastUpdated: 'Aktualisiert',
      autoRefresh: 'Daten werden alle 30 Sekunden aktualisiert.',
      loading: 'Lade Systemdaten …',
      error: 'Systemdaten konnten nicht geladen werden.',
      retry: 'Erneut versuchen',
      backToSettings: 'Einstellungen',
      summary: {
        customers: 'Kunden',
        projects: 'Projekte',
        workers: 'Monteure',
        openTasks: 'Offene Aufgaben',
        uptime: 'Uptime',
      },
      cpu: {
        title: 'CPU',
        model: 'Modell',
        cores: 'Kerne',
        usage: 'Auslastung',
        loadAvg: 'Load Average',
      },
      memory: {
        title: 'Arbeitsspeicher',
        total: 'Gesamt',
        used: 'Belegt',
        free: 'Frei',
      },
      disk: {
        title: 'Festplatte',
        total: 'Gesamt',
        used: 'Belegt',
        available: 'Verfügbar',
      },
      services: {
        title: 'Service Health Checks',
        online: 'Online',
        offline: 'Offline',
        responseTime: 'ms',
      },
      updates: {
        title: 'OS Updates',
        containerUpdates: 'Container-Updates',
        hostUpdates: 'Host-Updates',
        noUpdates: 'Keine Updates verfügbar',
        hostNotAvailable: 'Host-Updates nicht verfügbar (kein Host-Zugriff)',
        packagesAvailable: (n: number): string =>
          n === 1 ? '1 Paket verfügbar' : `${n} Pakete verfügbar`,
        installButton: 'Updates installieren',
        installing: 'Wird installiert …',
        confirmTitle: 'Updates installieren?',
        confirmText:
          'Alle verfügbaren Container-Pakete werden aktualisiert. Fortfahren?',
        confirmButton: 'Installieren',
        cancelButton: 'Abbrechen',
        success: 'Updates erfolgreich installiert.',
        failed: 'Update-Installation fehlgeschlagen.',
      },
      database: {
        title: 'PostgreSQL Datenbank',
        size: 'Datenbankgröße',
        connections: 'Verbindungen',
        activeOf: 'aktiv von',
        cacheHitRatio: 'Cache Hit Ratio',
        version: 'Version',
        topTables: 'Top 15 Tabellen',
        tableName: 'Tabelle',
        tableSize: 'Größe',
        tableRows: 'Zeilen',
      },
      storage: {
        title: 'MinIO Storage',
        totalSize: 'Gesamtgröße',
        totalObjects: 'Objekte gesamt',
        bucketName: 'Bucket',
        bucketObjects: 'Objekte',
        bucketSize: 'Größe',
        unavailable: 'MinIO nicht erreichbar',
      },
      network: {
        title: 'Netzwerk',
        interface: 'Schnittstelle',
        received: 'Empfangen',
        sent: 'Gesendet',
      },
      serverDetails: {
        title: 'Server-Details',
        hostname: 'Hostname',
        platform: 'Plattform',
        arch: 'Architektur',
        nodeVersion: 'Node.js',
      },
      processes: {
        title: 'Top 10 Prozesse',
        pid: 'PID',
        user: 'Benutzer',
        cpu: 'CPU %',
        mem: 'RAM %',
        command: 'Befehl',
      },
      appStats: {
        title: 'Anwendungsstatistiken',
        communication: 'Kommunikation (7 Tage)',
        documents: 'Dokumente gesamt',
        equipmentAssigned: 'Geräte zugewiesen',
        equipmentAvailable: 'Geräte verfügbar',
      },
      osUsers: {
        title: 'OS-Benutzer',
      },
    },
  } as const;
