/** UI-Texte: `subcontractors`. */
export const subcontractors = {
    title: 'Subunternehmen',
    subtitle: 'Subunternehmen verwalten',
    newSubcontractor: 'Neues Subunternehmen',
    searchPlaceholder: 'Suche nach Name, Kontakt oder Ort …',
    empty: 'Noch keine Subunternehmen vorhanden.',
    emptyAction: 'Erstes Subunternehmen anlegen →',
    noResults: 'Keine Subunternehmen gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Subunternehmen anlegen',
    createSubtitle: 'Firmendaten erfassen.',
    deleteTitle: 'Subunternehmen löschen?',
    deleteConfirm:
      'Das Subunternehmen wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      name: 'Name',
      contactPerson: 'Kontaktperson',
      city: 'Ort',
      workers: 'Monteure',
    },
    sections: {
      company: 'Firmendaten',
      contact: 'Kontakt',
      contacts: 'Ansprechpartner',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      tax: 'Steuer',
      bank: 'Bankverbindung',
      notes: 'Notizen',
      workers: 'Zugehörige Monteure',
    },
    fields: {
      name: 'Firmenname',
      contactPerson: 'Kontaktperson (Legacy)',
      email: 'E-Mail',
      phone: 'Telefon',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      taxNumber: 'Steuernummer',
      vatId: 'USt-ID',
      iban: 'IBAN',
      bic: 'BIC',
      bankName: 'Bankname',
      notes: 'Notizen',
      active: 'Aktiv',
      contactTitle: 'Anrede',
      contactFirstName: 'Vorname',
      contactLastName: 'Nachname',
      contactRole: 'Funktion',
      contactEmail: 'E-Mail',
      contactPhoneMobile: 'Mobil',
      contactPhoneLandline: 'Festnetz',
      contactNotes: 'Notizen',
      contactIsPrimary: 'Hauptkontakt',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      print: 'Drucken',
      addContact: 'Ansprechpartner hinzufügen',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      openRoute: 'Route öffnen',
    },
    tabs: {
      printTab: 'Aktuelle Ansicht drucken',
      printAll: 'Gesamtübersicht drucken',
    },
    empties: {
      workers: 'Noch keine Monteure zugeordnet.',
      contacts: 'Noch keine Ansprechpartner.',
      addNow: 'Jetzt anlegen →',
    },
    toast: {
      created: 'Subunternehmen angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Subunternehmen gelöscht.',
      contactCreated: 'Ansprechpartner angelegt.',
      contactUpdated: 'Ansprechpartner gespeichert.',
      contactDeleted: 'Ansprechpartner gelöscht.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  } as const;
