/**
 * UI-Texte für Domäne `timeClock` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const timeClock = {
  title: 'Stempeluhr',
  subtitle: 'Wer ist gerade eingestempelt?',
  refresh: 'Aktualisieren',
  liveCount: (n: number): string =>
    n === 1 ? '1 Monteur eingestempelt' : `${n} Monteure eingestempelt`,
  empty: 'Aktuell ist niemand eingestempelt.',
  tabs: {
    live: 'Live',
    period: 'Zeitraum',
    gps: 'GPS-Daten',
  },
  period: {
    title: 'Zeitraum',
    subtitle: 'Stempelungen nach Tag oder Kalenderwoche',
    empty: 'Keine Einträge für die gewählten Filter.',
    modeDay: 'Tag',
    modeWeek: 'KW',
    modeLabel: 'Zeitraum',
    filters: {
      date: 'Datum',
      weekNumber: 'KW',
      weekYear: 'Jahr',
      project: 'Projekt',
      worker: 'Monteur',
      team: 'Team',
      allProjects: 'Alle Projekte',
      allWorkers: 'Alle Monteure',
      allTeams: 'Alle Teams',
    },
    columns: {
      worker: 'Monteur',
      status: 'Status',
      firstIn: 'Erster In',
      lastOut: 'Letzter Out',
      gross: 'Brutto',
      breakBooked: 'Pause gebucht',
      breakRule: 'Pause Regel',
      net: 'Netto',
      warnings: 'Warnung',
      projects: 'Projekte',
    },
    status: {
      CLOCKED_IN: 'Eingestempelt',
      ON_BREAK: 'In Pause',
      CLOCKED_OUT: 'Ausgestempelt',
      NO_ENTRIES: 'Kein Stempel',
    },
    warnings: {
      PAUSE_BELOW_RULE: 'Pause unter Regel',
      BREAK_RULE_FALLBACK: 'Regel-Fallback',
      MISSING_CLOCK_OUT: 'Fehlendes Ausstempeln',
      OVER_10H: 'Über 10 Stunden',
    },
    breakFallbackHint:
      'Regel = Vorgabe; gestempelte Pause = Ist. Ohne Pause-Events gilt die Regel als Fallback.',
    timeline: {
      title: 'Tagesverlauf',
      locked:
        'Tag ist in freigegebenem/gesperrtem Stundenzettel – Korrektur gesperrt. Zuerst Stundenzettel zurücksetzen.',
      empty: 'Keine Stempelungen an diesem Tag.',
      selectDay: 'Tag wählen',
      entryType: 'Ereignis',
      time: 'Zeit',
      comment: 'Kommentar',
      project: 'Projekt',
      save: 'Speichern',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      addManual: 'Ereignis hinzufügen',
      deleteConfirmTitle: 'Eintrag löschen?',
      deleteConfirmHint: 'Kommentar zur Löschung ist Pflicht.',
      deleteConfirm: 'Endgültig löschen',
      commentRequired: 'Kommentar ist Pflicht.',
      manualTitle: 'Manuelles Ereignis',
      manualType: 'Typ',
      manualTime: 'Zeitpunkt',
      manualComment: 'Kommentar',
      manualProject: 'Projekt',
      manualSave: 'Anlegen',
      entryTypes: {
        CLOCK_IN: 'Einstempeln',
        CLOCK_OUT: 'Ausstempeln',
        BREAK_START: 'Pause starten',
        BREAK_END: 'Pause beenden',
        MANUAL_ADJUSTMENT: 'Korrektur',
      },
      segments: 'Tätigkeiten',
      toastSaved: 'Gespeichert.',
      toastDeleted: 'Gelöscht.',
      toastCreated: 'Ereignis angelegt.',
      toastError: 'Aktion fehlgeschlagen.',
    },
  },
  gps: {
    title: 'GPS-Daten',
    subtitle: 'Standorte bei Login, Stempel, Foto, Aktionen und im Intervall',
    empty: 'Keine GPS-Ereignisse im gewählten Zeitraum.',
    selectWorker: 'Monteur filtern',
    allWorkers: 'Alle Monteure',
    selectProject: 'Projekt filtern',
    allProjects: 'Alle Projekte',
    dateFrom: 'Von',
    dateTo: 'Bis',
    mapTitle: 'Bewegungsspur',
    mapHint:
      'Grün = Start, Blau = Zwischenpunkte, Rot = Ende – verbunden in zeitlicher Reihenfolge.',
    mapNeedWorker: 'Für die Karte bitte einen Monteur auswählen.',
    eventTypes: {
      CLOCK_IN: 'Einstempeln',
      CLOCK_OUT: 'Ausstempeln',
      MANUAL: 'Intervall',
      LOGIN: 'Login',
      LOGOUT: 'Logout',
      PHOTO: 'Foto',
      ACTION: 'Aktion',
    },
    columns: {
      time: 'Zeit',
      worker: 'Monteur',
      project: 'Projekt',
      event: 'Ereignis',
      location: 'Standort',
      accuracy: 'Genauigkeit',
    },
    openMap: 'Karte öffnen',
    daysBack: 'Letzte Tage',
  },
  columns: {
    worker: 'Monteur',
    project: 'Projekt',
    customer: 'Kunde',
    since: 'Eingestempelt seit',
    duration: 'Dauer',
  },
  openWorkerApp: 'Monteur-App öffnen',
} as const;
