/**
 * UI-Texte für Domäne `timesheets` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const timesheets = {
    title: 'Stundenzettel',
    subtitle: 'Wochenstundenzettel prüfen, freigeben und exportieren',
    searchPlaceholder: 'Suche …',
    empty: 'Noch keine Stundenzettel vorhanden.',
    noResults: 'Keine Stundenzettel gefunden.',
    backToList: 'Zurück zur Übersicht',
    generate: 'Stundenzettel anlegen / öffnen',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      week: 'KW',
      worker: 'Monteur',
      project: 'Projekt',
      gross: 'Brutto',
      break: 'Pause',
      net: 'Netto',
      status: 'Status',
      actions: 'Aktionen',
    },
    filters: {
      all: 'Alle',
      worker: 'Monteur',
      project: 'Projekt',
      status: 'Status',
      week: 'KW',
      year: 'Jahr',
    },
    status: {
      DRAFT: 'Entwurf',
      WORKER_SIGNED: 'Monteur unterschrieben',
      CUSTOMER_SIGNED: 'Kunde unterschrieben',
      COMPLETED: 'Abgeschlossen',
      LOCKED: 'Gesperrt',
      SUBMITTED: 'Eingereicht',
      REVIEWED: 'Geprüft',
      APPROVED: 'Genehmigt',
      REJECTED: 'Zurückgewiesen',
      ARCHIVED: 'Archiviert',
    },
    tabs: {
      week: 'Wochenübersicht',
      signatures: 'Unterschriften & Status',
    },
    days: {
      MON: 'Montag',
      TUE: 'Dienstag',
      WED: 'Mittwoch',
      THU: 'Donnerstag',
      FRI: 'Freitag',
      SAT: 'Samstag',
      SUN: 'Sonntag',
    },
    week: {
      day: 'Tag',
      date: 'Datum',
      start: 'Beginn',
      end: 'Ende',
      gross: 'Brutto',
      break: 'Pause',
      net: 'Netto',
      comment: 'Kommentar',
      activities: 'Tätigkeiten',
      total: 'Summe',
      gps: 'GPS-Standort öffnen',
      noData: 'Für diesen Stundenzettel liegen keine Tageseinträge vor.',
      addDay: 'Tag erfassen',
      regenerate: 'Aus Stempelungen neu laden',
    },
    generateDialog: {
      title: 'Stundenzettel anlegen',
      description:
        'Legt die Kalenderwoche an (Mo–So). Vorhandene Stempelungen werden übernommen; fehlende Tage können Sie manuell bearbeiten – auch ohne Handy des Monteurs. Existiert der Zettel schon als Entwurf, wird er aktualisiert und geöffnet.',
      worker: 'Monteur',
      project: 'Projekt',
      year: 'Jahr',
      week: 'Kalenderwoche von',
      weekTo: 'bis KW (optional)',
      weekToHint: 'Leer = nur eine Woche. Sonst alle KW von–bis inkl.',
      selectWorker: 'Monteur wählen',
      selectProject: 'Projekt wählen',
      confirm: 'Anlegen / öffnen',
      generating: 'Wird angelegt …',
      multiOk: '{count} Stundenzettel angelegt',
    },
    editDay: {
      title: 'Tageszeiten bearbeiten',
      start: 'Arbeitsbeginn',
      end: 'Arbeitsende',
      break: 'Pause (Minuten)',
      comment: 'Kommentar',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
    },
    addDayDialog: {
      title: 'Tag manuell erfassen',
      description:
        'Für Monteure ohne App/Handy: Arbeitszeiten für einen Tag der Woche eintragen.',
      date: 'Datum',
      start: 'Arbeitsbeginn',
      end: 'Arbeitsende',
      break: 'Pause (Minuten)',
      comment: 'Kommentar',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
    },
    signatures: {
      timeline: 'Status-Verlauf',
      generated: 'Generiert',
      submitted: 'Eingereicht',
      reviewed: 'Geprüft',
      approved: 'Genehmigt',
      rejected: 'Zurückgewiesen',
      rejectionReason: 'Grund der Zurückweisung',
      existing: 'Vorhandene Unterschriften',
      none: 'Noch keine Unterschriften.',
      present: 'Unterschrift vorhanden',
      signedAt: 'Unterschrieben am',
      signAsWorker: 'Als Monteur unterschreiben',
      signAsSupervisor: 'Als Vorarbeiter / Büro unterschreiben',
      signAsManager: 'Als Projektleiter unterschreiben',
      hint: 'Mit Finger oder Stift im Feld unterschreiben.',
    },
    signerType: {
      WORKER: 'Monteur',
      CUSTOMER: 'Kunden-PL',
      SUPERVISOR: 'Vorarbeiter / Büro',
      MANAGER: 'Projektleiter',
    },
    actions: {
      submit: 'Einreichen',
      approve: 'Genehmigen',
      reject: 'Zurückweisen',
      archive: 'Archivieren',
      downloadPdf: 'PDF herunterladen',
      regenerate: 'Neu generieren',
    },
    archiveTitle: 'Stundenzettel archivieren?',
    archiveConfirm:
      'Der Stundenzettel wird archiviert und kann danach nicht mehr bearbeitet werden.',
    rejectDialog: {
      title: 'Stundenzettel zurückweisen',
      reason: 'Grund',
      reasonPlaceholder: 'Warum wird der Stundenzettel zurückgewiesen?',
      confirm: 'Zurückweisen',
    },
    signDialog: {
      title: 'Unterschrift',
      name: 'Name des Unterzeichners',
      clear: 'Löschen',
      confirm: 'Bestätigen',
      empty: 'Bitte zuerst unterschreiben.',
    },
    toast: {
      generated: 'Stundenzettel angelegt / aktualisiert.',
      dayUpdated: 'Tageseintrag gespeichert.',
      submitted: 'Stundenzettel eingereicht.',
      approved: 'Stundenzettel genehmigt.',
      rejected: 'Stundenzettel zurückgewiesen.',
      signed: 'Unterschrift gespeichert.',
      archived: 'Stundenzettel archiviert.',
      pdf: 'PDF wird heruntergeladen.',
      regenerated: 'Aus Stempelungen neu geladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  } as const;
