/** UI-Texte: `todos`. */
export const todos = {
    title: 'Aufgaben',
    titleSingle: 'Aufgabe',
    new: 'Neue Aufgabe',
    edit: 'Aufgabe bearbeiten',
    status: {
      OPEN: 'Offen',
      IN_PROGRESS: 'In Bearbeitung',
      DONE: 'Erledigt',
      CANCELLED: 'Abgebrochen',
    } as Record<string, string>,
    priority: {
      LOW: 'Niedrig',
      MEDIUM: 'Mittel',
      HIGH: 'Hoch',
      URGENT: 'Dringend',
    } as Record<string, string>,
    fields: {
      title: 'Titel',
      description: 'Beschreibung',
      priority: 'Priorität',
      dueDate: 'Fällig am',
      assignedTo: 'Zugewiesen an',
      linkedEntity: 'Verknüpfung',
      status: 'Status',
    },
    entityType: {
      CUSTOMER: 'Kunde',
      PROJECT: 'Projekt',
      WORKER: 'Monteur',
      SUBCONTRACTOR: 'Subunternehmen',
      EQUIPMENT: 'Gerät',
    } as Record<string, string>,
    filter: {
      all: 'Alle',
      open: 'Offen',
      inProgress: 'In Bearbeitung',
      done: 'Erledigt',
    },
    empty: 'Keine Aufgaben vorhanden',
    overdue: 'Überfällig',
    dashboard: {
      title: 'Meine Aufgaben',
      open: 'Offen',
      overdue: 'Überfällig',
      upcoming: 'Nächste fällige Aufgaben',
      showAll: 'Alle anzeigen →',
      noTasks: 'Keine offenen Aufgaben',
    },
    toast: {
      created: 'Aufgabe erstellt',
      updated: 'Aufgabe aktualisiert',
      completed: 'Aufgabe erledigt',
      deleted: 'Aufgabe gelöscht',
    },
    deleteConfirm: 'Diese Aufgabe wirklich löschen?',
  } as const;
