/** UI-Texte: `vehicles`. */
export const vehicles = {
    title: 'Fahrzeuge',
    subtitle: 'Fuhrpark verwalten – eigene und Sub-Fahrzeuge',
    newVehicle: 'Neues Fahrzeug',
    searchPlaceholder: 'Suche nach Kennzeichen, Name oder Marke …',
    empty: 'Noch keine Fahrzeuge vorhanden.',
    emptyAction: 'Erstes Fahrzeug anlegen →',
    noResults: 'Keine Fahrzeuge gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Fahrzeug anlegen',
    createSubtitle: 'Stammdaten erfassen – Zuweisungen folgen im Detail.',
    deleteTitle: 'Fahrzeug deaktivieren?',
    deleteConfirm:
      'Das Fahrzeug wird deaktiviert (kein Löschen). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      licensePlate: 'Kennzeichen',
      vehicle: 'Marke / Modell',
      category: 'Kategorie',
      owner: 'Eigentümer',
      status: 'Status',
      inspection: 'TÜV',
      insurance: 'Versicherung',
    },
    filters: {
      ownerType: 'Eigentümer',
      category: 'Kategorie',
      status: 'Status',
      all: 'Alle',
    },
    status: {
      available: 'Verfügbar',
      assignedTo: (name: string): string => `Zugewiesen an ${name}`,
      assigned: 'Zugewiesen',
      inactive: 'Inaktiv',
    },
    ownerType: {
      OWN: 'Eigenes Fahrzeug',
      SUBCONTRACTOR: 'Subunternehmen',
    },
    category: {
      PKW: 'PKW',
      Transporter: 'Transporter',
      LKW: 'LKW',
      Anhänger: 'Anhänger',
    },
    fuelType: {
      Diesel: 'Diesel',
      Benzin: 'Benzin',
      Elektro: 'Elektro',
      Hybrid: 'Hybrid',
    },
    expiry: {
      soon: 'Läuft bald ab',
      expired: 'Abgelaufen',
    },
    tabs: {
      master: 'Stammdaten',
      assignments: 'Zuweisungen',
      documents: 'Dokumente',
    },
    sections: {
      vehicle: 'Fahrzeug',
      owner: 'Eigentümer',
      documents: 'Dokumente & Fristen',
      notes: 'Notizen',
      currentAssignment: 'Aktuelle Zuweisung',
      history: 'Historie',
    },
    fields: {
      licensePlate: 'Kennzeichen',
      make: 'Marke',
      model: 'Modell',
      internalName: 'Interner Name',
      category: 'Kategorie',
      year: 'Baujahr',
      color: 'Farbe',
      fuelType: 'Kraftstoff',
      vin: 'Fahrgestellnummer (FIN)',
      ownerType: 'Eigentümer-Typ',
      subcontractor: 'Subunternehmen',
      nextInspection: 'Nächster TÜV/HU',
      insuranceExpiry: 'Versicherung Ablauf',
      notes: 'Notizen',
      worker: 'Monteur',
      assignedFrom: 'Zugewiesen seit',
      assignedTo: 'Bis',
      period: 'Zeitraum',
    },
    assignment: {
      assignTitle: 'Monteur zuweisen',
      reassignTitle: 'Anderen Monteur zuweisen',
      assignAction: 'Monteur zuweisen',
      reassignAction: 'Umbesetzen',
      unassignAction: 'Zuweisung beenden',
      unassignTitle: 'Zuweisung beenden?',
      unassignConfirm:
        'Die aktuelle Zuweisung wird beendet. Die Historie bleibt erhalten. Fortfahren?',
      since: 'seit',
      notAssigned: 'Aktuell keinem Monteur zugewiesen.',
      noHistory: 'Noch keine vergangenen Zuweisungen.',
      selectWorker: 'Monteur wählen …',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      deactivate: 'Deaktivieren',
      reactivate: 'Aktivieren',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      geocode: 'Koordinaten ermitteln',
    },
    deactivateTitle: 'Fahrzeug deaktivieren?',
    deactivateConfirm:
      'Das Fahrzeug wird deaktiviert und in der Liste ausgeblendet. Dies kann rückgängig gemacht werden.',
    reactivateTitle: 'Fahrzeug wieder aktivieren?',
    reactivateConfirm:
      'Das Fahrzeug wird wieder als aktiv markiert.',
    hardDeleteTitle: 'Fahrzeug endgültig löschen?',
    hardDeleteConfirm:
      'Das Fahrzeug wird unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    hardDeleteBlocked:
      'Das Fahrzeug hat Zuweisungshistorie und wurde stattdessen deaktiviert.',
    toast: {
      created: 'Fahrzeug angelegt.',
      updated: 'Fahrzeug aktualisiert.',
      deleted: 'Fahrzeug gelöscht.',
      deactivated: 'Fahrzeug deaktiviert.',
      reactivated: 'Fahrzeug aktiviert.',
      assigned: 'Monteur zugewiesen.',
      unassigned: 'Zuweisung beendet.',
      error: 'Aktion fehlgeschlagen.',
    },
    empties: {
      noActiveAssignment: 'Aktuell keinem Monteur zugewiesen.',
    },
  } as const;
