/**
 * UI-Texte für Domäne `workers` (DE-Labels der Office-Web-App).
 * Nur String-Konstanten – absichtlich ohne Kommentar je Key.
 */

export const workers = {
    title: 'Monteure',
    subtitle: 'Monteure und Personal verwalten',
    newWorker: 'Neuer Monteur',
    searchPlaceholder: 'Suche nach Name oder Monteurnr. …',
    empty: 'Noch keine Monteure vorhanden.',
    emptyAction: 'Ersten Monteur anlegen →',
    noResults: 'Keine Monteure gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Monteur anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Monteur löschen?',
    deleteConfirm:
      'Der Monteur wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    deleteBlocked:
      'Der Monteur hat aktive Zuweisungen und kann nicht gelöscht werden.',
    deactivateTitle: 'Monteur deaktivieren?',
    deactivateConfirm:
      'Der Monteur wird als inaktiv markiert. Dies kann rückgängig gemacht werden.',
    reactivateTitle: 'Monteur wieder aktivieren?',
    reactivateConfirm:
      'Der Monteur wird wieder als aktiv markiert.',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      photo: 'Foto',
      workerNumber: 'Monteurnr.',
      name: 'Name',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      subcontractor: 'Subunternehmen',
      project: 'Aktuelles Projekt',
      hourlyRate: 'Stundensatz',
    },
    filters: {
      all: 'Alle',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      subcontractor: 'Subunternehmen',
      team: 'Team',
    },
    type: {
      EMPLOYED: 'Angestellt',
      SUBCONTRACTED: 'Subunternehmen',
    },
    availability: {
      AVAILABLE: 'Verfügbar',
      ON_PROJECT: 'Im Einsatz',
      SICK: 'Krank',
      VACATION: 'Urlaub',
      UNAVAILABLE: 'Nicht verfügbar',
    },
    proficiency: {
      A1: 'A1',
      A2: 'A2',
      B1: 'B1',
      B2: 'B2',
      C1: 'C1',
      C2: 'C2',
      NATIVE: 'Muttersprache',
    },
    tabs: {
      master: 'Stammdaten',
      documents: 'Dokumente & Ausweise',
      qualifications: 'Qualifikationen & Sprachen',
      contract: 'Vertrag & Kosten',
      equipment: 'Ausrüstung',
      projects: 'Projekte & Teams',
      printTab: 'Aktuelle Ansicht drucken',
      printAll: 'Gesamtübersicht drucken',
    },
    sections: {
      personal: 'Persönlich',
      contact: 'Kontakt',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      emergency: 'Notfallkontakt',
      psa: 'PSA-Größen',
      notes: 'Notizen',
      ids: 'Ausweise & IDs',
      travelDocs: 'Reisedokumente',
      documents: 'Dokumente',
      languages: 'Sprachkenntnisse',
      certifications: 'Zertifikate & Schulungen',
      typeSub: 'Typ & Subunternehmen',
      contractData: 'Vertragsdaten',
      rates: 'Stundensätze',
      currentAssignment: 'Aktuelle Projektzuweisung',
      projectHistory: 'Projekt-Historie',
      teams: 'Teams',
    },
    fields: {
      photo: 'Profilbild',
      firstName: 'Vorname',
      lastName: 'Nachname',
      workerNumber: 'Monteur-Nummer',
      dateOfBirth: 'Geburtsdatum',
      placeOfBirth: 'Geburtsort',
      nationality: 'Nationalität',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      email: 'E-Mail',
      phone: 'Telefon',
      phoneSecondary: 'Telefon 2',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      emergencyContactName: 'Name',
      emergencyContactPhone: 'Telefon',
      emergencyContactRelation: 'Beziehung',
      shoeSize: 'Schuhgröße',
      clothingSize: 'Konfektionsgröße',
      hasDriversLicense: 'Führerschein',
      notes: 'Notizen',
      idNumber: 'Personalausweis-Nr.',
      taxNumber: 'Steuernummer',
      socialSecurityNumber: 'Sozialversicherungsnr.',
      oib: 'OIB',
      passportNumber: 'Reisepass-Nr.',
      passportExpiry: 'Reisepass gültig bis',
      residencePermitNumber: 'Aufenthaltsgenehmigung-Nr.',
      residencePermitExpiry: 'Aufenthalt gültig bis',
      workPermitNumber: 'Arbeitserlaubnis-Nr.',
      workPermitExpiry: 'Arbeitserlaubnis gültig bis',
      subcontractor: 'Subunternehmen',
      contractStart: 'Vertragsbeginn',
      contractEnd: 'Vertragsende',
      hourlyRate: 'Stundensatz (€)',
      dailyRate: 'Tagessatz (€)',
      language: 'Sprache',
      proficiency: 'Niveau',
      certName: 'Bezeichnung',
      issuedBy: 'Ausgestellt von',
      issuedDate: 'Ausgestellt am',
      expiryDate: 'Gültig bis',
      role: 'Rolle',
      project: 'Projekt',
      since: 'Seit',
      period: 'Zeitraum',
      team: 'Team',
      equipmentName: 'Equipment',
      category: 'Kategorie',
      issuedAt: 'Ausgegeben am',
      returnedAt: 'Zurückgegeben am',
      condition: 'Zustand',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      deactivate: 'Deaktivieren',
      reactivate: 'Aktivieren',
      delete: 'Löschen',
      print: 'Drucken',
      add: 'Hinzufügen',
      addLanguage: 'Sprache hinzufügen',
      addCertification: 'Zertifikat hinzufügen',
      uploadPhoto: 'Foto hochladen',
      uploading: 'Wird hochgeladen …',
      changePhoto: 'Foto ändern',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      openRoute: 'Route öffnen',
      changeAvailability: 'Verfügbarkeit ändern',
      endAssignment: 'Zuweisung beenden',
      addToTeam: 'Zu Team hinzufügen',
      issueEquipment: 'Equipment ausgeben',
      returnEquipment: 'Rückgabe',
      openSubcontractor: 'Subunternehmen öffnen',
    },
    empties: {
      languages: 'Noch keine Sprachkenntnisse erfasst.',
      certifications: 'Noch keine Zertifikate erfasst.',
      documents: 'Noch keine Dokumente.',
      equipment: 'Kein Equipment ausgegeben.',
      currentAssignment: 'Aktuell keinem Projekt zugewiesen.',
      projectHistory: 'Noch keine vergangenen Zuweisungen.',
      teams: 'Noch keinem Team zugeordnet.',
      addNow: 'Jetzt anlegen →',
    },
    expiry: {
      soon: 'Läuft bald ab',
      expired: 'Abgelaufen',
    },
    equipmentHint:
      'Die Ausgabe und Rückgabe von Ausrüstung wird in einem späteren Auftrag aktiviert.',
    documentTypes: {
      PASSPORT: 'Reisepass',
      ID_CARD: 'Personalausweis',
      WORK_PERMIT: 'Arbeitserlaubnis',
      RESIDENCE_PERMIT: 'Aufenthaltsgenehmigung',
      CERTIFICATION: 'Zertifikat',
      HEALTH_CERTIFICATE: 'Gesundheitszeugnis',
      WORKER_PHOTO: 'Profilbild',
      CONTRACT: 'Vertrag',
      OTHER: 'Sonstiges',
    },
    toast: {
      created: 'Monteur angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Monteur gelöscht.',
      deactivated: 'Monteur deaktiviert.',
      reactivated: 'Monteur aktiviert.',
      photoUploaded: 'Profilbild aktualisiert.',
      photoError: 'Profilbild konnte nicht hochgeladen werden.',
      languageAdded: 'Sprache hinzugefügt.',
      certificationSaved: 'Zertifikat gespeichert.',
      availabilityChanged: 'Verfügbarkeit geändert.',
      assignmentEnded: 'Zuweisung beendet.',
      itemDeleted: 'Eintrag entfernt.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
      pinSet: 'PIN erfolgreich gesetzt.',
      pinEmailSent: 'PIN per E-Mail gesendet.',
      pinEmailFailed: 'PIN-E-Mail konnte nicht gesendet werden.',
    },
    pin: {
      title: 'Stempeluhr-PIN',
      label: 'PIN (6 Ziffern)',
      placeholder: '000000',
      set: 'PIN setzen',
      sendEmail: 'PIN per E-Mail senden',
      setting: 'Wird gesetzt …',
      sending: 'Wird gesendet …',
      hint: 'Die PIN wird für die Monteur-Stempeluhr und den Kiosk benötigt. Sie bleibt hier sichtbar hinterlegt.',
      current: 'Aktuelle PIN',
      none: 'Noch keine PIN gesetzt.',
      legacy:
        'Es ist eine PIN hinterlegt, die vor dem Update gesetzt wurde – bitte neu setzen, damit sie hier angezeigt werden kann.',
      noEmail: 'Monteur hat keine E-Mail-Adresse hinterlegt.',
      validation: 'PIN muss genau 6 Ziffern sein.',
      kioskAccess: 'Kiosk (work.vivahome.de) nutzen',
      kioskAccessHint:
        'Wenn aus: Anmeldung am Baustellen-Kiosk mit dieser PIN ist gesperrt (Monteur-App bleibt möglich).',
      validFrom: 'Gültig ab',
      validTo: 'Gültig bis (optional)',
      validToHint: 'Leer = unbegrenzt. Nach Ablauf schlägt der PIN-Login fehl.',
    },
    validation: {
      subcontractorRequired:
        'Für Subunternehmer-Monteure muss ein Subunternehmen gewählt werden.',
    },
  } as const;
