/** UI-Texte: `workerApp`. */
export const workerApp = {
    title: 'Zeiterfassung',
    pin: {
      title: 'Monteur-Anmeldung',
      subtitle: 'PIN eingeben',
      clear: 'Löschen',
      backspace: 'Zurück',
      submit: 'Anmelden',
      submitting: 'Wird geprüft …',
      error: 'Falsche PIN. Bitte erneut versuchen.',
      hint: '6-stellige PIN',
    },
    dashboard: {
      greeting: 'Hallo',
      currentProject: 'Aktuelles Projekt',
      noProject: 'Kein aktives Projekt zugewiesen.',
      upcomingProjects: 'Zukünftige Projekte',
      clockedInSince: 'Eingestempelt seit',
      notClockedIn: 'Nicht eingestempelt',
      start: 'Arbeit starten',
      stop: 'Arbeit beenden',
      working: 'Wird verarbeitet …',
      todayTitle: 'Heutige Zeiten',
      todayEmpty: 'Heute noch keine Stempelungen.',
      clockIn: 'Ein',
      clockOut: 'Aus',
      gpsActive: 'GPS aktiv',
      gpsInactive: 'GPS inaktiv',
      addPhoto: 'Arbeitsfoto hinzufügen',
      photoComment: 'Kommentar (optional)',
      photoUpload: 'Hochladen',
      photoUploading: 'Wird hochgeladen …',
      photoCancel: 'Abbrechen',
      logout: 'Abmelden',
    },
    toast: {
      clockedIn: 'Eingestempelt.',
      clockedOut: 'Ausgestempelt.',
      photoUploaded: 'Foto hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      noProject: 'Bitte zuerst ein Projekt auswählen.',
      savedPending: 'Gespeichert – wird synchronisiert',
    },
  } as const;
