# Office deploy configuration (auto-generated)
remoteName="origin"
branch="main"
repoUrl="https://github.com/vengelst/office.git"
serverHost="vivahome.de"
serverUser="root"
serverPath="/opt/office"
nginxConfigLocalPath="deploy/nginx/office.vivahome.de.conf"
nginxConfigName="office.vivahome.de.conf"
nginxMinioConfigLocalPath="deploy/nginx/minio.office.vivahome.de.conf"
nginxMinioConfigName="minio.office.vivahome.de.conf"
nginxSitesAvailablePath="/etc/nginx/sites-available"
nginxSitesEnabledPath="/etc/nginx/sites-enabled"
forceServerReset="true"
