/**
 * Zentrale UI-Texte (Vorbereitung i18n).
 * Keine hartcodierten Strings in Komponenten – alles hier referenzieren.
 */
export const texts = {
  app: {
    name: 'Office',
    tagline: 'CRM · Projekte · Monteure · Zeiterfassung',
  },
  nav: {
    dashboard: 'Dashboard',
    customers: 'Kunden',
    projects: 'Projekte',
    workers: 'Monteure',
    teams: 'Teams',
    subcontractors: 'Subunternehmen',
    vehicles: 'Fahrzeuge',
    timeClock: 'Stempeluhr',
    timesheets: 'Stundenzettel',
    breakRules: 'Pausenregeln',
    invoices: 'Rechnungen',
    settings: 'Einstellungen',
    sections: {
      operations: 'Betrieb',
      finance: 'Finanzen',
      admin: 'Administration',
      settings: 'Einstellungen',
    },
  },
  login: {
    title: 'Anmelden',
    subtitle: 'Melde dich mit deinen Zugangsdaten an.',
    email: 'E-Mail',
    emailPlaceholder: 'name@office.local',
    password: 'Passwort',
    passwordPlaceholder: '••••••••',
    submit: 'Anmelden',
    submitting: 'Wird angemeldet …',
    errorTitle: 'Anmeldung fehlgeschlagen',
    errorGeneric: 'E-Mail oder Passwort ist ungültig.',
  },
  header: {
    toggleTheme: 'Design wechseln',
    logout: 'Abmelden',
    openMenu: 'Menü öffnen',
    account: 'Konto',
  },
  dashboard: {
    title: 'Dashboard',
    welcome: 'Willkommen zurück',
    cards: {
      customers: 'Aktive Kunden',
      projects: 'Laufende Projekte',
      workers: 'Aktive Monteure',
      hours: 'Stunden diese Woche',
    },
    placeholder: 'Kennzahlen folgen in einem späteren Auftrag.',
    clockedIn: {
      title: 'Heute eingestempelt',
      subtitle: 'Aktuell eingestempelte Monteure · zur Live-Übersicht',
    },
    workers: {
      title: 'Monteur-Verfügbarkeit',
      available: 'Verfügbar',
      onProject: 'Im Einsatz',
      absent: 'Krank / Urlaub',
      expiringTitle: 'Ablaufende Dokumente',
      expiringWarning: (n: number): string =>
        n === 1
          ? '1 Monteur hat ein bald ablaufendes Dokument.'
          : `${n} Monteure haben bald ablaufende Dokumente.`,
      expiringNone: 'Keine ablaufenden Dokumente.',
      viewAll: 'Alle Monteure →',
    },
    invoices: {
      openTitle: 'Offene Ausgangsrechnungen',
      openSubtitle: 'Noch nicht beglichen · zu den Rechnungen',
      overdueTitle: 'Überfällige Rechnungen',
      overdueWarning: (n: number): string =>
        n === 1
          ? '1 Rechnung ist überfällig.'
          : `${n} Rechnungen sind überfällig.`,
      overdueNone: 'Keine überfälligen Rechnungen.',
      count: (n: number): string => (n === 1 ? '1 offen' : `${n} offen`),
    },
    vehicles: {
      title: 'Fahrzeuge',
      total: 'Gesamt',
      assigned: 'Zugewiesen',
      expiringTitle: 'TÜV/Versicherung',
      expiringWarning: (n: number): string =>
        n === 1
          ? '1 Fahrzeug mit ablaufender Frist.'
          : `${n} Fahrzeuge mit ablaufenden Fristen.`,
      expiringNone: 'Alle Fristen aktuell.',
      viewAll: 'Alle Fahrzeuge →',
    },
  },
  customers: {
    title: 'Kunden',
    subtitle: 'Kundenstamm verwalten',
    newCustomer: 'Neuer Kunde',
    searchPlaceholder: 'Suche nach Name oder Kundennr. …',
    empty: 'Noch keine Kunden vorhanden.',
    emptyAction: 'Ersten Kunden anlegen →',
    noResults: 'Keine Kunden gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Kunden anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Kunde löschen?',
    deleteConfirm:
      'Der Kunde wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      customerNumber: 'Kundennr.',
      companyName: 'Firmenname',
      city: 'Ort',
      industry: 'Branche',
      rating: 'Bewertung',
      status: 'Status',
    },
    status: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
    },
    tabs: {
      master: 'Stammdaten',
      emails: 'E-Mails',
      bankAccounts: 'Bankverbindungen',
      branches: 'Niederlassungen',
      contacts: 'Ansprechpartner',
      businessCards: 'Visitenkarten',
      submissions: 'Ausschreibungen',
      documents: 'Dokumente',
      printTab: 'Aktuelle Ansicht drucken',
      printAll: 'Gesamtübersicht drucken',
    },
    fields: {
      companyName: 'Firmenname',
      legalForm: 'Rechtsform',
      customerNumber: 'Kundennummer',
      status: 'Status',
      industry: 'Branche',
      rating: 'Bewertung',
      paymentTermDays: 'Zahlungsziel (Tage)',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      phone: 'Telefon',
      website: 'Website',
      vatId: 'USt-ID',
      taxNumber: 'Steuernummer',
      notes: 'Notizen',
      email: 'E-Mail',
      emailType: 'Typ',
      label: 'Bezeichnung',
      isPrimary: 'Primär',
      bankName: 'Bankname',
      iban: 'IBAN',
      bic: 'BIC',
      accountHolder: 'Kontoinhaber',
      branchName: 'Name',
      branchType: 'Typ',
      title: 'Anrede',
      firstName: 'Vorname',
      lastName: 'Nachname',
      role: 'Funktion',
      department: 'Abteilung',
      branch: 'Niederlassung',
      phoneMobile: 'Mobil',
      phoneLandline: 'Festnetz',
      birthday: 'Geburtstag',
      linkedInUrl: 'LinkedIn',
      preferredContactMethod: 'Bevorzugter Kontakt',
      isAccountingContact: 'Buchhaltung',
      isProjectContact: 'Projektleitung',
      isSignatory: 'Unterschriftsberechtigt',
    },
    sections: {
      base: 'Basisdaten',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      contactInfo: 'Kontakt',
      tax: 'Steuer',
    },
    actions: {
      openRoute: 'Route öffnen',
      addEmail: 'E-Mail hinzufügen',
      addBankAccount: 'Bankverbindung hinzufügen',
      addBranch: 'Niederlassung hinzufügen',
      addContact: 'Ansprechpartner hinzufügen',
      uploadBusinessCard: 'Visitenkarte hochladen',
      scanBusinessCard: 'Visitenkarte scannen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      print: 'Drucken',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      setPrimary: 'Als primär',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      details: 'Details',
      close: 'Schließen',
    },
    empties: {
      emails: 'Noch keine E-Mail-Adressen.',
      bankAccounts: 'Noch keine Bankverbindungen.',
      branches: 'Noch keine Niederlassungen.',
      contacts: 'Noch keine Ansprechpartner.',
      documents: 'Noch keine Dokumente.',
      addNow: 'Jetzt anlegen →',
    },
    headquarters: 'Hauptsitz',
    allBranches: 'Alle Standorte',
    coordinates: 'Koordinaten',
    branchContacts: 'Ansprechpartner',
    branchContactsEmpty: 'Keine Ansprechpartner für diese Niederlassung.',
    maxBankReached: 'Maximal 2 Bankverbindungen erreicht.',
    documentTypes: {
      BUSINESS_CARD: 'Visitenkarte',
      CONTRACT: 'Vertrag',
      LOGO: 'Logo',
      CERTIFICATE: 'Zertifikat',
      NOTE_DOCUMENT: 'Notiz-Dokument',
      OTHER: 'Sonstiges',
    },
    emailTypes: {
      GENERAL: 'Allgemein',
      BILLING: 'Rechnung',
      SERVICE: 'Service',
      SUPPORT: 'Support',
      PROJECT: 'Projekt',
      OTHER: 'Sonstiges',
    },
    branchTypes: {
      HEADQUARTERS: 'Hauptsitz',
      OFFICE: 'Büro',
      WAREHOUSE: 'Lager',
      SITE: 'Standort',
      OTHER: 'Sonstiges',
    },
    contactMethods: {
      EMAIL: 'E-Mail',
      PHONE: 'Festnetz',
      MOBILE: 'Mobil',
    },
    contactSearch: {
      button: 'Kontakte suchen',
      placeholder: 'Website-URL eingeben...',
      loading: 'Suche Kontakte...',
      found: (n: number): string =>
        `${n} Kontaktperson${n !== 1 ? 'en' : ''} gefunden`,
      noResults: 'Keine Kontaktpersonen gefunden',
      selectAll: 'Alle auswählen',
      selectNone: 'Keine auswählen',
      import: 'Ausgewählte übernehmen',
      importing: 'Kontakte werden angelegt...',
      success: (n: number): string =>
        `${n} Kontakt${n !== 1 ? 'e' : ''} erfolgreich angelegt`,
      syncToGoogle: 'Zu Google Kontakte synchronisieren',
    },
    research: {
      button: 'Auto-Recherche',
      loading: 'Recherchiere …',
      dialogTitle: 'Auto-Recherche Ergebnis',
      companySection: 'Firmendaten',
      contactsSection: 'Ansprechpartner',
      socialSection: 'Social Media',
      sources: 'Quellen',
      confidence: 'Konfidenz',
      field: 'Feld',
      value: 'Gefundener Wert',
      apply: 'Ausgewählte übernehmen',
      applyContact: 'Übernehmen',
      syncGoogle: 'Mit Google Kontakte synchronisieren',
      syncGoogleHint: 'Kontakt wird in Google Kontakte angelegt/aktualisiert',
      noData: 'Keine Daten gefunden.',
      serviceError: 'Research-Service nicht verfügbar',
      applied: (fields: number, contacts: number): string =>
        `${fields} Felder und ${contacts} Kontakte übernommen`,
    },
    submissions: {
      tab: 'Ausschreibungen',
      title: 'Ausschreibungen',
      newSubmission: 'Neue Ausschreibung',
      searchButton: 'Ausschreibungen suchen',
      empty: 'Noch keine Ausschreibungen.',
      addNow: 'Jetzt anlegen →',
      columns: {
        title: 'Titel',
        status: 'Status',
        priority: 'Priorität',
        deadline: 'Abgabefrist',
        value: 'Wert',
        reference: 'Referenz',
      },
      status: {
        OPEN: 'Offen',
        IN_PROGRESS: 'In Bearbeitung',
        SUBMITTED: 'Eingereicht',
        WON: 'Gewonnen',
        LOST: 'Verloren',
        CANCELLED: 'Abgesagt',
      } as Record<string, string>,
      priority: {
        LOW: 'Niedrig',
        MEDIUM: 'Mittel',
        HIGH: 'Hoch',
        URGENT: 'Dringend',
      } as Record<string, string>,
      fields: {
        title: 'Titel',
        description: 'Beschreibung',
        reference: 'Referenz/Vergabenummer',
        source: 'Quelle/URL',
        status: 'Status',
        priority: 'Priorität',
        deadline: 'Abgabefrist',
        startDate: 'Projektbeginn',
        endDate: 'Projektende',
        value: 'Geschätzter Wert (€)',
        contactName: 'Ansprechpartner',
        contactEmail: 'E-Mail',
        contactPhone: 'Telefon',
        requirements: 'Anforderungen',
        notes: 'Notizen',
      },
      sections: {
        base: 'Basisdaten',
        dates: 'Termine',
        contact: 'Ansprechpartner',
        details: 'Details',
      },
      search: {
        dialogTitle: 'Ausschreibungen suchen',
        urlPlaceholder: 'URL der Ausschreibungsseite eingeben …',
        searching: 'Suche Ausschreibungen …',
        found: (n: number): string =>
          `${n} Ausschreibung${n !== 1 ? 'en' : ''} gefunden`,
        noResults: 'Keine Ausschreibungen gefunden.',
        selectAll: 'Alle auswählen',
        selectNone: 'Keine auswählen',
        import: 'Ausgewählte importieren',
        importing: 'Wird importiert …',
        imported: (n: number): string =>
          `${n} Ausschreibung${n !== 1 ? 'en' : ''} importiert`,
        confidence: 'Konfidenz',
      },
      toast: {
        created: 'Ausschreibung angelegt.',
        updated: 'Ausschreibung gespeichert.',
        deleted: 'Ausschreibung gelöscht.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    toast: {
      created: 'Kunde angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Kunde gelöscht.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      scanSuccess: 'Visitenkarte erfolgreich gescannt.',
      scanError: 'Visitenkarte konnte nicht gescannt werden.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  },
  projects: {
    title: 'Projekte',
    subtitle: 'Projekte planen und steuern',
    newProject: 'Neues Projekt',
    searchPlaceholder: 'Suche nach Projektnr., Titel oder Kunde …',
    empty: 'Noch keine Projekte vorhanden.',
    emptyAction: 'Erstes Projekt anlegen →',
    noResults: 'Keine Projekte gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Projekt anlegen',
    createSubtitle: 'Stammdaten erfassen – Standorte und Zuordnungen folgen im Detail.',
    deleteTitle: 'Projekt löschen?',
    deleteConfirm:
      'Das Projekt wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      projectNumber: 'Projektnr.',
      title: 'Titel',
      customer: 'Kunde',
      serviceType: 'Leistungsart',
      priority: 'Priorität',
      status: 'Status',
      plannedStart: 'Start (geplant)',
    },
    tabs: {
      stammdaten: 'Stammdaten',
      standorte: 'Standorte',
      monteure: 'Monteure',
      equipment: 'Equipment',
      dokumente: 'Dokumente',
      emailVerteiler: 'E-Mail-Verteiler',
      notizenVerlauf: 'Notizen & Verlauf',
    },
    status: {
      DRAFT: 'Entwurf',
      PLANNED: 'Geplant',
      ACTIVE: 'Aktiv',
      PAUSED: 'Pausiert',
      COMPLETED: 'Abgeschlossen',
      CANCELED: 'Abgebrochen',
    },
    priority: {
      LOW: 'Niedrig',
      MEDIUM: 'Mittel',
      HIGH: 'Hoch',
      URGENT: 'Dringend',
    },
    serviceType: {
      VIDEO: 'Videotechnik',
      ELECTRICAL: 'Elektrotechnik',
      SERVICE: 'Service',
      OTHER: 'Sonstiges',
    },
    billingMode: {
      HOURLY_PACKAGE: 'Stunden-Paket',
      UNIT_BASED: 'Nach Einheiten',
      MIXED: 'Gemischt',
    },
    fields: {
      projectNumber: 'Projektnummer',
      title: 'Titel',
      description: 'Beschreibung',
      customer: 'Kunde',
      branch: 'Niederlassung',
      contact: 'Ansprechpartner',
      serviceType: 'Leistungsart',
      priority: 'Priorität',
      status: 'Status',
      projectManager: 'Projektleiter',
      plannedStart: 'Geplanter Start',
      plannedEnd: 'Geplantes Ende',
      actualStart: 'Tatsächlicher Start',
      actualEnd: 'Tatsächliches Ende',
      billingMode: 'Abrechnungsart',
      weeklyPackageHours: 'Paket-Stunden / Woche',
      weeklyPackagePrice: 'Paket-Preis / Woche (€)',
      overtimeRate: 'Überstundensatz (€/h)',
      pauseRule: 'Pausenregel',
      notes: 'Notizen',
      siteName: 'Standort-Name',
      siteAddress: 'Standort-Adresse',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      accessInfo: 'Zugangsinfos',
      workingHours: 'Arbeitszeiten',
      accommodation: 'Unterkunft',
      accommodationAddress: 'Unterkunft-Adresse',
      accommodationNotes: 'Unterkunft-Hinweise',
      equipmentName: 'Bezeichnung',
      equipmentDescription: 'Beschreibung',
      quantity: 'Menge',
      serialNumber: 'Seriennummer',
      issuedAt: 'Ausgegeben am',
      issuedTo: 'Ausgegeben an',
      returnedAt: 'Zurückgegeben am',
      condition: 'Zustand bei Ausgabe',
      returnCondition: 'Zustand bei Rückgabe',
      roleName: 'Funktion',
      worker: 'Monteur',
      startDate: 'Von',
      endDate: 'Bis',
      isLead: 'Teamleitung',
      recipientEmail: 'E-Mail',
      recipientName: 'Name',
      recipientType: 'Typ',
      noteBody: 'Notiz',
      sortOrder: 'Reihenfolge',
    },
    sections: {
      base: 'Basisdaten',
      classification: 'Einordnung',
      planning: 'Planung & Termine',
      billing: 'Abrechnung',
      site: 'Hauptstandort',
      accommodation: 'Unterkunft',
    },
    actions: {
      newProject: 'Neues Projekt',
      addSite: 'Standort hinzufügen',
      addEquipment: 'Equipment hinzufügen',
      addRecipient: 'Empfänger hinzufügen',
      addNote: 'Notiz hinzufügen',
      addAssignment: 'Monteur zuordnen',
      returnEquipment: 'Zurücknehmen',
      changeStatus: 'Status ändern',
      openRoute: 'Route öffnen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      print: 'Drucken',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      details: 'Details',
      close: 'Schließen',
    },
    empties: {
      sites: 'Noch keine Standorte erfasst.',
      equipment: 'Noch kein Equipment zugeordnet.',
      assignments: 'Noch keine Monteure zugeordnet.',
      recipients: 'Noch keine E-Mail-Empfänger.',
      notes: 'Noch keine Notizen.',
      documents: 'Noch keine Dokumente.',
      statusHistory: 'Noch keine Statusänderungen.',
      addNow: 'Jetzt anlegen →',
    },
    statusHistory: 'Status-Verlauf',
    activeAssignments: 'Aktive Zuordnungen',
    issuedEquipment: 'Ausgegeben (offen)',
    returnedEquipment: 'Zurückgegeben',
    coordinates: 'Koordinaten',
    calendar: {
      title: 'Projektkalender',
      today: 'Heute',
      month: 'Monat',
      week: 'Woche',
      day: 'Tag',
      noEvents: 'Keine Termine in diesem Zeitraum.',
      plannedStart: 'Geplanter Start',
      plannedEnd: 'Geplantes Ende',
      actualStart: 'Tatsächlicher Start',
      actualEnd: 'Tatsächliches Ende',
      duration: 'Laufzeit',
    },
    changeStatus: {
      title: 'Status ändern',
      newStatus: 'Neuer Status',
      comment: 'Kommentar (optional)',
      confirm: 'Status setzen',
    },
    toast: {
      created: 'Projekt angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Projekt gelöscht.',
      statusChanged: 'Status geändert.',
      siteAdded: 'Standort hinzugefügt.',
      siteDeleted: 'Standort entfernt.',
      equipmentAdded: 'Equipment hinzugefügt.',
      equipmentReturned: 'Equipment zurückgenommen.',
      assignmentAdded: 'Monteur zugeordnet.',
      assignmentEnded: 'Zuordnung beendet.',
      recipientAdded: 'Empfänger hinzugefügt.',
      noteAdded: 'Notiz gespeichert.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  workers: {
    title: 'Monteure',
    subtitle: 'Monteure und Personal verwalten',
    newWorker: 'Neuer Monteur',
    searchPlaceholder: 'Suche nach Name oder Monteurnr. …',
    empty: 'Noch keine Monteure vorhanden.',
    emptyAction: 'Ersten Monteur anlegen →',
    noResults: 'Keine Monteure gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Monteur anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Monteur löschen?',
    deleteConfirm:
      'Der Monteur wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    deleteBlocked:
      'Der Monteur hat aktive Zuweisungen und kann nicht gelöscht werden.',
    deactivateTitle: 'Monteur deaktivieren?',
    deactivateConfirm:
      'Der Monteur wird als inaktiv markiert. Dies kann rückgängig gemacht werden.',
    reactivateTitle: 'Monteur wieder aktivieren?',
    reactivateConfirm:
      'Der Monteur wird wieder als aktiv markiert.',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      photo: 'Foto',
      workerNumber: 'Monteurnr.',
      name: 'Name',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      subcontractor: 'Subunternehmen',
      project: 'Aktuelles Projekt',
      hourlyRate: 'Stundensatz',
    },
    filters: {
      all: 'Alle',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      subcontractor: 'Subunternehmen',
      team: 'Team',
    },
    type: {
      EMPLOYED: 'Angestellt',
      SUBCONTRACTED: 'Subunternehmen',
    },
    availability: {
      AVAILABLE: 'Verfügbar',
      ON_PROJECT: 'Im Einsatz',
      SICK: 'Krank',
      VACATION: 'Urlaub',
      UNAVAILABLE: 'Nicht verfügbar',
    },
    proficiency: {
      A1: 'A1',
      A2: 'A2',
      B1: 'B1',
      B2: 'B2',
      C1: 'C1',
      C2: 'C2',
      NATIVE: 'Muttersprache',
    },
    tabs: {
      master: 'Stammdaten',
      documents: 'Dokumente & Ausweise',
      qualifications: 'Qualifikationen & Sprachen',
      contract: 'Vertrag & Kosten',
      equipment: 'Ausrüstung',
      projects: 'Projekte & Teams',
    },
    sections: {
      personal: 'Persönlich',
      contact: 'Kontakt',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      emergency: 'Notfallkontakt',
      psa: 'PSA-Größen',
      notes: 'Notizen',
      ids: 'Ausweise & IDs',
      travelDocs: 'Reisedokumente',
      documents: 'Dokumente',
      languages: 'Sprachkenntnisse',
      certifications: 'Zertifikate & Schulungen',
      typeSub: 'Typ & Subunternehmen',
      contractData: 'Vertragsdaten',
      rates: 'Stundensätze',
      currentAssignment: 'Aktuelle Projektzuweisung',
      projectHistory: 'Projekt-Historie',
      teams: 'Teams',
    },
    fields: {
      photo: 'Profilbild',
      firstName: 'Vorname',
      lastName: 'Nachname',
      workerNumber: 'Monteur-Nummer',
      dateOfBirth: 'Geburtsdatum',
      placeOfBirth: 'Geburtsort',
      nationality: 'Nationalität',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      email: 'E-Mail',
      phone: 'Telefon',
      phoneSecondary: 'Telefon 2',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      emergencyContactName: 'Name',
      emergencyContactPhone: 'Telefon',
      emergencyContactRelation: 'Beziehung',
      shoeSize: 'Schuhgröße',
      clothingSize: 'Konfektionsgröße',
      hasDriversLicense: 'Führerschein',
      notes: 'Notizen',
      idNumber: 'Personalausweis-Nr.',
      taxNumber: 'Steuernummer',
      socialSecurityNumber: 'Sozialversicherungsnr.',
      oib: 'OIB',
      passportNumber: 'Reisepass-Nr.',
      passportExpiry: 'Reisepass gültig bis',
      residencePermitNumber: 'Aufenthaltsgenehmigung-Nr.',
      residencePermitExpiry: 'Aufenthalt gültig bis',
      workPermitNumber: 'Arbeitserlaubnis-Nr.',
      workPermitExpiry: 'Arbeitserlaubnis gültig bis',
      subcontractor: 'Subunternehmen',
      contractStart: 'Vertragsbeginn',
      contractEnd: 'Vertragsende',
      hourlyRate: 'Stundensatz (€)',
      dailyRate: 'Tagessatz (€)',
      language: 'Sprache',
      proficiency: 'Niveau',
      certName: 'Bezeichnung',
      issuedBy: 'Ausgestellt von',
      issuedDate: 'Ausgestellt am',
      expiryDate: 'Gültig bis',
      role: 'Rolle',
      project: 'Projekt',
      since: 'Seit',
      period: 'Zeitraum',
      team: 'Team',
      equipmentName: 'Equipment',
      category: 'Kategorie',
      issuedAt: 'Ausgegeben am',
      returnedAt: 'Zurückgegeben am',
      condition: 'Zustand',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      deactivate: 'Deaktivieren',
      reactivate: 'Aktivieren',
      delete: 'Löschen',
      print: 'Drucken',
      add: 'Hinzufügen',
      addLanguage: 'Sprache hinzufügen',
      addCertification: 'Zertifikat hinzufügen',
      uploadPhoto: 'Foto hochladen',
      uploading: 'Wird hochgeladen …',
      changePhoto: 'Foto ändern',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      openRoute: 'Route öffnen',
      changeAvailability: 'Verfügbarkeit ändern',
      endAssignment: 'Zuweisung beenden',
      addToTeam: 'Zu Team hinzufügen',
      issueEquipment: 'Equipment ausgeben',
      returnEquipment: 'Rückgabe',
      openSubcontractor: 'Subunternehmen öffnen',
    },
    empties: {
      languages: 'Noch keine Sprachkenntnisse erfasst.',
      certifications: 'Noch keine Zertifikate erfasst.',
      documents: 'Noch keine Dokumente.',
      equipment: 'Kein Equipment ausgegeben.',
      currentAssignment: 'Aktuell keinem Projekt zugewiesen.',
      projectHistory: 'Noch keine vergangenen Zuweisungen.',
      teams: 'Noch keinem Team zugeordnet.',
      addNow: 'Jetzt anlegen →',
    },
    expiry: {
      soon: 'Läuft bald ab',
      expired: 'Abgelaufen',
    },
    equipmentHint:
      'Die Ausgabe und Rückgabe von Ausrüstung wird in einem späteren Auftrag aktiviert.',
    documentTypes: {
      PASSPORT: 'Reisepass',
      ID_CARD: 'Personalausweis',
      WORK_PERMIT: 'Arbeitserlaubnis',
      RESIDENCE_PERMIT: 'Aufenthaltsgenehmigung',
      CERTIFICATION: 'Zertifikat',
      HEALTH_CERTIFICATE: 'Gesundheitszeugnis',
      WORKER_PHOTO: 'Profilbild',
      CONTRACT: 'Vertrag',
      OTHER: 'Sonstiges',
    },
    toast: {
      created: 'Monteur angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Monteur gelöscht.',
      deactivated: 'Monteur deaktiviert.',
      reactivated: 'Monteur aktiviert.',
      photoUploaded: 'Profilbild aktualisiert.',
      photoError: 'Profilbild konnte nicht hochgeladen werden.',
      languageAdded: 'Sprache hinzugefügt.',
      certificationSaved: 'Zertifikat gespeichert.',
      availabilityChanged: 'Verfügbarkeit geändert.',
      assignmentEnded: 'Zuweisung beendet.',
      itemDeleted: 'Eintrag entfernt.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
      pinSet: 'PIN erfolgreich gesetzt.',
      pinEmailSent: 'PIN per E-Mail gesendet.',
      pinEmailFailed: 'PIN-E-Mail konnte nicht gesendet werden.',
    },
    pin: {
      title: 'Stempeluhr-PIN',
      label: 'PIN (6 Ziffern)',
      placeholder: '000000',
      set: 'PIN setzen',
      sendEmail: 'PIN per E-Mail senden',
      setting: 'Wird gesetzt …',
      sending: 'Wird gesendet …',
      hint: 'Die PIN wird für die Monteur-Stempeluhr-App benötigt.',
      noEmail: 'Monteur hat keine E-Mail-Adresse hinterlegt.',
      validation: 'PIN muss genau 6 Ziffern sein.',
    },
  },
  subcontractors: {
    title: 'Subunternehmen',
    subtitle: 'Subunternehmen verwalten',
    newSubcontractor: 'Neues Subunternehmen',
    searchPlaceholder: 'Suche nach Name, Kontakt oder Ort …',
    empty: 'Noch keine Subunternehmen vorhanden.',
    emptyAction: 'Erstes Subunternehmen anlegen →',
    noResults: 'Keine Subunternehmen gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Subunternehmen anlegen',
    createSubtitle: 'Firmendaten erfassen.',
    deleteTitle: 'Subunternehmen löschen?',
    deleteConfirm:
      'Das Subunternehmen wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      name: 'Name',
      contactPerson: 'Kontaktperson',
      city: 'Ort',
      workers: 'Monteure',
    },
    sections: {
      company: 'Firmendaten',
      contact: 'Kontakt',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      tax: 'Steuer',
      bank: 'Bankverbindung',
      notes: 'Notizen',
      workers: 'Zugehörige Monteure',
    },
    fields: {
      name: 'Firmenname',
      contactPerson: 'Kontaktperson',
      email: 'E-Mail',
      phone: 'Telefon',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      taxNumber: 'Steuernummer',
      vatId: 'USt-ID',
      iban: 'IBAN',
      bic: 'BIC',
      bankName: 'Bankname',
      notes: 'Notizen',
      active: 'Aktiv',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      openRoute: 'Route öffnen',
    },
    empties: {
      workers: 'Noch keine Monteure zugeordnet.',
    },
    toast: {
      created: 'Subunternehmen angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Subunternehmen gelöscht.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  },
  teams: {
    title: 'Teams',
    subtitle: 'Monteur-Teams verwalten',
    newTeam: 'Neues Team',
    empty: 'Noch keine Teams vorhanden.',
    emptyAction: 'Erstes Team anlegen →',
    noResults: 'Team nicht gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Team',
    deleteTitle: 'Team löschen?',
    deleteConfirm: 'Das Team wird unwiderruflich gelöscht. Fortfahren?',
    leader: 'Teamleiter',
    noLeader: 'Kein Teamleiter',
    members: 'Mitglieder',
    memberCount: 'Mitglieder',
    joinedAt: 'Beigetreten am',
    sections: {
      info: 'Team-Info',
      members: 'Mitglieder',
    },
    fields: {
      name: 'Name',
      description: 'Beschreibung',
      leader: 'Teamleiter',
      worker: 'Monteur',
      role: 'Rolle',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      addMember: 'Mitglied hinzufügen',
      removeMember: 'Entfernen',
    },
    empties: {
      members: 'Noch keine Mitglieder.',
    },
    toast: {
      created: 'Team angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Team gelöscht.',
      memberAdded: 'Mitglied hinzugefügt.',
      memberRemoved: 'Mitglied entfernt.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  timesheets: {
    title: 'Stundenzettel',
    subtitle: 'Wochenstundenzettel prüfen, freigeben und exportieren',
    searchPlaceholder: 'Suche …',
    empty: 'Noch keine Stundenzettel vorhanden.',
    noResults: 'Keine Stundenzettel gefunden.',
    backToList: 'Zurück zur Übersicht',
    generate: 'Stundenzettel generieren',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      week: 'KW',
      worker: 'Monteur',
      project: 'Projekt',
      gross: 'Brutto',
      break: 'Pause',
      net: 'Netto',
      status: 'Status',
      actions: 'Aktionen',
    },
    filters: {
      all: 'Alle',
      worker: 'Monteur',
      project: 'Projekt',
      status: 'Status',
      week: 'KW',
      year: 'Jahr',
    },
    status: {
      DRAFT: 'Entwurf',
      WORKER_SIGNED: 'Monteur unterschrieben',
      CUSTOMER_SIGNED: 'Kunde unterschrieben',
      COMPLETED: 'Abgeschlossen',
      LOCKED: 'Gesperrt',
      SUBMITTED: 'Eingereicht',
      REVIEWED: 'Geprüft',
      APPROVED: 'Genehmigt',
      REJECTED: 'Zurückgewiesen',
      ARCHIVED: 'Archiviert',
    },
    tabs: {
      week: 'Wochenübersicht',
      signatures: 'Unterschriften & Status',
    },
    days: {
      MON: 'Montag',
      TUE: 'Dienstag',
      WED: 'Mittwoch',
      THU: 'Donnerstag',
      FRI: 'Freitag',
      SAT: 'Samstag',
      SUN: 'Sonntag',
    },
    week: {
      day: 'Tag',
      date: 'Datum',
      start: 'Beginn',
      end: 'Ende',
      gross: 'Brutto',
      break: 'Pause',
      net: 'Netto',
      comment: 'Kommentar',
      total: 'Summe',
      gps: 'GPS-Standort öffnen',
      noData: 'Für diesen Stundenzettel liegen keine Tageseinträge vor.',
    },
    generateDialog: {
      title: 'Stundenzettel generieren',
      description:
        'Aggregiert die Stempelungen der gewählten Woche und wendet die Pausenregeln an.',
      worker: 'Monteur',
      project: 'Projekt',
      year: 'Jahr',
      week: 'Kalenderwoche',
      selectWorker: 'Monteur wählen',
      selectProject: 'Projekt wählen',
      confirm: 'Generieren',
      generating: 'Wird generiert …',
    },
    editDay: {
      title: 'Tageseintrag korrigieren',
      start: 'Arbeitsbeginn',
      end: 'Arbeitsende',
      break: 'Pause (Minuten)',
      comment: 'Kommentar',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
    },
    signatures: {
      timeline: 'Status-Verlauf',
      generated: 'Generiert',
      submitted: 'Eingereicht',
      reviewed: 'Geprüft',
      approved: 'Genehmigt',
      rejected: 'Zurückgewiesen',
      rejectionReason: 'Grund der Zurückweisung',
      existing: 'Vorhandene Unterschriften',
      none: 'Noch keine Unterschriften.',
      present: 'Unterschrift vorhanden',
      signedAt: 'Unterschrieben am',
      signAsWorker: 'Als Monteur unterschreiben',
      signAsSupervisor: 'Als Vorarbeiter unterschreiben',
      hint: 'Mit Finger oder Stift im Feld unterschreiben.',
    },
    signerType: {
      WORKER: 'Monteur',
      CUSTOMER: 'Kunde',
      SUPERVISOR: 'Vorarbeiter',
      MANAGER: 'Projektleiter',
    },
    actions: {
      submit: 'Einreichen',
      approve: 'Genehmigen',
      reject: 'Zurückweisen',
      archive: 'Archivieren',
      downloadPdf: 'PDF herunterladen',
      regenerate: 'Neu generieren',
    },
    archiveTitle: 'Stundenzettel archivieren?',
    archiveConfirm:
      'Der Stundenzettel wird archiviert und kann danach nicht mehr bearbeitet werden.',
    rejectDialog: {
      title: 'Stundenzettel zurückweisen',
      reason: 'Grund',
      reasonPlaceholder: 'Warum wird der Stundenzettel zurückgewiesen?',
      confirm: 'Zurückweisen',
    },
    signDialog: {
      title: 'Unterschrift',
      name: 'Name des Unterzeichners',
      clear: 'Löschen',
      confirm: 'Bestätigen',
      empty: 'Bitte zuerst unterschreiben.',
    },
    toast: {
      generated: 'Stundenzettel generiert.',
      dayUpdated: 'Tageseintrag gespeichert.',
      submitted: 'Stundenzettel eingereicht.',
      approved: 'Stundenzettel genehmigt.',
      rejected: 'Stundenzettel zurückgewiesen.',
      signed: 'Unterschrift gespeichert.',
      archived: 'Stundenzettel archiviert.',
      pdf: 'PDF wird heruntergeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  timeClock: {
    title: 'Stempeluhr',
    subtitle: 'Wer ist gerade eingestempelt?',
    refresh: 'Aktualisieren',
    liveCount: (n: number): string =>
      n === 1 ? '1 Monteur eingestempelt' : `${n} Monteure eingestempelt`,
    empty: 'Aktuell ist niemand eingestempelt.',
    columns: {
      worker: 'Monteur',
      project: 'Projekt',
      customer: 'Kunde',
      since: 'Eingestempelt seit',
      duration: 'Dauer',
    },
    openWorkerApp: 'Monteur-App öffnen',
  },
  invoices: {
    title: 'Rechnungen',
    subtitle: 'Aus- und Eingangsrechnungen verwalten',
    newInvoice: 'Neue Rechnung',
    generate: 'Aus Stundenzetteln',
    searchPlaceholder: 'Suche nach Rechnungsnr. …',
    empty: 'Noch keine Rechnungen vorhanden.',
    noResults: 'Keine Rechnungen gefunden.',
    backToList: 'Zurück zur Übersicht',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    tabsType: {
      outgoing: 'Ausgangsrechnungen',
      incoming: 'Eingangsrechnungen',
    },
    columns: {
      invoiceNumber: 'Rechnungs-Nr.',
      party: 'Kunde / Sub',
      project: 'Projekt',
      period: 'Zeitraum',
      net: 'Netto',
      gross: 'Brutto',
      status: 'Status',
      dueDate: 'Fällig am',
    },
    filters: {
      all: 'Alle',
      status: 'Status',
      project: 'Projekt',
      periodFrom: 'Von',
      periodTo: 'Bis',
    },
    status: {
      DRAFT: 'Entwurf',
      SENT: 'Versendet',
      PARTIALLY_PAID: 'Teilbezahlt',
      PAID: 'Bezahlt',
      CANCELLED: 'Storniert',
    },
    type: {
      OUTGOING: 'Ausgangsrechnung',
      INCOMING: 'Eingangsrechnung',
    },
    lineType: {
      WEEKLY_PACKAGE: 'Wochenpaket',
      OVERTIME: 'Überstunden',
      UNIT_BASED: 'Einheit',
      PARTIAL_PAYMENT: 'Abschlag',
      CUSTOM: 'Frei',
    },
    overdue: 'Überfällig',
    partial: 'Teilrechnung',
    partialLabel: (n: number, pct: number | null): string =>
      pct != null ? `${n}. Abschlag (${pct}%)` : `${n}. Abschlag`,
    tabs: {
      lines: 'Positionen',
      payments: 'Zahlungen',
      details: 'Details',
    },
    lines: {
      title: 'Positionen',
      position: 'Pos',
      type: 'Typ',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einheit',
      unitPrice: 'Einzelpreis',
      total: 'Gesamt',
      add: 'Position hinzufügen',
      edit: 'Bearbeiten',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      empty: 'Noch keine Positionen erfasst.',
      readonlyHint:
        'Positionen können nur im Entwurf bearbeitet werden.',
      subtotal: 'Netto',
      tax: 'MwSt',
      grandTotal: 'Brutto',
    },
    lineDialog: {
      addTitle: 'Position hinzufügen',
      editTitle: 'Position bearbeiten',
      type: 'Typ',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einheit',
      unitPrice: 'Einzelpreis (€)',
      preview: 'Gesamt',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    payments: {
      title: 'Zahlungen',
      date: 'Datum',
      amount: 'Betrag',
      method: 'Methode',
      reference: 'Referenz',
      add: 'Zahlung erfassen',
      empty: 'Noch keine Zahlungseingänge.',
      progress: (paid: string, total: string): string =>
        `${paid} von ${total} bezahlt`,
      open: 'Offen',
      cancelledHint:
        'Für stornierte Rechnungen können keine Zahlungen erfasst werden.',
    },
    paymentDialog: {
      title: 'Zahlung erfassen',
      amount: 'Betrag (€)',
      date: 'Zahlungsdatum',
      method: 'Methode',
      reference: 'Referenz (optional)',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    methods: {
      TRANSFER: 'Überweisung',
      CASH: 'Bar',
      PAYPAL: 'PayPal',
      OTHER: 'Sonstige',
    },
    details: {
      title: 'Rechnungsdetails',
      invoiceNumber: 'Rechnungsnummer',
      type: 'Typ',
      status: 'Status',
      issueDate: 'Ausstelldatum',
      dueDate: 'Fälligkeitsdatum',
      paidDate: 'Bezahlt am',
      project: 'Projekt',
      customer: 'Kunde',
      subcontractor: 'Subunternehmen',
      period: 'Zeitraum',
      paymentTerm: 'Zahlungsziel (Tage)',
      partialTitle: 'Teilrechnung',
      partialNumber: 'Abschlagsnummer',
      partialPercentage: 'Prozentsatz (%)',
      notesTitle: 'Notizen',
      notes: 'Notizen (auf Rechnung)',
      internalNotes: 'Interne Notizen',
      createdBy: 'Erstellt von',
      none: '–',
    },
    actions: {
      send: 'Als versendet markieren',
      pdf: 'PDF Vorschau',
      cancel: 'Rechnung stornieren',
      duplicate: 'Rechnung duplizieren',
      delete: 'Entwurf löschen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
    },
    cancelDialog: {
      title: 'Rechnung stornieren?',
      description:
        'Die Rechnung wird auf „Storniert" gesetzt und die Beträge auf 0 reduziert. Dies kann nicht rückgängig gemacht werden.',
      confirm: 'Stornieren',
      cancel: 'Abbrechen',
    },
    deleteDialog: {
      title: 'Entwurf löschen?',
      description: 'Der Rechnungsentwurf wird unwiderruflich gelöscht.',
      confirm: 'Löschen',
      cancel: 'Abbrechen',
    },
    generateDialog: {
      title: 'Rechnung aus Stundenzetteln',
      description:
        'Erzeugt einen Rechnungsentwurf aus genehmigten Stundenzetteln des gewählten Zeitraums.',
      type: 'Typ',
      project: 'Projekt',
      subcontractor: 'Subunternehmen',
      periodFrom: 'Zeitraum von',
      periodTo: 'Zeitraum bis',
      selectProject: 'Projekt wählen',
      selectSubcontractor: 'Subunternehmen wählen',
      confirm: 'Generieren',
      generating: 'Wird generiert …',
    },
    create: {
      title: 'Neue Rechnung',
      subtitle: 'Rechnung manuell anlegen – Positionen folgen im Entwurf.',
      type: 'Typ',
      project: 'Projekt (optional)',
      customer: 'Kunde',
      subcontractor: 'Subunternehmen',
      selectProject: 'Projekt wählen',
      selectCustomer: 'Kunde wählen',
      selectSubcontractor: 'Subunternehmen wählen',
      none: 'Kein',
      taxRate: 'MwSt-Satz (%)',
      periodFrom: 'Zeitraum von (optional)',
      periodTo: 'Zeitraum bis (optional)',
      isPartial: 'Teilrechnung',
      partialNumber: 'Abschlagsnummer',
      partialPercentage: 'Prozentsatz (%)',
      notes: 'Notizen (auf Rechnung)',
      internalNotes: 'Interne Notizen',
      submit: 'Rechnung anlegen',
      submitting: 'Wird angelegt …',
      cancel: 'Abbrechen',
    },
    toast: {
      created: 'Rechnung angelegt.',
      generated: 'Rechnungsentwurf erstellt.',
      updated: 'Gespeichert.',
      deleted: 'Rechnung gelöscht.',
      sent: 'Rechnung als versendet markiert.',
      cancelled: 'Rechnung storniert.',
      duplicated: 'Rechnung dupliziert.',
      lineSaved: 'Position gespeichert.',
      lineDeleted: 'Position entfernt.',
      reordered: 'Reihenfolge geändert.',
      paymentSaved: 'Zahlung erfasst.',
      paymentDeleted: 'Zahlung gelöscht.',
      pdf: 'PDF wird heruntergeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  breakRules: {
    title: 'Pausenregeln',
    subtitle: 'Automatischer Pausenabzug nach Arbeitszeit',
    newRule: 'Neue Regel',
    empty: 'Noch keine Pausenregeln vorhanden.',
    deleteTitle: 'Pausenregel löschen?',
    deleteConfirm: 'Die Regel wird unwiderruflich gelöscht. Fortfahren?',
    columns: {
      name: 'Name',
      scope: 'Geltungsbereich',
      project: 'Projekt',
      threshold1: 'Ab Schwelle 1',
      threshold2: 'Ab Schwelle 2',
      active: 'Aktiv',
    },
    scope: {
      GLOBAL: 'Global',
      PROJECT: 'Projektspezifisch',
    },
    rule: (threshold: number, brk: number): string =>
      `ab ${Math.round(threshold / 60)}h → ${brk} min Pause`,
    dialog: {
      createTitle: 'Pausenregel erstellen',
      editTitle: 'Pausenregel bearbeiten',
      name: 'Name',
      scope: 'Geltungsbereich',
      project: 'Projekt',
      selectProject: 'Projekt wählen',
      autoDeduct: 'Automatischer Abzug aktiv',
      threshold1: 'Schwellenwert 1 (Minuten)',
      break1: 'Pausenabzug 1 (Minuten)',
      threshold2: 'Schwellenwert 2 (Minuten, optional)',
      break2: 'Pausenabzug 2 (Minuten, optional)',
      active: 'Regel aktiv',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
    },
    toast: {
      created: 'Pausenregel erstellt.',
      updated: 'Gespeichert.',
      deleted: 'Pausenregel gelöscht.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  workerApp: {
    title: 'Zeiterfassung',
    pin: {
      title: 'Monteur-Anmeldung',
      subtitle: 'PIN eingeben',
      clear: 'Löschen',
      backspace: 'Zurück',
      submit: 'Anmelden',
      submitting: 'Wird geprüft …',
      error: 'Falsche PIN. Bitte erneut versuchen.',
      hint: '6-stellige PIN',
    },
    dashboard: {
      greeting: 'Hallo',
      currentProject: 'Aktuelles Projekt',
      noProject: 'Kein aktives Projekt zugewiesen.',
      upcomingProjects: 'Zukünftige Projekte',
      clockedInSince: 'Eingestempelt seit',
      notClockedIn: 'Nicht eingestempelt',
      start: 'Arbeit starten',
      stop: 'Arbeit beenden',
      working: 'Wird verarbeitet …',
      todayTitle: 'Heutige Zeiten',
      todayEmpty: 'Heute noch keine Stempelungen.',
      clockIn: 'Ein',
      clockOut: 'Aus',
      gpsActive: 'GPS aktiv',
      gpsInactive: 'GPS inaktiv',
      addPhoto: 'Arbeitsfoto hinzufügen',
      photoComment: 'Kommentar (optional)',
      photoUpload: 'Hochladen',
      photoUploading: 'Wird hochgeladen …',
      photoCancel: 'Abbrechen',
      logout: 'Abmelden',
    },
    toast: {
      clockedIn: 'Eingestempelt.',
      clockedOut: 'Ausgestempelt.',
      photoUploaded: 'Foto hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      noProject: 'Bitte zuerst ein Projekt auswählen.',
    },
  },
  settings: {
    title: 'Einstellungen',
    placeholder: 'Einstellungen folgen in einem späteren Auftrag.',
    email: {
      title: 'E-Mail-Konfiguration',
      subtitle: 'SMTP-Einstellungen für den E-Mail-Versand',
      host: 'SMTP-Host',
      port: 'SMTP-Port',
      user: 'SMTP-Benutzer',
      pass: 'SMTP-Passwort',
      fromName: 'Absender-Name',
      fromEmail: 'Absender-E-Mail',
      secure: 'TLS/SSL verwenden',
      testEmail: 'Test-E-Mail senden',
      testEmailTo: 'Empfänger für Test',
      testEmailPlaceholder: 'test@example.com',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      sending: 'Wird gesendet …',
      toast: {
        saved: 'SMTP-Konfiguration gespeichert.',
        testSuccess: 'Test-E-Mail erfolgreich gesendet.',
        testFailed: 'Test-E-Mail fehlgeschlagen.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    storage: {
      title: 'Speicher & Cloud',
      subtitle: 'Google Drive Synchronisation konfigurieren',
      enabled: 'Google Drive aktivieren',
      folderId: 'Google Drive Ordner-ID',
      folderIdPlaceholder: 'z.B. 1aBcDeFgHiJkLmNoPqRsTuVwXyZ',
      serviceAccountJson: 'Service Account JSON Key',
      serviceAccountPlaceholder: 'JSON-Inhalt hier einfügen …',
      testConnection: 'Verbindung testen',
      testing: 'Wird getestet …',
      info: 'Dokumente werden parallel in MinIO (lokal) und Google Drive gespeichert.',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      toast: {
        saved: 'Speicher-Konfiguration gespeichert.',
        testSuccess: 'Verbindung erfolgreich.',
        testFailed: 'Verbindungstest fehlgeschlagen.',
        error: 'Aktion fehlgeschlagen.',
      },
    },
    nav: {
      email: 'E-Mail-Konfiguration',
      storage: 'Speicher & Cloud',
      breakRules: 'Pausenregeln',
      system: 'Server-Status',
    },
    system: {
      title: 'Server-Status',
      subtitle: 'Systemüberwachung und Ressourcenauslastung',
      refresh: 'Aktualisieren',
      lastUpdated: 'Aktualisiert',
      autoRefresh: 'Daten werden alle 30 Sekunden aktualisiert.',
      loading: 'Lade Systemdaten …',
      error: 'Systemdaten konnten nicht geladen werden.',
      retry: 'Erneut versuchen',
      backToSettings: 'Einstellungen',
      summary: {
        customers: 'Kunden',
        projects: 'Projekte',
        workers: 'Monteure',
        openTasks: 'Offene Aufgaben',
        uptime: 'Uptime',
      },
      cpu: {
        title: 'CPU',
        model: 'Modell',
        cores: 'Kerne',
        usage: 'Auslastung',
        loadAvg: 'Load Average',
      },
      memory: {
        title: 'Arbeitsspeicher',
        total: 'Gesamt',
        used: 'Belegt',
        free: 'Frei',
      },
      disk: {
        title: 'Festplatte',
        total: 'Gesamt',
        used: 'Belegt',
        available: 'Verfügbar',
      },
      services: {
        title: 'Service Health Checks',
        online: 'Online',
        offline: 'Offline',
        responseTime: 'ms',
      },
      updates: {
        title: 'OS Updates',
        containerUpdates: 'Container-Updates',
        hostUpdates: 'Host-Updates',
        noUpdates: 'Keine Updates verfügbar',
        hostNotAvailable: 'Host-Updates nicht verfügbar (kein Host-Zugriff)',
        packagesAvailable: (n: number): string =>
          n === 1 ? '1 Paket verfügbar' : `${n} Pakete verfügbar`,
        installButton: 'Updates installieren',
        installing: 'Wird installiert …',
        confirmTitle: 'Updates installieren?',
        confirmText:
          'Alle verfügbaren Container-Pakete werden aktualisiert. Fortfahren?',
        confirmButton: 'Installieren',
        cancelButton: 'Abbrechen',
        success: 'Updates erfolgreich installiert.',
        failed: 'Update-Installation fehlgeschlagen.',
      },
      database: {
        title: 'PostgreSQL Datenbank',
        size: 'Datenbankgröße',
        connections: 'Verbindungen',
        activeOf: 'aktiv von',
        cacheHitRatio: 'Cache Hit Ratio',
        version: 'Version',
        topTables: 'Top 15 Tabellen',
        tableName: 'Tabelle',
        tableSize: 'Größe',
        tableRows: 'Zeilen',
      },
      storage: {
        title: 'MinIO Storage',
        totalSize: 'Gesamtgröße',
        totalObjects: 'Objekte gesamt',
        bucketName: 'Bucket',
        bucketObjects: 'Objekte',
        bucketSize: 'Größe',
        unavailable: 'MinIO nicht erreichbar',
      },
      network: {
        title: 'Netzwerk',
        interface: 'Schnittstelle',
        received: 'Empfangen',
        sent: 'Gesendet',
      },
      serverDetails: {
        title: 'Server-Details',
        hostname: 'Hostname',
        platform: 'Plattform',
        arch: 'Architektur',
        nodeVersion: 'Node.js',
      },
      processes: {
        title: 'Prozesse (Container)',
        pid: 'PID',
        user: 'Benutzer',
        cpu: 'CPU %',
        mem: 'RAM %',
        command: 'Befehl',
      },
      appStats: {
        title: 'Anwendungsstatistiken',
        communication: 'Kommunikation (7 Tage)',
        documents: 'Dokumente gesamt',
        equipmentAssigned: 'Geräte zugewiesen',
        equipmentAvailable: 'Geräte verfügbar',
      },
      osUsers: {
        title: 'OS-Benutzer',
      },
    },
  },
  vehicles: {
    title: 'Fahrzeuge',
    subtitle: 'Fuhrpark verwalten – eigene und Sub-Fahrzeuge',
    newVehicle: 'Neues Fahrzeug',
    searchPlaceholder: 'Suche nach Kennzeichen, Name oder Marke …',
    empty: 'Noch keine Fahrzeuge vorhanden.',
    emptyAction: 'Erstes Fahrzeug anlegen →',
    noResults: 'Keine Fahrzeuge gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Fahrzeug anlegen',
    createSubtitle: 'Stammdaten erfassen – Zuweisungen folgen im Detail.',
    deleteTitle: 'Fahrzeug deaktivieren?',
    deleteConfirm:
      'Das Fahrzeug wird deaktiviert (kein Löschen). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      licensePlate: 'Kennzeichen',
      vehicle: 'Marke / Modell',
      category: 'Kategorie',
      owner: 'Eigentümer',
      status: 'Status',
      inspection: 'TÜV',
      insurance: 'Versicherung',
    },
    filters: {
      ownerType: 'Eigentümer',
      category: 'Kategorie',
      status: 'Status',
      all: 'Alle',
    },
    status: {
      available: 'Verfügbar',
      assignedTo: (name: string): string => `Zugewiesen an ${name}`,
      assigned: 'Zugewiesen',
      inactive: 'Inaktiv',
    },
    ownerType: {
      OWN: 'Eigenes Fahrzeug',
      SUBCONTRACTOR: 'Subunternehmen',
    },
    category: {
      PKW: 'PKW',
      Transporter: 'Transporter',
      LKW: 'LKW',
      Anhänger: 'Anhänger',
    },
    fuelType: {
      Diesel: 'Diesel',
      Benzin: 'Benzin',
      Elektro: 'Elektro',
      Hybrid: 'Hybrid',
    },
    expiry: {
      soon: 'Läuft bald ab',
      expired: 'Abgelaufen',
    },
    tabs: {
      master: 'Stammdaten',
      assignments: 'Zuweisungen',
      documents: 'Dokumente',
    },
    sections: {
      vehicle: 'Fahrzeug',
      owner: 'Eigentümer',
      documents: 'Dokumente & Fristen',
      notes: 'Notizen',
      currentAssignment: 'Aktuelle Zuweisung',
      history: 'Historie',
    },
    fields: {
      licensePlate: 'Kennzeichen',
      make: 'Marke',
      model: 'Modell',
      internalName: 'Interner Name',
      category: 'Kategorie',
      year: 'Baujahr',
      color: 'Farbe',
      fuelType: 'Kraftstoff',
      vin: 'Fahrgestellnummer (FIN)',
      ownerType: 'Eigentümer-Typ',
      subcontractor: 'Subunternehmen',
      nextInspection: 'Nächster TÜV/HU',
      insuranceExpiry: 'Versicherung Ablauf',
      notes: 'Notizen',
      worker: 'Monteur',
      assignedFrom: 'Zugewiesen seit',
      assignedTo: 'Bis',
      period: 'Zeitraum',
    },
    assignment: {
      assignTitle: 'Monteur zuweisen',
      assignAction: 'Monteur zuweisen',
      unassignAction: 'Zuweisung beenden',
      unassignTitle: 'Zuweisung beenden?',
      unassignConfirm:
        'Die aktuelle Zuweisung wird beendet. Fortfahren?',
      since: 'seit',
      notAssigned: 'Aktuell keinem Monteur zugewiesen.',
      noHistory: 'Noch keine vergangenen Zuweisungen.',
      selectWorker: 'Monteur wählen …',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      deactivate: 'Deaktivieren',
      reactivate: 'Aktivieren',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      geocode: 'Koordinaten ermitteln',
    },
    deactivateTitle: 'Fahrzeug deaktivieren?',
    deactivateConfirm:
      'Das Fahrzeug wird deaktiviert und in der Liste ausgeblendet. Dies kann rückgängig gemacht werden.',
    reactivateTitle: 'Fahrzeug wieder aktivieren?',
    reactivateConfirm:
      'Das Fahrzeug wird wieder als aktiv markiert.',
    hardDeleteTitle: 'Fahrzeug endgültig löschen?',
    hardDeleteConfirm:
      'Das Fahrzeug wird unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    hardDeleteBlocked:
      'Das Fahrzeug hat Zuweisungshistorie und wurde stattdessen deaktiviert.',
    toast: {
      created: 'Fahrzeug angelegt.',
      updated: 'Fahrzeug aktualisiert.',
      deleted: 'Fahrzeug gelöscht.',
      deactivated: 'Fahrzeug deaktiviert.',
      reactivated: 'Fahrzeug aktiviert.',
      assigned: 'Monteur zugewiesen.',
      unassigned: 'Zuweisung beendet.',
      error: 'Aktion fehlgeschlagen.',
    },
    empties: {
      noActiveAssignment: 'Aktuell keinem Monteur zugewiesen.',
    },
  },
  documents: {
    title: 'Dokumente',
    subtitle: 'Alle Dokumente durchsuchen und verwalten',
    nav: 'Dokumente',
    // Globale Suche
    searchPlaceholder: 'Nach Dateiname, Titel oder Tags suchen …',
    allTypes: 'Alle Typen',
    allEntities: 'Alle Bereiche',
    onlyExpiring: 'Nur ablaufende',
    results: 'Treffer',
    noResults: 'Keine Dokumente gefunden.',
    linkedTo: 'Verknüpft mit',
    uploadedAt: 'Hochgeladen',
    uploadedBy: 'von',
    // Tab / Entitäts-Ansicht
    allFolder: 'Alle',
    empty: 'Noch keine Dokumente.',
    search: 'Suchen …',
    gridView: 'Kacheln',
    listView: 'Liste',
    newFolder: 'Ordner',
    newFolderTitle: 'Neuer Ordner',
    newFolderName: 'Ordnername',
    renameFolder: 'Ordner umbenennen',
    deleteFolder: 'Ordner löschen',
    deleteFolderConfirm:
      'Ordner wirklich löschen? (nur möglich, wenn er leer ist)',
    // Aktionen
    upload: 'Hochladen',
    takePhoto: 'Foto aufnehmen',
    download: 'Herunterladen',
    open: 'Öffnen',
    preview: 'Vorschau',
    replace: 'Ersetzen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    versions: 'Versionen',
    versionHistory: 'Versions-Historie',
    deleteTitle: 'Dokument löschen?',
    deleteConfirm: 'Das Dokument wird unwiderruflich aus dem Speicher entfernt.',
    cancel: 'Abbrechen',
    save: 'Speichern',
    // Badges
    versionBadge: 'V',
    expiresOn: 'Läuft ab am',
    expired: 'Abgelaufen',
    expiringSoon: 'Läuft bald ab',
    // Upload-Dialog
    uploadTitle: 'Dokumente hochladen',
    dropZone: 'Dateien hierher ziehen oder klicken zum Auswählen',
    dropZoneActive: 'Dateien hier ablegen …',
    selectFiles: 'Dateien wählen',
    fileType: 'Typ',
    fileTitle: 'Titel',
    fileTags: 'Tags (komma-getrennt)',
    fileExpiry: 'Ablaufdatum',
    folder: 'Ordner',
    noFolder: 'Kein Ordner',
    removeFile: 'Entfernen',
    startUpload: 'Hochladen',
    uploading: 'Wird hochgeladen …',
    uploadDone: 'Upload abgeschlossen.',
    // Bild-Editor
    editorTitle: 'Bild bearbeiten',
    rotateLeft: 'Links drehen',
    rotateRight: 'Rechts drehen',
    crop: 'Zuschneiden',
    cropApply: 'Zuschnitt anwenden',
    cropCancel: 'Zuschnitt abbrechen',
    brightness: 'Helligkeit',
    contrast: 'Kontrast',
    reset: 'Zurücksetzen',
    apply: 'Übernehmen',
    // Lightbox
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    prev: 'Zurück',
    next: 'Weiter',
    close: 'Schließen',
    // Toasts
    toast: {
      uploaded: 'Dokument(e) hochgeladen.',
      replaced: 'Neue Version gespeichert.',
      deleted: 'Dokument gelöscht.',
      folderCreated: 'Ordner erstellt.',
      folderDeleted: 'Ordner gelöscht.',
      folderRenamed: 'Ordner umbenannt.',
      error: 'Aktion fehlgeschlagen.',
    },
    entityTypes: {
      CUSTOMER: 'Kunde',
      BRANCH: 'Standort',
      CONTACT: 'Kontakt',
      PROJECT: 'Projekt',
      WORKER: 'Monteur',
      VEHICLE: 'Fahrzeug',
    } as Record<string, string>,
    documentTypes: {
      PHOTO: 'Foto',
      DELIVERY_NOTE: 'Lieferschein',
      INVOICE: 'Rechnung',
      PROJECT_DOC: 'Projektdokument',
      BUSINESS_CARD: 'Visitenkarte',
      CONTRACT: 'Vertrag',
      LOGO: 'Logo',
      CERTIFICATE: 'Zertifikat',
      NOTE_DOCUMENT: 'Notiz-Dokument',
      DRAWING: 'Zeichnung',
      WORK_CONTRACT: 'Werkvertrag',
      SPECIFICATION: 'Leistungsverzeichnis',
      SITE_PHOTO: 'Baustellenfoto',
      HANDOVER_PROTOCOL: 'Abnahmeprotokoll',
      PASSPORT: 'Reisepass',
      ID_CARD: 'Personalausweis',
      WORK_PERMIT: 'Arbeitserlaubnis',
      RESIDENCE_PERMIT: 'Aufenthaltsgenehmigung',
      CERTIFICATION: 'Zertifizierung',
      HEALTH_CERTIFICATE: 'Gesundheitszeugnis',
      WORKER_PHOTO: 'Profilbild',
      REGISTRATION_DOC: 'Fahrzeugschein',
      INSURANCE_DOC: 'Versicherungsnachweis',
      INSPECTION_DOC: 'TÜV/HU-Bericht',
      OTHER: 'Sonstiges',
    } as Record<string, string>,
  },
  kiosk: {
    title: 'Kiosk-Terminal',
    setup: {
      title: 'Kiosk einrichten',
      subtitle: 'Konfiguration für dieses Gerät',
      project: 'Projekt zuweisen',
      projectPlaceholder: 'Projekt auswählen …',
      autoLogout: 'Auto-Logout (Sekunden)',
      cameraEnabled: 'Kamera erlauben',
      fullscreen: 'Vollbild erzwingen',
      adminPin: 'Admin-PIN (4–6 Ziffern)',
      adminPinHint: 'Zum Verlassen des Kiosk-Modus',
      save: 'Kiosk starten',
      saving: 'Wird gespeichert …',
      noProjects: 'Keine aktiven Projekte gefunden.',
      loginRequired: 'Bitte als Admin anmelden, um den Kiosk einzurichten.',
    },
    terminal: {
      welcome: 'Willkommen',
      pinTitle: 'PIN eingeben',
      pinHint: '6-stellige Monteur-PIN',
      pinError: 'Ungültige PIN. Bitte erneut versuchen.',
      pinChecking: 'Wird geprüft …',
      clear: 'Löschen',
      confirm: 'OK',
      notClockedIn: 'Nicht eingestempelt',
      clockedInSince: 'Eingestempelt seit',
      startWork: 'ARBEIT STARTEN',
      stopWork: 'ARBEIT BEENDEN',
      takePhoto: 'Foto aufnehmen',
      photoUploading: 'Wird hochgeladen …',
      gpsActive: 'GPS aktiv',
      gpsInactive: 'GPS nicht verfügbar',
      gpsAcquiring: 'GPS wird ermittelt …',
      autoLogout: (seconds: number): string =>
        `Automatisch zurück in ${seconds} Sek.`,
      back: 'Zurück',
      setupButton: 'Setup',
      adminPinPrompt: 'Admin-PIN eingeben',
      confirmClockIn: (name: string, time: string): string =>
        `${name} – Eingestempelt um ${time}`,
      confirmClockOut: (name: string, time: string, duration: string): string =>
        `${name} – Ausgestempelt um ${time} (${duration})`,
      goodDay: 'Guten Arbeitstag!',
      goodBye: 'Bis morgen!',
      upcomingProjects: 'Zukünftige Projekte',
      liveOverview: 'Heute eingestempelt',
      notOnSite: 'Noch nicht da',
      since: 'seit',
      processing: 'Wird verarbeitet …',
      error: 'Aktion fehlgeschlagen. Bitte erneut versuchen.',
    },
    nav: 'Kiosk-Modus',
  },
  map: {
    route: 'Route planen',
    sizeSmall: 'Klein',
    sizeMedium: 'Mittel',
    sizeLarge: 'Groß',
    noCoordinates: 'Keine Koordinaten vorhanden',
  },
  equipment: {
    title: 'Geräte & Werkzeuge',
    titleSingle: 'Gerät',
    subtitle: 'Werkzeuge und Geräte verwalten',
    new: 'Neues Gerät',
    searchPlaceholder: 'Suche nach Name, Seriennr. oder Inventarnr. …',
    empty: 'Noch keine Geräte vorhanden.',
    emptyAction: 'Erstes Gerät anlegen →',
    noResults: 'Keine Geräte gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Gerät anlegen',
    createSubtitle: 'Stammdaten erfassen – Zuweisungen folgen im Detail.',
    deleteTitle: 'Gerät löschen?',
    deleteConfirm: 'Das Gerät wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    fields: {
      name: 'Bezeichnung',
      description: 'Beschreibung',
      category: 'Kategorie',
      manufacturer: 'Hersteller',
      model: 'Modell',
      serialNumber: 'Seriennummer',
      inventoryNumber: 'Inventarnummer',
      purchaseDate: 'Kaufdatum',
      purchasePrice: 'Kaufpreis',
      status: 'Status',
      condition: 'Zustand',
      image: 'Foto',
      notes: 'Notizen',
    },
    status: {
      AVAILABLE: 'Verfügbar',
      ASSIGNED: 'Ausgegeben',
      IN_REPAIR: 'In Reparatur',
      RETIRED: 'Ausgemustert',
    } as Record<string, string>,
    condition: {
      NEW: 'Neu',
      GOOD: 'Gut',
      FAIR: 'Befriedigend',
      POOR: 'Schlecht',
      DEFECTIVE: 'Defekt',
    } as Record<string, string>,
    tabs: { master: 'Stammdaten', assignments: 'Zuweisungen' },
    sections: {
      base: 'Basisdaten',
      purchase: 'Einkauf',
      state: 'Status & Zustand',
      notes: 'Notizen',
    },
    assign: {
      button: 'Ausgeben',
      title: 'Gerät ausgeben',
      worker: 'Monteur',
      expectedReturn: 'Erwartete Rückgabe',
      notes: 'Notizen',
      submit: 'Ausgeben',
    },
    return: {
      button: 'Rückgabe',
      title: 'Gerät zurücknehmen',
      condition: 'Zustand bei Rückgabe',
      notes: 'Bemerkungen',
      submit: 'Rückgabe bestätigen',
    },
    history: {
      title: 'Zuweisungs-Historie',
      worker: 'Monteur',
      assignedAt: 'Ausgegeben am',
      returnedAt: 'Zurück am',
      expected: 'Erwartet',
      condition: 'Zustand',
      notes: 'Notizen',
      current: 'Aktuell ausgegeben',
    },
    columns: {
      name: 'Bezeichnung',
      category: 'Kategorie',
      status: 'Status',
      condition: 'Zustand',
      assignedTo: 'Zugewiesen an',
    },
    filters: {
      all: 'Alle',
      status: 'Status',
      category: 'Kategorie',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      uploadImage: 'Foto hochladen',
      changeImage: 'Foto ändern',
    },
    toast: {
      created: 'Gerät erfolgreich angelegt.',
      updated: 'Gerät aktualisiert.',
      deleted: 'Gerät gelöscht.',
      assigned: 'Gerät ausgegeben.',
      returned: 'Rückgabe registriert.',
      imageUploaded: 'Foto hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
    workerSection: 'Zugewiesene Geräte',
    workerSectionEmpty: 'Keine Geräte zugewiesen.',
  },
  communication: {
    title: 'Kommunikation',
    newEntry: 'Neuer Eintrag',
    editEntry: 'Eintrag bearbeiten',
    type: {
      PHONE_CALL: 'Telefonat',
      EMAIL: 'E-Mail',
      MEETING: 'Besprechung',
      NOTE: 'Notiz',
      INSTRUCTION: 'Anweisung',
    },
    direction: {
      INCOMING: 'Eingehend',
      OUTGOING: 'Ausgehend',
    },
    fields: {
      type: 'Art',
      direction: 'Richtung',
      contact: 'Kontaktperson',
      subject: 'Betreff',
      content: 'Inhalt',
      occurredAt: 'Datum/Uhrzeit',
      duration: 'Dauer (Minuten)',
    },
    filter: {
      all: 'Alle',
      byType: 'Nach Art filtern',
      byContact: 'Nach Kontaktperson',
    },
    empty: 'Keine Kommunikationseinträge vorhanden',
    toast: {
      created: 'Eintrag erstellt',
      updated: 'Eintrag aktualisiert',
      deleted: 'Eintrag gelöscht',
    },
    dictation: {
      start: 'Diktat starten',
      stop: 'Diktat beenden',
      notSupported: 'Spracheingabe wird von diesem Browser nicht unterstützt',
      listening: 'Aufnahme läuft...',
    },
    deleteConfirm: 'Diesen Eintrag wirklich löschen?',
  },
  todos: {
    title: 'Aufgaben',
    titleSingle: 'Aufgabe',
    new: 'Neue Aufgabe',
    edit: 'Aufgabe bearbeiten',
    status: {
      OPEN: 'Offen',
      IN_PROGRESS: 'In Bearbeitung',
      DONE: 'Erledigt',
      CANCELLED: 'Abgebrochen',
    } as Record<string, string>,
    priority: {
      LOW: 'Niedrig',
      MEDIUM: 'Mittel',
      HIGH: 'Hoch',
      URGENT: 'Dringend',
    } as Record<string, string>,
    fields: {
      title: 'Titel',
      description: 'Beschreibung',
      priority: 'Priorität',
      dueDate: 'Fällig am',
      assignedTo: 'Zugewiesen an',
      linkedEntity: 'Verknüpfung',
      status: 'Status',
    },
    entityType: {
      CUSTOMER: 'Kunde',
      PROJECT: 'Projekt',
      WORKER: 'Monteur',
      SUBCONTRACTOR: 'Subunternehmen',
      EQUIPMENT: 'Gerät',
    } as Record<string, string>,
    filter: {
      all: 'Alle',
      open: 'Offen',
      inProgress: 'In Bearbeitung',
      done: 'Erledigt',
    },
    empty: 'Keine Aufgaben vorhanden',
    overdue: 'Überfällig',
    dashboard: {
      title: 'Meine Aufgaben',
      open: 'Offen',
      overdue: 'Überfällig',
      upcoming: 'Nächste fällige Aufgaben',
      showAll: 'Alle anzeigen →',
      noTasks: 'Keine offenen Aufgaben',
    },
    toast: {
      created: 'Aufgabe erstellt',
      updated: 'Aufgabe aktualisiert',
      completed: 'Aufgabe erledigt',
      deleted: 'Aufgabe gelöscht',
    },
    deleteConfirm: 'Diese Aufgabe wirklich löschen?',
  },
  common: {
    loading: 'Wird geladen …',
    empty: 'Keine Daten vorhanden.',
  },
} as const;

export type Texts = typeof texts;
