/**
 * Zentrale UI-Texte (Vorbereitung i18n).
 * Keine hartcodierten Strings in Komponenten – alles hier referenzieren.
 */
export const texts = {
  app: {
    name: 'Office',
    tagline: 'CRM · Projekte · Monteure · Zeiterfassung',
  },
  nav: {
    dashboard: 'Dashboard',
    customers: 'Kunden',
    projects: 'Projekte',
    workers: 'Monteure',
    timesheets: 'Stundenzettel',
    settings: 'Einstellungen',
  },
  login: {
    title: 'Anmelden',
    subtitle: 'Melde dich mit deinen Zugangsdaten an.',
    email: 'E-Mail',
    emailPlaceholder: 'name@office.local',
    password: 'Passwort',
    passwordPlaceholder: '••••••••',
    submit: 'Anmelden',
    submitting: 'Wird angemeldet …',
    errorTitle: 'Anmeldung fehlgeschlagen',
    errorGeneric: 'E-Mail oder Passwort ist ungültig.',
  },
  header: {
    toggleTheme: 'Design wechseln',
    logout: 'Abmelden',
    openMenu: 'Menü öffnen',
    account: 'Konto',
  },
  dashboard: {
    title: 'Dashboard',
    welcome: 'Willkommen zurück',
    cards: {
      customers: 'Aktive Kunden',
      projects: 'Laufende Projekte',
      workers: 'Aktive Monteure',
      hours: 'Stunden diese Woche',
    },
    placeholder: 'Kennzahlen folgen in einem späteren Auftrag.',
  },
  customers: {
    title: 'Kunden',
    subtitle: 'Kundenstamm verwalten',
    newCustomer: 'Neuer Kunde',
    searchPlaceholder: 'Suche nach Name oder Kundennr. …',
    empty: 'Noch keine Kunden vorhanden.',
    emptyAction: 'Ersten Kunden anlegen →',
    noResults: 'Keine Kunden gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Kunden anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Kunde löschen?',
    deleteConfirm:
      'Der Kunde wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      customerNumber: 'Kundennr.',
      companyName: 'Firmenname',
      city: 'Ort',
      industry: 'Branche',
      rating: 'Bewertung',
      status: 'Status',
    },
    status: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
    },
    tabs: {
      master: 'Stammdaten',
      emails: 'E-Mails',
      bankAccounts: 'Bankverbindungen',
      branches: 'Niederlassungen',
      contacts: 'Ansprechpartner',
      documents: 'Dokumente',
    },
    fields: {
      companyName: 'Firmenname',
      legalForm: 'Rechtsform',
      customerNumber: 'Kundennummer',
      status: 'Status',
      industry: 'Branche',
      rating: 'Bewertung',
      paymentTermDays: 'Zahlungsziel (Tage)',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      phone: 'Telefon',
      website: 'Website',
      vatId: 'USt-ID',
      taxNumber: 'Steuernummer',
      notes: 'Notizen',
      email: 'E-Mail',
      emailType: 'Typ',
      label: 'Bezeichnung',
      isPrimary: 'Primär',
      bankName: 'Bankname',
      iban: 'IBAN',
      bic: 'BIC',
      accountHolder: 'Kontoinhaber',
      branchName: 'Name',
      branchType: 'Typ',
      title: 'Anrede',
      firstName: 'Vorname',
      lastName: 'Nachname',
      role: 'Funktion',
      department: 'Abteilung',
      branch: 'Niederlassung',
      phoneMobile: 'Mobil',
      phoneLandline: 'Festnetz',
      birthday: 'Geburtstag',
      linkedInUrl: 'LinkedIn',
      preferredContactMethod: 'Bevorzugter Kontakt',
      isAccountingContact: 'Buchhaltung',
      isProjectContact: 'Projektleitung',
      isSignatory: 'Unterschriftsberechtigt',
    },
    sections: {
      base: 'Basisdaten',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      contactInfo: 'Kontakt',
      tax: 'Steuer',
    },
    actions: {
      openRoute: 'Route öffnen',
      addEmail: 'E-Mail hinzufügen',
      addBankAccount: 'Bankverbindung hinzufügen',
      addBranch: 'Niederlassung hinzufügen',
      addContact: 'Ansprechpartner hinzufügen',
      uploadBusinessCard: 'Visitenkarte hochladen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      setPrimary: 'Als primär',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      details: 'Details',
      close: 'Schließen',
    },
    empties: {
      emails: 'Noch keine E-Mail-Adressen.',
      bankAccounts: 'Noch keine Bankverbindungen.',
      branches: 'Noch keine Niederlassungen.',
      contacts: 'Noch keine Ansprechpartner.',
      documents: 'Noch keine Dokumente.',
      addNow: 'Jetzt anlegen →',
    },
    headquarters: 'Hauptsitz',
    allBranches: 'Alle Standorte',
    coordinates: 'Koordinaten',
    branchContacts: 'Ansprechpartner',
    branchContactsEmpty: 'Keine Ansprechpartner für diese Niederlassung.',
    maxBankReached: 'Maximal 2 Bankverbindungen erreicht.',
    documentTypes: {
      BUSINESS_CARD: 'Visitenkarte',
      CONTRACT: 'Vertrag',
      LOGO: 'Logo',
      CERTIFICATE: 'Zertifikat',
      NOTE_DOCUMENT: 'Notiz-Dokument',
      OTHER: 'Sonstiges',
    },
    emailTypes: {
      GENERAL: 'Allgemein',
      BILLING: 'Rechnung',
      SERVICE: 'Service',
      SUPPORT: 'Support',
      PROJECT: 'Projekt',
      OTHER: 'Sonstiges',
    },
    branchTypes: {
      HEADQUARTERS: 'Hauptsitz',
      OFFICE: 'Büro',
      WAREHOUSE: 'Lager',
      SITE: 'Standort',
      OTHER: 'Sonstiges',
    },
    contactMethods: {
      EMAIL: 'E-Mail',
      PHONE: 'Festnetz',
      MOBILE: 'Mobil',
    },
    toast: {
      created: 'Kunde angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Kunde gelöscht.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  },
  projects: {
    title: 'Projekte',
    placeholder: 'Die Projektverwaltung folgt in Auftrag #2.',
  },
  workers: {
    title: 'Monteure',
    placeholder: 'Die Monteurverwaltung folgt in Auftrag #2.',
  },
  timesheets: {
    title: 'Stundenzettel',
    placeholder: 'Wochen-Stundenzettel folgen in einem späteren Auftrag.',
  },
  settings: {
    title: 'Einstellungen',
    placeholder: 'Einstellungen folgen in einem späteren Auftrag.',
  },
  common: {
    loading: 'Wird geladen …',
    empty: 'Keine Daten vorhanden.',
  },
} as const;

export type Texts = typeof texts;
