/**
 * Zentrale UI-Texte (Vorbereitung i18n).
 * Keine hartcodierten Strings in Komponenten – alles hier referenzieren.
 */
export const texts = {
  app: {
    name: 'Office',
    tagline: 'CRM · Projekte · Monteure · Zeiterfassung',
  },
  nav: {
    dashboard: 'Dashboard',
    customers: 'Kunden',
    projects: 'Projekte',
    workers: 'Monteure',
    teams: 'Teams',
    subcontractors: 'Subunternehmen',
    timesheets: 'Stundenzettel',
    settings: 'Einstellungen',
  },
  login: {
    title: 'Anmelden',
    subtitle: 'Melde dich mit deinen Zugangsdaten an.',
    email: 'E-Mail',
    emailPlaceholder: 'name@office.local',
    password: 'Passwort',
    passwordPlaceholder: '••••••••',
    submit: 'Anmelden',
    submitting: 'Wird angemeldet …',
    errorTitle: 'Anmeldung fehlgeschlagen',
    errorGeneric: 'E-Mail oder Passwort ist ungültig.',
  },
  header: {
    toggleTheme: 'Design wechseln',
    logout: 'Abmelden',
    openMenu: 'Menü öffnen',
    account: 'Konto',
  },
  dashboard: {
    title: 'Dashboard',
    welcome: 'Willkommen zurück',
    cards: {
      customers: 'Aktive Kunden',
      projects: 'Laufende Projekte',
      workers: 'Aktive Monteure',
      hours: 'Stunden diese Woche',
    },
    placeholder: 'Kennzahlen folgen in einem späteren Auftrag.',
    workers: {
      title: 'Monteur-Verfügbarkeit',
      available: 'Verfügbar',
      onProject: 'Im Einsatz',
      absent: 'Krank / Urlaub',
      expiringTitle: 'Ablaufende Dokumente',
      expiringWarning: (n: number): string =>
        n === 1
          ? '1 Monteur hat ein bald ablaufendes Dokument.'
          : `${n} Monteure haben bald ablaufende Dokumente.`,
      expiringNone: 'Keine ablaufenden Dokumente.',
      viewAll: 'Alle Monteure →',
    },
  },
  customers: {
    title: 'Kunden',
    subtitle: 'Kundenstamm verwalten',
    newCustomer: 'Neuer Kunde',
    searchPlaceholder: 'Suche nach Name oder Kundennr. …',
    empty: 'Noch keine Kunden vorhanden.',
    emptyAction: 'Ersten Kunden anlegen →',
    noResults: 'Keine Kunden gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Kunden anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Kunde löschen?',
    deleteConfirm:
      'Der Kunde wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      customerNumber: 'Kundennr.',
      companyName: 'Firmenname',
      city: 'Ort',
      industry: 'Branche',
      rating: 'Bewertung',
      status: 'Status',
    },
    status: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
    },
    tabs: {
      master: 'Stammdaten',
      emails: 'E-Mails',
      bankAccounts: 'Bankverbindungen',
      branches: 'Niederlassungen',
      contacts: 'Ansprechpartner',
      documents: 'Dokumente',
    },
    fields: {
      companyName: 'Firmenname',
      legalForm: 'Rechtsform',
      customerNumber: 'Kundennummer',
      status: 'Status',
      industry: 'Branche',
      rating: 'Bewertung',
      paymentTermDays: 'Zahlungsziel (Tage)',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      phone: 'Telefon',
      website: 'Website',
      vatId: 'USt-ID',
      taxNumber: 'Steuernummer',
      notes: 'Notizen',
      email: 'E-Mail',
      emailType: 'Typ',
      label: 'Bezeichnung',
      isPrimary: 'Primär',
      bankName: 'Bankname',
      iban: 'IBAN',
      bic: 'BIC',
      accountHolder: 'Kontoinhaber',
      branchName: 'Name',
      branchType: 'Typ',
      title: 'Anrede',
      firstName: 'Vorname',
      lastName: 'Nachname',
      role: 'Funktion',
      department: 'Abteilung',
      branch: 'Niederlassung',
      phoneMobile: 'Mobil',
      phoneLandline: 'Festnetz',
      birthday: 'Geburtstag',
      linkedInUrl: 'LinkedIn',
      preferredContactMethod: 'Bevorzugter Kontakt',
      isAccountingContact: 'Buchhaltung',
      isProjectContact: 'Projektleitung',
      isSignatory: 'Unterschriftsberechtigt',
    },
    sections: {
      base: 'Basisdaten',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      contactInfo: 'Kontakt',
      tax: 'Steuer',
    },
    actions: {
      openRoute: 'Route öffnen',
      addEmail: 'E-Mail hinzufügen',
      addBankAccount: 'Bankverbindung hinzufügen',
      addBranch: 'Niederlassung hinzufügen',
      addContact: 'Ansprechpartner hinzufügen',
      uploadBusinessCard: 'Visitenkarte hochladen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      setPrimary: 'Als primär',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      details: 'Details',
      close: 'Schließen',
    },
    empties: {
      emails: 'Noch keine E-Mail-Adressen.',
      bankAccounts: 'Noch keine Bankverbindungen.',
      branches: 'Noch keine Niederlassungen.',
      contacts: 'Noch keine Ansprechpartner.',
      documents: 'Noch keine Dokumente.',
      addNow: 'Jetzt anlegen →',
    },
    headquarters: 'Hauptsitz',
    allBranches: 'Alle Standorte',
    coordinates: 'Koordinaten',
    branchContacts: 'Ansprechpartner',
    branchContactsEmpty: 'Keine Ansprechpartner für diese Niederlassung.',
    maxBankReached: 'Maximal 2 Bankverbindungen erreicht.',
    documentTypes: {
      BUSINESS_CARD: 'Visitenkarte',
      CONTRACT: 'Vertrag',
      LOGO: 'Logo',
      CERTIFICATE: 'Zertifikat',
      NOTE_DOCUMENT: 'Notiz-Dokument',
      OTHER: 'Sonstiges',
    },
    emailTypes: {
      GENERAL: 'Allgemein',
      BILLING: 'Rechnung',
      SERVICE: 'Service',
      SUPPORT: 'Support',
      PROJECT: 'Projekt',
      OTHER: 'Sonstiges',
    },
    branchTypes: {
      HEADQUARTERS: 'Hauptsitz',
      OFFICE: 'Büro',
      WAREHOUSE: 'Lager',
      SITE: 'Standort',
      OTHER: 'Sonstiges',
    },
    contactMethods: {
      EMAIL: 'E-Mail',
      PHONE: 'Festnetz',
      MOBILE: 'Mobil',
    },
    toast: {
      created: 'Kunde angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Kunde gelöscht.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  },
  projects: {
    title: 'Projekte',
    subtitle: 'Projekte planen und steuern',
    newProject: 'Neues Projekt',
    searchPlaceholder: 'Suche nach Projektnr., Titel oder Kunde …',
    empty: 'Noch keine Projekte vorhanden.',
    emptyAction: 'Erstes Projekt anlegen →',
    noResults: 'Keine Projekte gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Projekt anlegen',
    createSubtitle: 'Stammdaten erfassen – Standorte und Zuordnungen folgen im Detail.',
    deleteTitle: 'Projekt löschen?',
    deleteConfirm:
      'Das Projekt wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      projectNumber: 'Projektnr.',
      title: 'Titel',
      customer: 'Kunde',
      serviceType: 'Leistungsart',
      priority: 'Priorität',
      status: 'Status',
      plannedStart: 'Start (geplant)',
    },
    tabs: {
      stammdaten: 'Stammdaten',
      standorte: 'Standorte',
      monteure: 'Monteure',
      equipment: 'Equipment',
      dokumente: 'Dokumente',
      emailVerteiler: 'E-Mail-Verteiler',
      notizenVerlauf: 'Notizen & Verlauf',
    },
    status: {
      DRAFT: 'Entwurf',
      PLANNED: 'Geplant',
      ACTIVE: 'Aktiv',
      PAUSED: 'Pausiert',
      COMPLETED: 'Abgeschlossen',
      CANCELED: 'Abgebrochen',
    },
    priority: {
      LOW: 'Niedrig',
      MEDIUM: 'Mittel',
      HIGH: 'Hoch',
      URGENT: 'Dringend',
    },
    serviceType: {
      VIDEO: 'Videotechnik',
      ELECTRICAL: 'Elektrotechnik',
      SERVICE: 'Service',
      OTHER: 'Sonstiges',
    },
    billingMode: {
      HOURLY_PACKAGE: 'Stunden-Paket',
      UNIT_BASED: 'Nach Einheiten',
      MIXED: 'Gemischt',
    },
    fields: {
      projectNumber: 'Projektnummer',
      title: 'Titel',
      description: 'Beschreibung',
      customer: 'Kunde',
      branch: 'Niederlassung',
      contact: 'Ansprechpartner',
      serviceType: 'Leistungsart',
      priority: 'Priorität',
      status: 'Status',
      projectManager: 'Projektleiter',
      plannedStart: 'Geplanter Start',
      plannedEnd: 'Geplantes Ende',
      actualStart: 'Tatsächlicher Start',
      actualEnd: 'Tatsächliches Ende',
      billingMode: 'Abrechnungsart',
      weeklyPackageHours: 'Paket-Stunden / Woche',
      weeklyPackagePrice: 'Paket-Preis / Woche (€)',
      overtimeRate: 'Überstundensatz (€/h)',
      pauseRule: 'Pausenregel',
      notes: 'Notizen',
      siteName: 'Standort-Name',
      siteAddress: 'Standort-Adresse',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      accessInfo: 'Zugangsinfos',
      workingHours: 'Arbeitszeiten',
      accommodation: 'Unterkunft',
      accommodationAddress: 'Unterkunft-Adresse',
      accommodationNotes: 'Unterkunft-Hinweise',
      equipmentName: 'Bezeichnung',
      equipmentDescription: 'Beschreibung',
      quantity: 'Menge',
      serialNumber: 'Seriennummer',
      issuedAt: 'Ausgegeben am',
      issuedTo: 'Ausgegeben an',
      returnedAt: 'Zurückgegeben am',
      condition: 'Zustand bei Ausgabe',
      returnCondition: 'Zustand bei Rückgabe',
      roleName: 'Funktion',
      worker: 'Monteur',
      startDate: 'Von',
      endDate: 'Bis',
      isLead: 'Teamleitung',
      recipientEmail: 'E-Mail',
      recipientName: 'Name',
      recipientType: 'Typ',
      noteBody: 'Notiz',
      sortOrder: 'Reihenfolge',
    },
    sections: {
      base: 'Basisdaten',
      classification: 'Einordnung',
      planning: 'Planung & Termine',
      billing: 'Abrechnung',
      site: 'Hauptstandort',
      accommodation: 'Unterkunft',
    },
    actions: {
      newProject: 'Neues Projekt',
      addSite: 'Standort hinzufügen',
      addEquipment: 'Equipment hinzufügen',
      addRecipient: 'Empfänger hinzufügen',
      addNote: 'Notiz hinzufügen',
      addAssignment: 'Monteur zuordnen',
      returnEquipment: 'Zurücknehmen',
      changeStatus: 'Status ändern',
      openRoute: 'Route öffnen',
      uploadDocument: 'Dokument hochladen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      add: 'Hinzufügen',
      download: 'Herunterladen',
      details: 'Details',
      close: 'Schließen',
    },
    empties: {
      sites: 'Noch keine Standorte erfasst.',
      equipment: 'Noch kein Equipment zugeordnet.',
      assignments: 'Noch keine Monteure zugeordnet.',
      recipients: 'Noch keine E-Mail-Empfänger.',
      notes: 'Noch keine Notizen.',
      documents: 'Noch keine Dokumente.',
      statusHistory: 'Noch keine Statusänderungen.',
      addNow: 'Jetzt anlegen →',
    },
    statusHistory: 'Status-Verlauf',
    activeAssignments: 'Aktive Zuordnungen',
    issuedEquipment: 'Ausgegeben (offen)',
    returnedEquipment: 'Zurückgegeben',
    coordinates: 'Koordinaten',
    calendar: {
      title: 'Projektkalender',
      today: 'Heute',
      month: 'Monat',
      week: 'Woche',
      day: 'Tag',
      noEvents: 'Keine Termine in diesem Zeitraum.',
      plannedStart: 'Geplanter Start',
      plannedEnd: 'Geplantes Ende',
      actualStart: 'Tatsächlicher Start',
      actualEnd: 'Tatsächliches Ende',
      duration: 'Laufzeit',
    },
    changeStatus: {
      title: 'Status ändern',
      newStatus: 'Neuer Status',
      comment: 'Kommentar (optional)',
      confirm: 'Status setzen',
    },
    toast: {
      created: 'Projekt angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Projekt gelöscht.',
      statusChanged: 'Status geändert.',
      siteAdded: 'Standort hinzugefügt.',
      siteDeleted: 'Standort entfernt.',
      equipmentAdded: 'Equipment hinzugefügt.',
      equipmentReturned: 'Equipment zurückgenommen.',
      assignmentAdded: 'Monteur zugeordnet.',
      assignmentEnded: 'Zuordnung beendet.',
      recipientAdded: 'Empfänger hinzugefügt.',
      noteAdded: 'Notiz gespeichert.',
      itemDeleted: 'Eintrag gelöscht.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  workers: {
    title: 'Monteure',
    subtitle: 'Monteure und Personal verwalten',
    newWorker: 'Neuer Monteur',
    searchPlaceholder: 'Suche nach Name oder Monteurnr. …',
    empty: 'Noch keine Monteure vorhanden.',
    emptyAction: 'Ersten Monteur anlegen →',
    noResults: 'Keine Monteure gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neuen Monteur anlegen',
    createSubtitle: 'Stammdaten erfassen – weitere Daten folgen im Detail.',
    deleteTitle: 'Monteur löschen?',
    deleteConfirm:
      'Der Monteur wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      photo: 'Foto',
      workerNumber: 'Monteurnr.',
      name: 'Name',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      subcontractor: 'Subunternehmen',
      project: 'Aktuelles Projekt',
      hourlyRate: 'Stundensatz',
    },
    filters: {
      all: 'Alle',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      subcontractor: 'Subunternehmen',
      team: 'Team',
    },
    type: {
      EMPLOYED: 'Angestellt',
      SUBCONTRACTED: 'Subunternehmen',
    },
    availability: {
      AVAILABLE: 'Verfügbar',
      ON_PROJECT: 'Im Einsatz',
      SICK: 'Krank',
      VACATION: 'Urlaub',
      UNAVAILABLE: 'Nicht verfügbar',
    },
    proficiency: {
      A1: 'A1',
      A2: 'A2',
      B1: 'B1',
      B2: 'B2',
      C1: 'C1',
      C2: 'C2',
      NATIVE: 'Muttersprache',
    },
    tabs: {
      master: 'Stammdaten',
      documents: 'Dokumente & Ausweise',
      qualifications: 'Qualifikationen & Sprachen',
      contract: 'Vertrag & Kosten',
      equipment: 'Ausrüstung',
      projects: 'Projekte & Teams',
    },
    sections: {
      personal: 'Persönlich',
      contact: 'Kontakt',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      emergency: 'Notfallkontakt',
      psa: 'PSA-Größen',
      notes: 'Notizen',
      ids: 'Ausweise & IDs',
      travelDocs: 'Reisedokumente',
      documents: 'Dokumente',
      languages: 'Sprachkenntnisse',
      certifications: 'Zertifikate & Schulungen',
      typeSub: 'Typ & Subunternehmen',
      contractData: 'Vertragsdaten',
      rates: 'Stundensätze',
      currentAssignment: 'Aktuelle Projektzuweisung',
      projectHistory: 'Projekt-Historie',
      teams: 'Teams',
    },
    fields: {
      photo: 'Profilbild',
      firstName: 'Vorname',
      lastName: 'Nachname',
      workerNumber: 'Monteur-Nummer',
      dateOfBirth: 'Geburtsdatum',
      placeOfBirth: 'Geburtsort',
      nationality: 'Nationalität',
      type: 'Typ',
      availability: 'Verfügbarkeit',
      email: 'E-Mail',
      phone: 'Telefon',
      phoneSecondary: 'Telefon 2',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      emergencyContactName: 'Name',
      emergencyContactPhone: 'Telefon',
      emergencyContactRelation: 'Beziehung',
      shoeSize: 'Schuhgröße',
      clothingSize: 'Konfektionsgröße',
      hasDriversLicense: 'Führerschein',
      notes: 'Notizen',
      idNumber: 'Personalausweis-Nr.',
      taxNumber: 'Steuernummer',
      socialSecurityNumber: 'Sozialversicherungsnr.',
      oib: 'OIB',
      passportNumber: 'Reisepass-Nr.',
      passportExpiry: 'Reisepass gültig bis',
      residencePermitNumber: 'Aufenthaltsgenehmigung-Nr.',
      residencePermitExpiry: 'Aufenthalt gültig bis',
      workPermitNumber: 'Arbeitserlaubnis-Nr.',
      workPermitExpiry: 'Arbeitserlaubnis gültig bis',
      subcontractor: 'Subunternehmen',
      contractStart: 'Vertragsbeginn',
      contractEnd: 'Vertragsende',
      hourlyRate: 'Stundensatz (€)',
      dailyRate: 'Tagessatz (€)',
      language: 'Sprache',
      proficiency: 'Niveau',
      certName: 'Bezeichnung',
      issuedBy: 'Ausgestellt von',
      issuedDate: 'Ausgestellt am',
      expiryDate: 'Gültig bis',
      role: 'Rolle',
      project: 'Projekt',
      since: 'Seit',
      period: 'Zeitraum',
      team: 'Team',
      equipmentName: 'Equipment',
      category: 'Kategorie',
      issuedAt: 'Ausgegeben am',
      returnedAt: 'Zurückgegeben am',
      condition: 'Zustand',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      add: 'Hinzufügen',
      addLanguage: 'Sprache hinzufügen',
      addCertification: 'Zertifikat hinzufügen',
      uploadPhoto: 'Foto hochladen',
      uploading: 'Wird hochgeladen …',
      changePhoto: 'Foto ändern',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      openRoute: 'Route öffnen',
      changeAvailability: 'Verfügbarkeit ändern',
      endAssignment: 'Zuweisung beenden',
      addToTeam: 'Zu Team hinzufügen',
      issueEquipment: 'Equipment ausgeben',
      returnEquipment: 'Rückgabe',
      openSubcontractor: 'Subunternehmen öffnen',
    },
    empties: {
      languages: 'Noch keine Sprachkenntnisse erfasst.',
      certifications: 'Noch keine Zertifikate erfasst.',
      documents: 'Noch keine Dokumente.',
      equipment: 'Kein Equipment ausgegeben.',
      currentAssignment: 'Aktuell keinem Projekt zugewiesen.',
      projectHistory: 'Noch keine vergangenen Zuweisungen.',
      teams: 'Noch keinem Team zugeordnet.',
      addNow: 'Jetzt anlegen →',
    },
    expiry: {
      soon: 'Läuft bald ab',
      expired: 'Abgelaufen',
    },
    equipmentHint:
      'Die Ausgabe und Rückgabe von Ausrüstung wird in einem späteren Auftrag aktiviert.',
    documentTypes: {
      PASSPORT: 'Reisepass',
      ID_CARD: 'Personalausweis',
      WORK_PERMIT: 'Arbeitserlaubnis',
      RESIDENCE_PERMIT: 'Aufenthaltsgenehmigung',
      CERTIFICATION: 'Zertifikat',
      HEALTH_CERTIFICATE: 'Gesundheitszeugnis',
      WORKER_PHOTO: 'Profilbild',
      CONTRACT: 'Vertrag',
      OTHER: 'Sonstiges',
    },
    toast: {
      created: 'Monteur angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Monteur gelöscht.',
      photoUploaded: 'Profilbild aktualisiert.',
      photoError: 'Profilbild konnte nicht hochgeladen werden.',
      languageAdded: 'Sprache hinzugefügt.',
      certificationSaved: 'Zertifikat gespeichert.',
      availabilityChanged: 'Verfügbarkeit geändert.',
      assignmentEnded: 'Zuweisung beendet.',
      itemDeleted: 'Eintrag entfernt.',
      uploaded: 'Dokument hochgeladen.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  },
  subcontractors: {
    title: 'Subunternehmen',
    subtitle: 'Subunternehmen verwalten',
    newSubcontractor: 'Neues Subunternehmen',
    searchPlaceholder: 'Suche nach Name, Kontakt oder Ort …',
    empty: 'Noch keine Subunternehmen vorhanden.',
    emptyAction: 'Erstes Subunternehmen anlegen →',
    noResults: 'Keine Subunternehmen gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Subunternehmen anlegen',
    createSubtitle: 'Firmendaten erfassen.',
    deleteTitle: 'Subunternehmen löschen?',
    deleteConfirm:
      'Das Subunternehmen wird in den Papierkorb verschoben (Soft-Delete). Fortfahren?',
    pagination: {
      showing: 'Einträge',
      page: 'Seite',
      of: 'von',
      prev: 'Zurück',
      next: 'Weiter',
    },
    columns: {
      name: 'Name',
      contactPerson: 'Kontaktperson',
      city: 'Ort',
      workers: 'Monteure',
    },
    sections: {
      company: 'Firmendaten',
      contact: 'Kontakt',
      address: 'Adresse',
      geo: 'Koordinaten & Karte',
      tax: 'Steuer',
      bank: 'Bankverbindung',
      notes: 'Notizen',
      workers: 'Zugehörige Monteure',
    },
    fields: {
      name: 'Firmenname',
      contactPerson: 'Kontaktperson',
      email: 'E-Mail',
      phone: 'Telefon',
      addressLine1: 'Straße',
      addressLine2: 'Adresszusatz',
      postalCode: 'PLZ',
      city: 'Ort',
      country: 'Land',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      mapsUrl: 'Maps-Link',
      taxNumber: 'Steuernummer',
      vatId: 'USt-ID',
      iban: 'IBAN',
      bic: 'BIC',
      bankName: 'Bankname',
      notes: 'Notizen',
      active: 'Aktiv',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      geocode: 'Koordinaten ermitteln',
      geocoding: 'Wird ermittelt …',
      openRoute: 'Route öffnen',
    },
    empties: {
      workers: 'Noch keine Monteure zugeordnet.',
    },
    toast: {
      created: 'Subunternehmen angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Subunternehmen gelöscht.',
      error: 'Aktion fehlgeschlagen.',
      geocoded: 'Koordinaten ermittelt.',
      geocodeFailed: 'Adresse konnte nicht gefunden werden.',
    },
  },
  teams: {
    title: 'Teams',
    subtitle: 'Monteur-Teams verwalten',
    newTeam: 'Neues Team',
    empty: 'Noch keine Teams vorhanden.',
    emptyAction: 'Erstes Team anlegen →',
    noResults: 'Team nicht gefunden.',
    backToList: 'Zurück zur Liste',
    createTitle: 'Neues Team',
    deleteTitle: 'Team löschen?',
    deleteConfirm: 'Das Team wird unwiderruflich gelöscht. Fortfahren?',
    leader: 'Teamleiter',
    noLeader: 'Kein Teamleiter',
    members: 'Mitglieder',
    memberCount: 'Mitglieder',
    joinedAt: 'Beigetreten am',
    sections: {
      info: 'Team-Info',
      members: 'Mitglieder',
    },
    fields: {
      name: 'Name',
      description: 'Beschreibung',
      leader: 'Teamleiter',
      worker: 'Monteur',
      role: 'Rolle',
    },
    actions: {
      save: 'Speichern',
      saving: 'Wird gespeichert …',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      addMember: 'Mitglied hinzufügen',
      removeMember: 'Entfernen',
    },
    empties: {
      members: 'Noch keine Mitglieder.',
    },
    toast: {
      created: 'Team angelegt.',
      updated: 'Gespeichert.',
      deleted: 'Team gelöscht.',
      memberAdded: 'Mitglied hinzugefügt.',
      memberRemoved: 'Mitglied entfernt.',
      error: 'Aktion fehlgeschlagen.',
    },
  },
  timesheets: {
    title: 'Stundenzettel',
    placeholder: 'Wochen-Stundenzettel folgen in einem späteren Auftrag.',
  },
  settings: {
    title: 'Einstellungen',
    placeholder: 'Einstellungen folgen in einem späteren Auftrag.',
  },
  common: {
    loading: 'Wird geladen …',
    empty: 'Keine Daten vorhanden.',
  },
} as const;

export type Texts = typeof texts;
